"""Additional TOEIC vocabulary data - Categories 06-10"""
WORDS_EXTRA_2 = {
"cat06": [
("access","v",["存取","進入"],"access data",1),
("algorithm","n",["演算法"],"search algorithm",2),
("analog","adj",["類比的"],"analog signal",2),
("application","n",["應用程式","應用"],"mobile application",1),
("archive","v",["存檔","封存"],"archive files",1),
("artificial","adj",["人工的","人造的"],"artificial intelligence",1),
("authenticate","v",["驗證","認證"],"authenticate users",2),
("automate","v",["自動化"],"automate tasks",2),
("backup","n",["備份"],"data backup",1),
("bandwidth","n",["頻寬"],"network bandwidth",2),
("binary","adj",["二進位的"],"binary code",2),
("blockchain","n",["區塊鏈"],"blockchain technology",2),
("boot","v",["啟動","開機"],"boot the system",1),
("broadband","n",["寬頻"],"broadband connection",1),
("browse","v",["瀏覽"],"browse the internet",1),
("browser","n",["瀏覽器"],"web browser",1),
("bug","n",["漏洞","錯誤"],"software bug",1),
("byte","n",["位元組"],"megabyte",2),
("cache","n",["快取"],"clear cache",2),
("click","v",["點擊"],"click a link",1),
("cloud","n",["雲端"],"cloud computing",1),
("code","n",["程式碼"],"source code",1),
("compatible","adj",["相容的"],"compatible device",1),
("compile","v",["編譯"],"compile code",2),
("component","n",["元件","組件"],"hardware component",1),
("compress","v",["壓縮"],"compress files",1),
("compute","v",["計算","運算"],"compute data",2),
("computing","n",["計算","運算"],"cloud computing",1),
("configure","v",["配置","設定"],"configure settings",1),
("connect","v",["連接","連線"],"connect to WiFi",1),
("connectivity","n",["連接性"],"internet connectivity",1),
("console","n",["控制台"],"admin console",2),
("convert","v",["轉換"],"convert files",1),
("cookie","n",["Cookie"],"browser cookies",1),
("crash","v",["當機","崩潰"],"system crash",1),
("cyber","adj",["網路的"],"cyber security",1),
("cybersecurity","n",["網路安全"],"cybersecurity measures",2),
("dashboard","n",["儀表板"],"analytics dashboard",1),
("data","n",["資料","數據"],"data analysis",1),
("database","n",["資料庫"],"relational database",1),
("debug","v",["除錯"],"debug software",2),
("decrypt","v",["解密"],"decrypt data",2),
("default","n",["預設值"],"default settings",1),
("deploy","v",["部署","佈署"],"deploy software",2),
("desktop","n",["桌面","桌上型電腦"],"desktop computer",1),
("detect","v",["偵測"],"detect threats",1),
("develop","v",["開發"],"develop software",1),
("developer","n",["開發者"],"software developer",1),
("device","n",["裝置","設備"],"mobile device",1),
("digital","adj",["數位的"],"digital transformation",1),
("directory","n",["目錄"],"file directory",1),
("disable","v",["停用"],"disable a feature",1),
("disk","n",["磁碟"],"hard disk",1),
("display","n",["顯示器","螢幕"],"LCD display",1),
("domain","n",["網域"],"domain name",1),
("download","v",["下載"],"download files",1),
("drive","n",["磁碟機","硬碟"],"flash drive",1),
("email","n",["電子郵件"],"send an email",1),
("embed","v",["嵌入"],"embed a video",2),
("enable","v",["啟用"],"enable notifications",1),
("encrypt","v",["加密"],"encrypt data",2),
("encryption","n",["加密"],"data encryption",2),
("engineer","n",["工程師"],"software engineer",1),
("enterprise","n",["企業"],"enterprise software",1),
("error","n",["錯誤"],"error message",1),
("ethernet","n",["乙太網路"],"ethernet cable",2),
("execute","v",["執行"],"execute a command",2),
("export","v",["匯出"],"export data",1),
("extension","n",["擴充功能","副檔名"],"file extension",1),
("extract","v",["擷取","解壓"],"extract files",1),
("feature","n",["功能","特性"],"key feature",1),
("feedback","n",["回饋"],"user feedback",1),
("fiber","n",["光纖"],"fiber optic",2),
("file","n",["檔案"],"save a file",1),
("filter","v",["篩選","過濾"],"filter results",1),
("firewall","n",["防火牆"],"network firewall",2),
("firmware","n",["韌體"],"update firmware",2),
("format","v",["格式化"],"format a disk",1),
("function","n",["功能","函式"],"program function",1),
("generate","v",["產生","生成"],"generate reports",1),
("gigabyte","n",["GB"],"storage capacity",1),
("glitch","n",["小故障"],"software glitch",1),
("graphics","n",["圖形","圖像"],"computer graphics",1),
("hack","v",["入侵","駭客攻擊"],"hack a system",2),
("hardware","n",["硬體"],"hardware upgrade",1),
("host","v",["主機託管"],"host a website",1),
("hyperlink","n",["超連結"],"click a hyperlink",1),
("icon","n",["圖示"],"desktop icon",1),
("implement","v",["實現","實作"],"implement a solution",1),
("import","v",["匯入"],"import data",1),
("infrastructure","n",["基礎設施"],"IT infrastructure",2),
("initialize","v",["初始化"],"initialize the system",2),
("innovate","v",["創新"],"innovate in tech",2),
("innovation","n",["創新"],"technological innovation",1),
("input","n",["輸入"],"user input",1),
("install","v",["安裝"],"install software",1),
("integrate","v",["整合"],"integrate systems",2),
("interface","n",["介面"],"user interface",1),
("internet","n",["網際網路"],"internet access",1),
("iterate","v",["迭代","重複"],"iterate on designs",2),
("keyboard","n",["鍵盤"],"wireless keyboard",1),
("laptop","n",["筆記型電腦"],"company laptop",1),
("launch","v",["推出","啟動"],"launch an app",1),
("load","v",["載入","加載"],"load a page",1),
("log","n",["日誌","記錄"],"error log",1),
("login","n",["登入"],"user login",1),
("malware","n",["惡意軟體"],"detect malware",2),
("memory","n",["記憶體"],"RAM memory",1),
("merge","v",["合併"],"merge files",2),
("migrate","v",["遷移"],"migrate data",2),
("mobile","adj",["行動的"],"mobile technology",1),
("modem","n",["數據機"],"cable modem",1),
("modify","v",["修改"],"modify settings",1),
("module","n",["模組"],"software module",2),
("monitor","n",["螢幕","監視器"],"computer monitor",1),
("navigate","v",["導覽","瀏覽"],"navigate a website",1),
("network","n",["網路"],"computer network",1),
("offline","adj",["離線的"],"work offline",1),
("online","adj",["線上的"],"online service",1),
("operate","v",["操作","運行"],"operate a system",1),
("optimize","v",["最佳化"],"optimize performance",2),
("output","n",["輸出"],"program output",1),
("outage","n",["中斷","停機"],"power outage",1),
("overwrite","v",["覆寫"],"overwrite a file",2),
("password","n",["密碼"],"change password",1),
("patch","n",["修補程式"],"security patch",2),
("peripheral","n",["周邊設備"],"computer peripheral",2),
("phishing","n",["釣魚攻擊"],"phishing email",2),
("pixel","n",["像素"],"high pixel density",2),
("platform","n",["平台"],"software platform",1),
("plugin","n",["外掛程式"],"browser plugin",1),
("portal","n",["入口網站"],"web portal",1),
("printer","n",["印表機"],"laser printer",1),
("privacy","n",["隱私"],"data privacy",1),
("processor","n",["處理器"],"CPU processor",1),
("program","n",["程式"],"computer program",1),
("programmer","n",["程式設計師"],"skilled programmer",1),
("programming","n",["程式設計"],"programming language",1),
("protocol","n",["協定"],"network protocol",2),
("proxy","n",["代理伺服器"],"proxy server",2),
("query","n",["查詢"],"database query",2),
("reboot","v",["重新啟動"],"reboot a server",1),
("recover","v",["復原","回復"],"recover data",1),
("redundancy","n",["備援","冗餘"],"data redundancy",2),
("remote","adj",["遠端的"],"remote access",1),
("render","v",["渲染","算圖"],"render graphics",2),
("repository","n",["儲存庫"],"code repository",2),
("resolution","n",["解析度"],"screen resolution",1),
("resource","n",["資源"],"system resources",1),
("restore","v",["還原","恢復"],"restore a backup",1),
("retrieve","v",["檢索","取回"],"retrieve data",2),
("router","n",["路由器"],"wireless router",1),
("scan","v",["掃描"],"scan for viruses",1),
("scalable","adj",["可擴展的"],"scalable solution",2),
("script","n",["腳本","指令碼"],"run a script",2),
("search","v",["搜尋"],"search online",1),
("secure","adj",["安全的"],"secure connection",1),
("security","n",["安全","保全"],"network security",1),
("server","n",["伺服器"],"web server",1),
("simulate","v",["模擬"],"simulate conditions",2),
("software","n",["軟體"],"software update",1),
("spam","n",["垃圾郵件"],"spam filter",1),
("specification","n",["規格"],"system specifications",1),
("storage","n",["儲存空間"],"cloud storage",1),
("stream","v",["串流"],"stream video",1),
("subscribe","v",["訂閱"],"subscribe to a service",1),
("sync","v",["同步"],"sync data",1),
("system","n",["系統"],"operating system",1),
("tablet","n",["平板電腦"],"tablet device",1),
("template","n",["模板","範本"],"email template",1),
("terminal","n",["終端機"],"computer terminal",2),
("thread","n",["執行緒"],"multi-threading",2),
("token","n",["憑證","代幣"],"security token",2),
("toolbar","n",["工具列"],"navigation toolbar",1),
("traffic","n",["流量"],"web traffic",1),
("troubleshoot","v",["排除故障"],"troubleshoot issues",1),
("update","v",["更新"],"update software",1),
("upgrade","v",["升級"],"upgrade hardware",1),
("upload","v",["上傳"],"upload a file",1),
("user","n",["使用者"],"end user",1),
("utility","n",["工具程式","公用事業"],"system utility",2),
("validate","v",["驗證"],"validate input",2),
("virtual","adj",["虛擬的"],"virtual reality",1),
("virus","n",["病毒"],"computer virus",1),
("web","n",["網路"],"web development",1),
("widget","n",["小工具"],"desktop widget",2),
("wireless","adj",["無線的"],"wireless network",1),
],
"cat07": [
("abide","v",["遵守","遵循"],"abide by the law",2),
("abolish","v",["廢除","取消"],"abolish a policy",2),
("abstract","n",["摘要"],"legal abstract",2),
("accord","n",["協議","協定"],"peace accord",2),
("acquit","v",["無罪釋放"],"acquit the defendant",3),
("adjudicate","v",["裁決","判決"],"adjudicate a dispute",3),
("adhere","v",["遵守","堅持"],"adhere to rules",2),
("admissible","adj",["可接受的"],"admissible evidence",3),
("advocate","v",["提倡","主張"],"advocate for change",2),
("affidavit","n",["宣誓書"],"sign an affidavit",3),
("affirm","v",["確認","肯定"],"affirm a decision",2),
("allegation","n",["指控","聲稱"],"serious allegation",2),
("allege","v",["指控","聲稱"],"allege wrongdoing",2),
("amend","v",["修正","修改"],"amend a contract",2),
("amendment","n",["修正案","修改"],"contract amendment",2),
("appeal","n",["上訴","申訴"],"file an appeal",2),
("applicable","adj",["適用的"],"applicable laws",1),
("arbitrate","v",["仲裁"],"arbitrate a dispute",3),
("arbitration","n",["仲裁"],"binding arbitration",3),
("attorney","n",["律師"],"hire an attorney",1),
("authorize","v",["授權","批准"],"authorize action",2),
("ban","v",["禁止"],"ban a substance",1),
("binding","adj",["有約束力的"],"binding agreement",2),
("breach","n",["違約","違反"],"breach of contract",2),
("bylaws","n",["章程","細則"],"company bylaws",2),
("case","n",["案件","案例"],"legal case",1),
("claim","n",["索賠","主張"],"file a claim",1),
("clause","n",["條款"],"contract clause",2),
("code","n",["法典","法規"],"building code",1),
("compel","v",["強迫","迫使"],"compel compliance",2),
("compensate","v",["賠償","補償"],"compensate for damages",2),
("compensation","n",["賠償","補償"],"seek compensation",2),
("compliance","n",["合規","遵從"],"ensure compliance",2),
("comply","v",["遵守","符合"],"comply with law",2),
("confiscate","v",["沒收","充公"],"confiscate property",2),
("consent","n",["同意","許可"],"written consent",1),
("constitute","v",["構成"],"constitute a violation",2),
("contract","n",["合約"],"legal contract",1),
("contravene","v",["違反","違背"],"contravene regulations",3),
("convict","v",["定罪"],"convict the accused",2),
("copyright","n",["版權","著作權"],"copyright protection",1),
("counsel","n",["律師","法律顧問"],"legal counsel",2),
("court","n",["法院","法庭"],"court ruling",1),
("covenant","n",["契約","公約"],"loan covenant",3),
("criminal","adj",["刑事的"],"criminal offense",1),
("damages","n",["損害賠償"],"claim damages",2),
("decree","n",["法令","判決"],"court decree",2),
("default","n",["違約"],"loan default",2),
("defendant","n",["被告"],"the defendant",2),
("defense","n",["辯護","防禦"],"legal defense",1),
("defraud","v",["詐欺"],"defraud investors",2),
("deliberation","n",["審議","討論"],"careful deliberation",2),
("depose","v",["作證","廢黜"],"depose a witness",3),
("disclose","v",["披露","揭露"],"disclose information",2),
("disclosure","n",["披露","揭露"],"full disclosure",2),
("dispute","n",["爭議","糾紛"],"legal dispute",1),
("dissolve","v",["解散","解除"],"dissolve a partnership",2),
("draft","v",["草擬"],"draft a contract",1),
("due diligence","n",["盡職調查"],"perform due diligence",2),
("enact","v",["制定","頒布"],"enact legislation",2),
("enforce","v",["執行","實施"],"enforce the law",2),
("enforcement","n",["執行","實施"],"law enforcement",2),
("entitle","v",["使有權利"],"entitled to compensation",1),
("equity","n",["公平","衡平法"],"equity court",2),
("evidence","n",["證據"],"present evidence",1),
("exempt","adj",["免除的"],"exempt from taxes",2),
("exhibit","n",["證物","展品"],"trial exhibit",2),
("file","v",["提出","申請"],"file a lawsuit",1),
("fine","n",["罰款"],"pay a fine",1),
("forfeit","v",["喪失","沒收"],"forfeit rights",2),
("fraud","n",["欺詐","詐騙"],"commit fraud",2),
("grievance","n",["申訴","不滿"],"file a grievance",2),
("guilty","adj",["有罪的"],"found guilty",1),
("hearing","n",["聽證會"],"public hearing",1),
("illegal","adj",["非法的"],"illegal activity",1),
("immunity","n",["豁免權"],"diplomatic immunity",2),
("impose","v",["施加","處以"],"impose a fine",2),
("indict","v",["起訴","控告"],"indict on charges",3),
("infraction","n",["違規"],"minor infraction",2),
("infringe","v",["侵犯","侵權"],"infringe a patent",2),
("injunction","n",["禁令"],"court injunction",3),
("intellectual","adj",["智慧財產的"],"intellectual property",1),
("jurisdiction","n",["管轄權"],"court jurisdiction",2),
("jury","n",["陪審團"],"jury verdict",2),
("justice","n",["正義","司法"],"seek justice",1),
("lawful","adj",["合法的"],"lawful action",1),
("lawsuit","n",["訴訟"],"file a lawsuit",1),
("lawyer","n",["律師"],"corporate lawyer",1),
("legal","adj",["法律的","合法的"],"legal advice",1),
("legislation","n",["立法","法規"],"new legislation",2),
("legitimate","adj",["合法的","正當的"],"legitimate business",2),
("liability","n",["法律責任"],"product liability",2),
("license","n",["執照","許可證"],"business license",1),
("litigate","v",["訴訟","打官司"],"litigate a claim",3),
("litigation","n",["訴訟"],"avoid litigation",2),
("mandate","n",["命令","委任"],"legal mandate",2),
("mediate","v",["調解"],"mediate a dispute",2),
("negligence","n",["疏忽","過失"],"professional negligence",2),
("notarize","v",["公證"],"notarize a document",2),
("obligation","n",["義務","責任"],"contractual obligation",2),
("offense","n",["犯罪","違法"],"criminal offense",1),
("ordinance","n",["法令","條例"],"city ordinance",2),
("patent","n",["專利"],"patent application",2),
("penalty","n",["罰款","處罰"],"pay a penalty",1),
("permit","n",["許可證"],"building permit",1),
("petition","n",["請願書","申請"],"sign a petition",2),
("plaintiff","n",["原告"],"the plaintiff",2),
("plea","n",["抗辯","請求"],"enter a plea",2),
("policy","n",["政策"],"privacy policy",1),
("precedent","n",["先例","判例"],"legal precedent",2),
("proceedings","n",["訴訟程序"],"legal proceedings",2),
("prohibit","v",["禁止"],"prohibit smoking",1),
("prosecution","n",["起訴","控方"],"criminal prosecution",2),
("provision","n",["條款","規定"],"legal provision",2),
("ratify","v",["批准"],"ratify a treaty",3),
("regulation","n",["法規","規定"],"government regulation",1),
("repeal","v",["廢除","撤銷"],"repeal a law",2),
("resolve","v",["解決"],"resolve a dispute",1),
("restrict","v",["限制","約束"],"restrict access",1),
("restriction","n",["限制","約束"],"import restrictions",1),
("right","n",["權利"],"legal right",1),
("ruling","n",["裁決","判決"],"court ruling",2),
("sanction","n",["制裁","處罰"],"economic sanction",2),
("settle","v",["和解","解決"],"settle a case",1),
("settlement","n",["和解","解決"],"reach a settlement",1),
("statute","n",["法規","法令"],"statute of limitations",2),
("stipulate","v",["規定","約定"],"stipulate terms",2),
("sue","v",["起訴","控告"],"sue for damages",1),
("summon","v",["傳喚","召喚"],"summon a witness",2),
("testimony","n",["證詞","證言"],"witness testimony",2),
("trademark","n",["商標"],"protect a trademark",2),
("tribunal","n",["裁判所","法庭"],"trade tribunal",3),
("valid","adj",["有效的","合法的"],"valid contract",1),
("verdict","n",["裁決","判決"],"jury verdict",2),
("verify","v",["驗證","核實"],"verify compliance",1),
("violate","v",["違反"],"violate a law",1),
("violation","n",["違反","違規"],"policy violation",1),
("warrant","n",["搜索令","授權"],"search warrant",2),
("witness","n",["證人"],"call a witness",1),
],
}
