"""Word family expansion - generate related forms for each base word to reach 10000+"""
import random

# Suffix rules: (suffix_to_add, resulting_pos, meaning_suffix_zh)
DERIVATION_RULES = {
    "v": [
        ("-tion", "n", "的行為/過程"),
        ("-ment", "n", "的行為/結果"),
        ("-er", "n", "的人/物"),
        ("-able", "adj", "可...的"),
        ("-ive", "adj", "有...傾向的"),
        ("-ly", "adv", "地"),
    ],
    "n": [
        ("-al", "adj", "...的"),
        ("-ous", "adj", "充滿...的"),
        ("-ful", "adj", "充滿...的"),
        ("-less", "adj", "缺乏...的"),
    ],
    "adj": [
        ("-ly", "adv", "地"),
        ("-ness", "n", "...的狀態"),
        ("-ity", "n", "...的性質"),
    ],
}

# Additional high-frequency TOEIC words organized by category for maximum coverage
WORDS_EXPAND = {
"cat01": [
("abrupt","adj",["突然的","意外的"],"abrupt change",2),
("abstract","adj",["抽象的","摘要的"],"abstract concept",2),
("abundance","n",["豐富","充足"],"in abundance",2),
("abundant","adj",["豐富的","充裕的"],"abundant resources",2),
("accelerate","v",["加速","促進"],"accelerate growth",2),
("acceptable","adj",["可接受的"],"acceptable level",1),
("accessible","adj",["可取得的","可接近的"],"accessible information",1),
("accommodate","v",["適應","容納"],"accommodate changes",1),
("accomplish","v",["完成","實現"],"accomplish objectives",1),
("accountable","adj",["負責的","應解釋的"],"accountable for results",2),
("accumulate","v",["累積","積聚"],"accumulate experience",2),
("acknowledge","v",["承認","確認"],"acknowledge receipt",1),
("acquaint","v",["使熟悉"],"acquaint with procedures",2),
("adamant","adj",["堅定的","固執的"],"adamant about quality",2),
("adapt","v",["適應","改編"],"adapt to changes",1),
("adaptable","adj",["適應性強的"],"adaptable workforce",1),
("adequate","adj",["足夠的","適當的"],"adequate resources",1),
("adhere","v",["遵守","堅持"],"adhere to policy",2),
("adjacent","adj",["相鄰的","毗鄰的"],"adjacent departments",1),
("adjourn","v",["休會","延期"],"adjourn a meeting",2),
("admonish","v",["告誡","訓誡"],"admonish an employee",3),
("adversely","adv",["不利地"],"adversely affect",2),
("advise","v",["建議","忠告"],"advise management",1),
("advisory","adj",["顧問的","諮詢的"],"advisory board",2),
("advocate","v",["提倡","主張"],"advocate for change",2),
("affiliate","n",["附屬機構"],"corporate affiliate",2),
("affirmative","adj",["肯定的"],"affirmative action",2),
("aggregate","v",["合計","匯總"],"aggregate data",2),
("agile","adj",["敏捷的","靈活的"],"agile methodology",2),
("align","v",["對齊","使一致"],"align goals",1),
("alignment","n",["對齊","一致性"],"strategic alignment",2),
("alleviate","v",["減輕","緩和"],"alleviate concerns",2),
("ample","adj",["充足的","豐富的"],"ample time",1),
("anticipate","v",["預期","預料"],"anticipate demand",1),
("apparent","adj",["明顯的","顯然的"],"apparent improvement",1),
("applicable","adj",["適用的","可應用的"],"applicable regulations",1),
("arbitrary","adj",["任意的","武斷的"],"arbitrary decision",2),
("articulate","v",["清楚表達"],"articulate a vision",2),
("aspiration","n",["抱負","志向"],"career aspiration",2),
("assurance","n",["保證","確保"],"quality assurance",1),
("assure","v",["保證","確保"],"assure quality",1),
("attentive","adj",["專注的","留心的"],"attentive to detail",1),
("augment","v",["增加","補充"],"augment the team",2),
("avert","v",["避免","防止"],"avert a crisis",2),
("backlog","n",["積壓","待辦事項"],"order backlog",2),
("bilateral","adj",["雙邊的"],"bilateral agreement",2),
("bolster","v",["支持","加強"],"bolster confidence",2),
("boost","v",["提升","促進"],"boost morale",1),
("bottleneck","n",["瓶頸"],"production bottleneck",2),
("breadth","n",["廣度","寬度"],"breadth of experience",2),
("broad","adj",["廣泛的","寬闊的"],"broad experience",1),
("broaden","v",["擴展","拓寬"],"broaden horizons",1),
("bureaucracy","n",["官僚體系"],"reduce bureaucracy",2),
("bureau","n",["局","處"],"travel bureau",2),
("burnout","n",["倦怠","過勞"],"employee burnout",2),
("byproduct","n",["副產品"],"natural byproduct",2),
("caliber","n",["能力","素質"],"high caliber",2),
("candid","adj",["坦率的","直接的"],"candid feedback",2),
("captivate","v",["吸引","迷住"],"captivate an audience",2),
("catalogue","v",["編目","分類"],"catalogue items",2),
("cease","v",["停止","終止"],"cease operations",2),
("cede","v",["讓渡","割讓"],"cede control",3),
("chronic","adj",["長期的","慢性的"],"chronic issue",2),
("circumscribe","v",["限制","約束"],"circumscribe authority",3),
("cite","v",["引用","引述"],"cite evidence",1),
("civic","adj",["市民的","公民的"],"civic duty",2),
("commemorate","v",["紀念","慶祝"],"commemorate an anniversary",2),
("commend","v",["讚揚","推薦"],"commend an employee",2),
("compact","adj",["緊湊的","簡潔的"],"compact design",1),
("compatible","adj",["相容的","合適的"],"compatible systems",1),
("compel","v",["強迫","迫使"],"compel action",2),
("competency","n",["能力","勝任力"],"core competency",2),
("complement","v",["補充","互補"],"complement skills",2),
("comply","v",["遵守","順從"],"comply with standards",2),
("compulsory","adj",["強制的","義務的"],"compulsory training",2),
("concede","v",["承認","讓步"],"concede a point",2),
("concise","adj",["簡潔的","扼要的"],"concise report",1),
("concurrent","adj",["同時的","並行的"],"concurrent projects",2),
("condense","v",["濃縮","精簡"],"condense information",2),
("confine","v",["限制","侷限"],"confine to a role",2),
("confront","v",["面對","對抗"],"confront challenges",1),
("congruent","adj",["一致的","相符的"],"congruent goals",3),
("conscientious","adj",["盡責的","認真的"],"conscientious worker",2),
("conservation","n",["保護","節約"],"resource conservation",2),
("conservative","adj",["保守的","謹慎的"],"conservative estimate",1),
("constrain","v",["限制","約束"],"constrain spending",2),
("contingency","n",["應急措施","偶發事件"],"contingency plan",2),
("contingent","adj",["取決於的","有條件的"],"contingent upon approval",2),
("converge","v",["匯聚","趨同"],"converge on a solution",2),
("convert","v",["轉換","改變"],"convert resources",1),
("convey","v",["傳達","表達"],"convey a message",1),
("correlate","v",["相關聯","關連"],"correlate with performance",2),
("cortex","n",["核心","腦皮層"],"organizational cortex",3),
("counsel","v",["建議","輔導"],"counsel employees",2),
("courteous","adj",["有禮貌的","客氣的"],"courteous service",1),
("covert","adj",["秘密的","隱蔽的"],"covert operation",3),
("culminate","v",["達到頂點"],"culminate in success",2),
("cumulative","adj",["累積的","累計的"],"cumulative effect",2),
("curtail","v",["削減","縮減"],"curtail expenses",2),
("customary","adj",["慣例的","習慣的"],"customary practice",2),
("daunting","adj",["令人畏懼的"],"daunting task",2),
("deem","v",["認為","視為"],"deem necessary",2),
("defer","v",["推遲","延期"],"defer a decision",2),
("deficiency","n",["缺乏","不足"],"resource deficiency",2),
("definitive","adj",["明確的","最終的"],"definitive answer",2),
("delineate","v",["描述","勾勒"],"delineate responsibilities",2),
("delve","v",["深入研究"],"delve into details",2),
("deplete","v",["耗盡","消耗"],"deplete resources",2),
("deploy","v",["部署","調度"],"deploy resources",2),
("designate","v",["指定","指派"],"designate a successor",2),
("desirable","adj",["理想的","合意的"],"desirable outcome",1),
("detrimental","adj",["有害的","不利的"],"detrimental effect",2),
("devise","v",["設計","想出"],"devise a solution",2),
("diminish","v",["減少","縮小"],"diminish impact",2),
("discard","v",["丟棄","放棄"],"discard old methods",1),
("discern","v",["辨別","識別"],"discern trends",2),
("disclose","v",["揭露","透露"],"disclose information",2),
("discord","n",["不和","分歧"],"workplace discord",2),
("discrepancy","n",["差異","不一致"],"report discrepancy",2),
("discretionary","adj",["自由裁量的"],"discretionary spending",2),
("disperse","v",["分散","散布"],"disperse information",2),
("disrupt","v",["擾亂","中斷"],"disrupt the market",1),
("disruption","n",["中斷","顛覆"],"digital disruption",1),
("disseminate","v",["傳播","散布"],"disseminate knowledge",2),
("distinct","adj",["明顯的","獨特的"],"distinct advantage",1),
("distinguish","v",["區分","辨別"],"distinguish features",2),
("diverge","v",["分歧","偏離"],"diverge from the plan",2),
("downfall","n",["衰敗","垮台"],"lead to downfall",2),
("downturn","n",["經濟衰退","下滑"],"economic downturn",2),
("drawback","n",["缺點","不利之處"],"potential drawback",1),
("drastically","adv",["大幅地","劇烈地"],"drastically reduce",2),
("duplicate","v",["複製","重複"],"duplicate efforts",1),
("durability","n",["耐用性","持久性"],"product durability",2),
("dwindle","v",["減少","衰退"],"dwindle in size",2),
("edify","v",["啟發","教育"],"edify colleagues",3),
("efficacy","n",["功效","效能"],"program efficacy",2),
("eloquent","adj",["雄辯的","有說服力的"],"eloquent speaker",2),
("elusive","adj",["難以捉摸的"],"elusive goal",2),
("embark","v",["著手","開始"],"embark on a project",2),
("embed","v",["嵌入","植入"],"embed values",2),
("embrace","v",["擁抱","接受"],"embrace change",1),
("enact","v",["制定","頒布"],"enact policies",2),
("encompass","v",["包含","涵蓋"],"encompass all areas",2),
("endure","v",["忍受","持續"],"endure challenges",2),
("engender","v",["產生","引起"],"engender trust",3),
("enormous","adj",["巨大的","龐大的"],"enormous potential",1),
("ensue","v",["接著發生"],"problems ensue",2),
("entail","v",["需要","牽涉"],"entail responsibility",2),
("envision","v",["設想","展望"],"envision the future",2),
("erratic","adj",["不穩定的","反覆無常的"],"erratic performance",2),
("escalate","v",["升級","加劇"],"escalate a dispute",2),
("espouse","v",["支持","倡導"],"espouse a cause",3),
("essential","adj",["必要的","基本的"],"essential skill",1),
("ethical","adj",["道德的","倫理的"],"ethical behavior",1),
("evade","v",["逃避","迴避"],"evade responsibility",2),
("evident","adj",["明顯的","顯然的"],"evident improvement",1),
("evolve","v",["發展","演變"],"evolve strategies",2),
("exacerbate","v",["加劇","惡化"],"exacerbate problems",3),
("exaggerate","v",["誇大","誇張"],"exaggerate results",1),
("excessively","adv",["過度地"],"excessively cautious",2),
("exemplary","adj",["模範的","卓越的"],"exemplary performance",2),
("exemplify","v",["舉例說明","體現"],"exemplify best practices",2),
("exert","v",["施加","運用"],"exert influence",2),
("exhaustive","adj",["詳盡的","全面的"],"exhaustive review",2),
("expedient","adj",["權宜的","有利的"],"expedient solution",3),
("explicit","adj",["明確的","明白的"],"explicit instructions",2),
("exponentially","adv",["指數地","急速地"],"grow exponentially",2),
("extensively","adv",["廣泛地","大量地"],"extensively researched",2),
("extract","v",["提取","萃取"],"extract value",2),
("extraneous","adj",["無關的","外來的"],"extraneous information",3),
("fabricate","v",["捏造","製造"],"fabricate data",2),
("facet","n",["方面","層面"],"every facet",2),
("feasibility","n",["可行性"],"feasibility study",2),
("finalize","v",["完成","定案"],"finalize details",1),
("foresee","v",["預見","預知"],"foresee problems",2),
("forfeit","v",["喪失","沒收"],"forfeit rights",2),
("forthcoming","adj",["即將來臨的"],"forthcoming event",2),
("fragile","adj",["脆弱的","易碎的"],"fragile situation",1),
("frugal","adj",["節儉的","節約的"],"frugal approach",2),
("galvanize","v",["激勵","激發"],"galvanize the team",2),
("garner","v",["獲得","收集"],"garner support",2),
("gauge","v",["評估","衡量"],"gauge interest",2),
("generic","adj",["一般的","通用的"],"generic solution",1),
("grasp","v",["理解","抓住"],"grasp the concept",1),
("groundbreaking","adj",["開創性的"],"groundbreaking technology",2),
("hamper","v",["妨礙","阻礙"],"hamper progress",2),
("harness","v",["利用","駕馭"],"harness technology",2),
("hasten","v",["加速","催促"],"hasten development",2),
("heighten","v",["提高","加強"],"heighten awareness",2),
("hinder","v",["阻礙","妨礙"],"hinder progress",2),
("holistic","adj",["全面的","整體的"],"holistic approach",2),
("imminent","adj",["即將到來的","迫在眉睫的"],"imminent deadline",2),
("impair","v",["損害","削弱"],"impair judgment",2),
("impartial","adj",["公正的","不偏不倚的"],"impartial review",2),
("imperative","adj",["必要的","緊急的"],"imperative action",2),
("implicit","adj",["隱含的","暗示的"],"implicit agreement",2),
("impetus","n",["推動力","動力"],"provide impetus",2),
("impromptu","adj",["即興的","臨時的"],"impromptu meeting",2),
("inadvertently","adv",["無意地","不經意地"],"inadvertently omit",2),
("inaugural","adj",["就職的","首次的"],"inaugural speech",2),
("incline","v",["傾向","傾斜"],"incline toward",2),
("inclusive","adj",["包容的","包括的"],"inclusive policy",1),
("inconsistency","n",["不一致","矛盾"],"policy inconsistency",2),
("increment","n",["增量","增加"],"salary increment",2),
("incremental","adj",["漸進的","遞增的"],"incremental change",2),
("indispensable","adj",["不可或缺的"],"indispensable member",2),
("infer","v",["推斷","推論"],"infer from data",2),
("influential","adj",["有影響力的"],"influential leader",1),
("inherent","adj",["固有的","內在的"],"inherent risk",2),
("inhibit","v",["抑制","禁止"],"inhibit growth",2),
("innate","adj",["天生的","固有的"],"innate ability",2),
("insightful","adj",["有洞察力的"],"insightful analysis",2),
("instrumental","adj",["有助於的","重要的"],"instrumental in success",2),
("intangible","adj",["無形的"],"intangible asset",2),
("integral","adj",["不可或缺的"],"integral component",2),
("intensify","v",["加強","強化"],"intensify efforts",2),
("interchangeable","adj",["可互換的"],"interchangeable parts",2),
("interim","n",["暫時","過渡期"],"in the interim",2),
("intermittent","adj",["間歇的","斷斷續續的"],"intermittent service",2),
("intricate","adj",["複雜的","精細的"],"intricate process",2),
("intrinsic","adj",["固有的","本質的"],"intrinsic value",2),
("invaluable","adj",["無價的","極寶貴的"],"invaluable experience",1),
("invoke","v",["引用","援引"],"invoke a clause",2),
("irrevocable","adj",["不可撤銷的"],"irrevocable decision",3),
("iterate","v",["重複","迭代"],"iterate on feedback",2),
("jeopardize","v",["危害","危及"],"jeopardize success",2),
("judicious","adj",["明智的","審慎的"],"judicious decision",2),
("keen","adj",["熱切的","敏銳的"],"keen interest",1),
("knowledgeable","adj",["知識淵博的"],"knowledgeable staff",1),
("lag","v",["落後","滯後"],"lag behind",1),
("lapse","n",["失效","失誤"],"policy lapse",2),
("latent","adj",["潛在的","隱伏的"],"latent potential",2),
("liaise","v",["聯繫","協調"],"liaise with clients",2),
("liable","adj",["有責任的","易於...的"],"liable for damages",2),
("magnify","v",["放大","加劇"],"magnify impact",2),
("manifest","v",["表明","展現"],"manifest improvement",2),
("meager","adj",["微薄的","不足的"],"meager resources",2),
("mediation","n",["調解","斡旋"],"seek mediation",2),
("merit","n",["優點","功績"],"based on merit",1),
("meticulous","adj",["一絲不苟的"],"meticulous attention",2),
("mitigate","v",["減輕","緩和"],"mitigate risk",2),
("modest","adj",["適度的","謙虛的"],"modest growth",1),
("momentum","n",["動力","勢頭"],"build momentum",2),
("monetary","adj",["金錢的","貨幣的"],"monetary value",2),
("monopolize","v",["壟斷","獨佔"],"monopolize the market",2),
("negate","v",["否定","取消"],"negate the effect",2),
("negligible","adj",["可忽略的","微不足道的"],"negligible impact",2),
("nominal","adj",["名義上的","象徵性的"],"nominal fee",2),
("notwithstanding","adv",["儘管","雖然"],"notwithstanding challenges",3),
("nuance","n",["細微差異"],"cultural nuance",2),
("nurture","v",["培養","培育"],"nurture talent",2),
("obligatory","adj",["義務的","強制的"],"obligatory report",2),
("obscure","adj",["模糊的","不清楚的"],"obscure rule",2),
("obsolescence","n",["過時","淘汰"],"planned obsolescence",2),
("obstruct","v",["阻礙","妨礙"],"obstruct progress",2),
("offset","v",["抵消","補償"],"offset costs",2),
("omit","v",["省略","遺漏"],"omit details",1),
("onset","n",["開始","發生"],"onset of problems",2),
("opt","v",["選擇","決定"],"opt for",1),
("optimal","adj",["最佳的","理想的"],"optimal solution",2),
("orchestrate","v",["策劃","安排"],"orchestrate changes",2),
("outperform","v",["超越","表現更好"],"outperform competitors",2),
("outreach","n",["外展","推廣"],"community outreach",2),
("overt","adj",["公開的","明顯的"],"overt action",2),
("overture","n",["提議","序曲"],"business overture",3),
("overwhelm","v",["壓倒","使不知所措"],"overwhelm with tasks",1),
("paradigm","n",["典範","範式"],"paradigm shift",2),
("parallel","adj",["平行的","相似的"],"parallel projects",1),
("paramount","adj",["最重要的","至上的"],"paramount importance",2),
("parity","n",["平等","對等"],"pay parity",2),
("partial","adj",["部分的","偏向的"],"partial agreement",1),
("peculiar","adj",["特殊的","獨特的"],"peculiar situation",2),
("penetrate","v",["滲透","深入"],"penetrate the market",2),
("permeate","v",["滲透","瀰漫"],"permeate the organization",2),
("perpetual","adj",["永久的","不斷的"],"perpetual growth",2),
("pertain","v",["有關","屬於"],"pertain to the issue",2),
("pertinent","adj",["相關的","切題的"],"pertinent information",2),
("plausible","adj",["合理的","可信的"],"plausible explanation",2),
("plight","n",["困境","苦境"],"financial plight",2),
("plunge","v",["暴跌","急降"],"plunge in value",2),
("pragmatic","adj",["務實的","實際的"],"pragmatic approach",2),
("precautionary","adj",["預防的","預防性的"],"precautionary measure",2),
("precipitate","v",["促成","導致"],"precipitate a crisis",3),
("predominant","adj",["主要的","佔優勢的"],"predominant factor",2),
("preemptive","adj",["先發制人的"],"preemptive action",2),
("premise","n",["前提","假設"],"basic premise",2),
("prevalent","adj",["流行的","普遍的"],"prevalent trend",2),
("proactive","adj",["積極主動的"],"proactive approach",1),
("probe","v",["探究","調查"],"probe into",2),
("procure","v",["採購","獲得"],"procure materials",2),
("procurement","n",["採購","取得"],"procurement process",2),
("profound","adj",["深遠的","深刻的"],"profound impact",2),
("prohibitive","adj",["高得令人卻步的"],"prohibitive cost",2),
("proliferate","v",["激增","擴散"],"proliferate rapidly",2),
("prominent","adj",["傑出的","顯著的"],"prominent figure",1),
("propel","v",["推動","驅動"],"propel growth",2),
("proportional","adj",["成比例的"],"proportional increase",2),
("proprietary","adj",["專有的","專利的"],"proprietary software",2),
("prudent","adj",["謹慎的","明智的"],"prudent decision",2),
("punitive","adj",["懲罰性的"],"punitive measure",3),
("quantify","v",["量化"],"quantify results",2),
("rationale","n",["理由","根據"],"provide rationale",2),
("realm","n",["領域","範疇"],"business realm",2),
("reap","v",["收穫","獲得"],"reap benefits",2),
("recede","v",["退去","減退"],"recede in importance",2),
("reconcile","v",["調和","使一致"],"reconcile differences",2),
("redundant","adj",["多餘的","冗餘的"],"redundant processes",2),
("refrain","v",["克制","避免"],"refrain from commenting",2),
("reimagine","v",["重新構想"],"reimagine the workplace",2),
("reiterate","v",["重申","反覆說"],"reiterate the point",2),
("relentless","adj",["不懈的","堅持不解的"],"relentless pursuit",2),
("relinquish","v",["放棄","讓出"],"relinquish control",2),
("reluctance","n",["不情願","勉強"],"show reluctance",2),
("remarkable","adj",["顯著的","非凡的"],"remarkable growth",1),
("replicate","v",["複製","重現"],"replicate success",2),
("replenish","v",["補充","重新裝滿"],"replenish supplies",2),
("reprimand","v",["訓斥","譴責"],"reprimand an employee",2),
("repute","n",["名聲","聲譽"],"good repute",2),
("resilience","n",["韌性","恢復力"],"organizational resilience",2),
("resilient","adj",["有韌性的","堅韌的"],"resilient team",2),
("respective","adj",["各自的","分別的"],"respective roles",1),
("responsive","adj",["回應迅速的"],"responsive service",1),
("restraint","n",["克制","限制"],"exercise restraint",2),
("revelation","n",["揭示","發現"],"surprising revelation",2),
("rigorous","adj",["嚴格的","嚴密的"],"rigorous analysis",2),
("robust","adj",["強健的","堅固的"],"robust system",2),
("safeguard","v",["保護","捍衛"],"safeguard interests",2),
("saturate","v",["飽和","充滿"],"saturate the market",2),
("scarcity","n",["稀缺","短缺"],"resource scarcity",2),
("scrupulous","adj",["一絲不苟的"],"scrupulous attention",2),
("scrutiny","n",["審查","細查"],"under scrutiny",2),
("seize","v",["抓住","奪取"],"seize an opportunity",1),
("setback","n",["挫折","阻礙"],"temporary setback",1),
("sever","v",["切斷","斷絕"],"sever ties",2),
("shortcoming","n",["缺點","不足"],"address shortcomings",2),
("shrewd","adj",["精明的","敏銳的"],"shrewd businessman",2),
("simultaneous","adj",["同時的"],"simultaneous events",2),
("skeptical","adj",["懷疑的"],"skeptical investor",2),
("solvent","adj",["有償付能力的"],"remain solvent",2),
("span","v",["跨越","涵蓋"],"span several years",1),
("sparse","adj",["稀少的","稀疏的"],"sparse resources",2),
("speculate","v",["推測","投機"],"speculate on outcomes",2),
("spur","v",["激勵","促進"],"spur innovation",2),
("stagnant","adj",["停滯的","不景氣的"],"stagnant growth",2),
("stagnate","v",["停滯","滯銷"],"stagnate in growth",2),
("stark","adj",["明顯的","嚴酷的"],"stark contrast",2),
("steadfast","adj",["堅定的","不動搖的"],"steadfast commitment",2),
("steep","adj",["陡峭的","急劇的"],"steep decline",1),
("stimulate","v",["刺激","激勵"],"stimulate growth",2),
("stipulation","n",["規定","條件"],"contract stipulation",2),
("subordinate","adj",["次要的","下級的"],"subordinate role",2),
("substantial","adj",["大量的","實質的"],"substantial investment",1),
("subtract","v",["減去","扣除"],"subtract costs",1),
("successive","adj",["連續的","接連的"],"successive quarters",2),
("succinct","adj",["簡潔的","簡明的"],"succinct summary",2),
("surmount","v",["克服","超越"],"surmount obstacles",2),
("surplus","adj",["過剩的","多餘的"],"surplus inventory",2),
("susceptible","adj",["易受影響的"],"susceptible to change",2),
("synergy","n",["協同效應"],"create synergy",2),
("tangible","adj",["具體的","有形的"],"tangible results",1),
("tenacious","adj",["堅持不懈的"],"tenacious effort",2),
("tentative","adj",["暫定的","試探性的"],"tentative agreement",2),
("thereafter","adv",["此後","之後"],"shortly thereafter",2),
("thereby","adv",["由此","從而"],"thereby reducing costs",2),
("thorough","adj",["徹底的","詳盡的"],"thorough investigation",1),
("timely","adj",["及時的","適時的"],"timely response",1),
("tolerance","n",["容忍","寬容"],"zero tolerance",1),
("trajectory","n",["軌道","發展軌跡"],"growth trajectory",2),
("transact","v",["交易","辦理"],"transact business",2),
("transcend","v",["超越","超出"],"transcend boundaries",2),
("traverse","v",["穿越","橫跨"],"traverse departments",2),
("tremendous","adj",["極大的","驚人的"],"tremendous growth",1),
("trivial","adj",["微不足道的","瑣碎的"],"trivial matter",1),
("truncate","v",["截斷","縮短"],"truncate a report",2),
("tumultuous","adj",["動盪的","混亂的"],"tumultuous period",2),
("turnaround","n",["轉機","周轉時間"],"quick turnaround",1),
("ubiquitous","adj",["無所不在的"],"ubiquitous technology",2),
("ultimate","adj",["最終的","終極的"],"ultimate goal",1),
("unanimously","adv",["一致地"],"unanimously approved",2),
("unbiased","adj",["公正的","無偏見的"],"unbiased opinion",2),
("undergo","v",["經歷","接受"],"undergo review",2),
("undermine","v",["破壞","削弱"],"undermine confidence",2),
("underscore","v",["強調","突顯"],"underscore the importance",2),
("undertaking","n",["事業","任務"],"major undertaking",2),
("unprecedented","adj",["前所未有的"],"unprecedented growth",1),
("unwarranted","adj",["不正當的","無根據的"],"unwarranted criticism",2),
("upscale","adj",["高檔的","高級的"],"upscale market",1),
("upturn","n",["好轉","上升"],"economic upturn",2),
("urge","v",["敦促","催促"],"urge caution",1),
("usurp","v",["篡奪","侵佔"],"usurp authority",3),
("vague","adj",["模糊的","含糊的"],"vague response",1),
("vast","adj",["廣大的","大量的"],"vast experience",1),
("versatile","adj",["多才多藝的","通用的"],"versatile employee",1),
("vigilant","adj",["警覺的","警惕的"],"remain vigilant",2),
("vindicate","v",["證明正確","辯護"],"vindicate a decision",3),
("volatile","adj",["不穩定的","波動的"],"volatile market",2),
("waive","v",["放棄","免除"],"waive a fee",2),
("willingness","n",["意願","樂意"],"willingness to learn",1),
("wield","v",["行使","運用"],"wield influence",2),
("withstand","v",["承受","經得起"],"withstand pressure",2),
("zeal","n",["熱情","熱忱"],"show zeal",2),
("zealous","adj",["熱心的","熱情的"],"zealous advocate",2),
],
}
