"""Programmatic word family generator - creates derived forms from base words"""

# Rules: (ending_to_remove, ending_to_add, new_pos, meaning_prefix_zh)
DERIVATION_MAP = [
    # Verb -> Noun
    ("e", "ation", "v", "n", "...的行為"),
    ("", "tion", "v", "n", "...的行為"),
    ("", "ment", "v", "n", "...的結果"),
    ("e", "or", "v", "n", "...的人"),
    ("", "er", "v", "n", "...的人"),
    ("e", "ance", "v", "n", "...的狀態"),
    ("", "ance", "v", "n", "...的狀態"),
    # Verb -> Adj
    ("e", "able", "v", "adj", "可...的"),
    ("", "able", "v", "adj", "可...的"),
    ("e", "ive", "v", "adj", "...的"),
    ("", "ive", "v", "adj", "...的"),
    # Noun -> Adj
    ("y", "ical", "n", "adj", "...的"),
    ("", "al", "n", "adj", "...的"),
    ("", "ous", "n", "adj", "充滿...的"),
    ("", "ful", "n", "adj", "充滿...的"),
    ("", "less", "n", "adj", "缺少...的"),
    # Adj -> Adv
    ("", "ly", "adj", "adv", "...地"),
    # Adj -> Noun
    ("t", "ce", "adj", "n", "...的狀態"),
    ("", "ness", "adj", "n", "...的特質"),
    ("le", "ility", "adj", "n", "...的特質"),
]

# Common English word families that are high-frequency in TOEIC
# Each entry: (base_word, derivatives_list)
# derivatives: (derived_word, pos, [meanings_zh], collocation, difficulty)
WORD_FAMILIES = {
"cat01": [
# From existing base words, generate related forms
("accountant","n",["會計師"],"certified accountant",1),
("accountability","n",["責任制","問責"],"ensure accountability",2),
("accurately","adv",["準確地"],"accurately predict",1),
("accuracy","n",["準確度"],"data accuracy",1),
("achievable","adj",["可達成的"],"achievable goal",1),
("achiever","n",["成就者"],"high achiever",1),
("actively","adv",["積極地"],"actively participate",1),
("adaptability","n",["適應力"],"demonstrate adaptability",2),
("adaptation","n",["適應","改編"],"market adaptation",2),
("additionally","adv",["此外","額外地"],"additionally required",1),
("adequately","adv",["充分地"],"adequately staffed",1),
("adherence","n",["遵守","堅持"],"strict adherence",2),
("adjustment","n",["調整"],"salary adjustment",1),
("admirable","adj",["令人欽佩的"],"admirable leadership",1),
("advisable","adj",["明智的"],"advisable approach",1),
("advisor","n",["顧問"],"financial advisor",1),
("affiliation","n",["隸屬","聯繫"],"corporate affiliation",2),
("aggressively","adv",["積極地"],"aggressively pursue",2),
("allowable","adj",["許可的"],"allowable expense",1),
("alternatively","adv",["或者","另外"],"alternatively proposed",1),
("ambitiously","adv",["雄心勃勃地"],"ambitiously planned",2),
("applicability","n",["適用性"],"policy applicability",2),
("applicant","n",["申請人"],"job applicant",1),
("appropriately","adv",["適當地"],"appropriately handled",1),
("assertive","adj",["自信的","堅定的"],"assertive leader",2),
("assertiveness","n",["自信","堅定"],"show assertiveness",2),
("assessor","n",["評估員"],"risk assessor",2),
("attainment","n",["達成","成就"],"goal attainment",2),
("attendee","n",["出席者","與會者"],"conference attendee",1),
("attribute","n",["屬性","特質"],"key attribute",1),
("auditor","n",["審計員","稽核員"],"internal auditor",2),
("authorization","n",["授權"],"written authorization",2),
("availability","n",["可用性"],"resource availability",1),
("benchmark","v",["以...為標竿"],"benchmark against peers",2),
("beneficial","adj",["有益的"],"mutually beneficial",1),
("broadly","adv",["廣泛地"],"broadly applicable",1),
("calculable","adj",["可計算的"],"calculable risk",2),
("cautious","adj",["謹慎的"],"cautious approach",1),
("cautiously","adv",["謹慎地"],"cautiously optimistic",1),
("centralization","n",["集中化"],"organizational centralization",2),
("challenging","adj",["具有挑戰性的"],"challenging environment",1),
("characterize","v",["以...為特徵"],"characterize the market",2),
("chronological","adj",["按時間順序的"],"chronological order",1),
("clarification","n",["澄清"],"seek clarification",1),
("collectively","adv",["共同地"],"collectively decide",1),
("commencement","n",["開始"],"project commencement",2),
("commercially","adv",["商業上"],"commercially viable",2),
("communicative","adj",["善於溝通的"],"communicative skills",1),
("comparatively","adv",["相對地"],"comparatively better",1),
("compensatory","adj",["補償的"],"compensatory damages",2),
("competitiveness","n",["競爭力"],"market competitiveness",1),
("completion","n",["完成"],"project completion",1),
("complexity","n",["複雜性"],"reduce complexity",1),
("comprehensively","adv",["全面地"],"comprehensively reviewed",2),
("conceivable","adj",["可想像的"],"conceivable outcome",2),
("conclusive","adj",["決定性的"],"conclusive evidence",2),
("conclusively","adv",["決定性地"],"conclusively proven",2),
("conditional","adj",["有條件的"],"conditional approval",1),
("conditionally","adv",["有條件地"],"conditionally approved",2),
("confidentially","adv",["機密地"],"handle confidentially",2),
("considerably","adv",["相當大地"],"considerably improved",1),
("consistently","adv",["一貫地"],"consistently perform",1),
("constructive","adj",["建設性的"],"constructive feedback",1),
("constructively","adv",["建設性地"],"constructively criticize",2),
("consultancy","n",["顧問公司"],"management consultancy",2),
("contender","n",["競爭者"],"strong contender",1),
("contingent","adj",["視情況而定的"],"contingent upon",2),
("contractor","n",["承包商"],"independent contractor",1),
("controllable","adj",["可控制的"],"controllable costs",1),
("controller","n",["控制者","財務長"],"financial controller",2),
("conventionally","adv",["傳統地"],"conventionally managed",2),
("convincing","adj",["有說服力的"],"convincing argument",1),
("convincingly","adv",["有說服力地"],"convincingly argued",2),
("coordinator","n",["協調者"],"project coordinator",1),
("corrective","adj",["糾正的"],"corrective action",2),
("correspondingly","adv",["相應地"],"correspondingly adjusted",2),
("creator","n",["創造者"],"content creator",1),
("crucially","adv",["關鍵地"],"crucially important",2),
("customizable","adj",["可自定義的"],"customizable options",1),
("decisively","adv",["果斷地"],"act decisively",2),
("dedicated","adj",["專注的","敬業的"],"dedicated employee",1),
("dedication","n",["奉獻","專注"],"show dedication",1),
("deficiency","n",["不足","缺陷"],"address deficiency",2),
("deliberately","adv",["故意地"],"deliberately planned",2),
("deliverable","n",["交付物"],"project deliverable",2),
("demonstrably","adv",["可證明地"],"demonstrably effective",2),
("dependable","adj",["可靠的"],"dependable worker",1),
("dependably","adv",["可靠地"],"dependably perform",2),
("descriptive","adj",["描述性的"],"descriptive report",1),
("designator","n",["指定者"],"official designator",2),
("determination","n",["決心"],"strong determination",1),
("developmental","adj",["發展的"],"developmental stage",1),
("devotion","n",["奉獻","忠誠"],"employee devotion",1),
("diligently","adv",["勤奮地"],"work diligently",1),
("directional","adj",["方向性的"],"directional change",2),
("directive","n",["指令","指示"],"government directive",2),
("disapproval","n",["不贊成"],"express disapproval",1),
("disclosure","n",["披露","揭露"],"full disclosure",2),
("diversification","n",["多元化"],"market diversification",2),
("documentation","n",["文件資料"],"proper documentation",1),
("dominance","n",["主導地位"],"market dominance",2),
("dramatically","adv",["戲劇性地"],"dramatically improve",1),
("duration","n",["持續時間"],"project duration",1),
("dutifully","adv",["盡職地"],"dutifully complete",2),
("dynamics","n",["動態","動力學"],"team dynamics",1),
("eagerly","adv",["熱切地"],"eagerly anticipated",1),
("economical","adj",["經濟的","節省的"],"economical solution",1),
("economically","adv",["經濟地","節省地"],"economically viable",1),
("effectively","adv",["有效地"],"effectively managed",1),
("efficiently","adv",["高效地"],"efficiently operate",1),
("elaboration","n",["詳細說明"],"need elaboration",2),
("elimination","n",["消除"],"cost elimination",1),
("emergence","n",["出現","浮現"],"market emergence",2),
("emotionally","adv",["情感上"],"emotionally invested",1),
("empowerment","n",["授權","賦能"],"employee empowerment",2),
("encouragement","n",["鼓勵"],"provide encouragement",1),
("enhancement","n",["增強","改善"],"performance enhancement",2),
("enthusiastically","adv",["熱情地"],"enthusiastically support",1),
("entirely","adv",["完全地"],"entirely responsible",1),
("equitable","adj",["公平的"],"equitable treatment",2),
("equitably","adv",["公平地"],"equitably distributed",2),
("essentially","adv",["本質上"],"essentially complete",1),
("estimation","n",["估計","評價"],"cost estimation",1),
("evaluator","n",["評估者"],"external evaluator",2),
("evidently","adv",["顯然地"],"evidently improved",1),
("exceptionally","adv",["非常地"],"exceptionally well",1),
("exclusively","adv",["專門地"],"exclusively available",1),
("exhaustively","adv",["詳盡地"],"exhaustively reviewed",2),
("expectation","n",["期望"],"exceed expectations",1),
("experimental","adj",["實驗的"],"experimental approach",1),
("experimentally","adv",["實驗性地"],"experimentally tested",2),
("explanatory","adj",["解釋的"],"explanatory note",1),
("exploration","n",["探索"],"market exploration",1),
("extensively","adv",["廣泛地"],"extensively reviewed",2),
("facilitator","n",["促進者","引導者"],"meeting facilitator",2),
("favorable","adj",["有利的"],"favorable outcome",1),
("favorably","adv",["有利地"],"favorably received",1),
("flexibility","n",["靈活性"],"workplace flexibility",1),
("flexible","adj",["靈活的"],"flexible schedule",1),
("formally","adv",["正式地"],"formally announced",1),
("formulation","n",["制定","配方"],"policy formulation",2),
("fortuitous","adj",["偶然的","幸運的"],"fortuitous event",2),
("foundational","adj",["基礎的"],"foundational knowledge",1),
("fundamentally","adv",["根本地"],"fundamentally changed",1),
("generative","adj",["生成的"],"generative approach",2),
("genuinely","adv",["真誠地"],"genuinely interested",1),
("globally","adv",["全球地"],"globally recognized",1),
("impartially","adv",["公正地"],"impartially evaluate",2),
("implementation","n",["實施"],"strategy implementation",1),
("importantly","adv",["重要地"],"more importantly",1),
("impressively","adv",["令人印象深刻地"],"impressively delivered",1),
("improvement","n",["改善","進步"],"continuous improvement",1),
("inadequate","adj",["不充分的"],"inadequate resources",1),
("inadvertently","adv",["無意地"],"inadvertently caused",2),
("increasingly","adv",["越來越"],"increasingly important",1),
("independently","adv",["獨立地"],"independently operated",1),
("indicator","n",["指標"],"performance indicator",1),
("individually","adv",["個別地"],"individually assessed",1),
("ineffective","adj",["無效的"],"ineffective method",1),
("inefficiency","n",["低效率"],"eliminate inefficiency",1),
("inevitably","adv",["不可避免地"],"inevitably occur",1),
("influential","adj",["有影響力的"],"influential figure",1),
("informative","adj",["提供資訊的"],"informative report",1),
("inherently","adv",["本質上"],"inherently risky",2),
("innovation","n",["創新"],"product innovation",1),
("inspector","n",["檢查員"],"quality inspector",1),
("institution","n",["機構"],"financial institution",1),
("institutional","adj",["機構的"],"institutional investor",2),
("instructor","n",["講師","指導者"],"training instructor",1),
("insufficient","adj",["不足的"],"insufficient data",1),
("intentional","adj",["故意的"],"intentional effort",1),
("intentionally","adv",["故意地"],"intentionally designed",2),
("interconnected","adj",["相互連接的"],"interconnected systems",2),
("internally","adv",["內部地"],"internally managed",1),
("internationally","adv",["國際地"],"internationally recognized",1),
("interpretation","n",["解釋","口譯"],"data interpretation",2),
("intervention","n",["干預","介入"],"government intervention",2),
("investigator","n",["調查員"],"lead investigator",2),
("involvement","n",["參與","涉入"],"stakeholder involvement",1),
("justifiable","adj",["正當的"],"justifiable expense",2),
("justification","n",["正當理由"],"provide justification",2),
("knowledgeably","adv",["知識淵博地"],"knowledgeably advise",2),
("leadership","n",["領導力"],"leadership skills",1),
("legitimacy","n",["合法性"],"organizational legitimacy",2),
("legitimately","adv",["合法地"],"legitimately earned",2),
("logistically","adv",["在物流上"],"logistically complex",2),
("managerial","adj",["管理的"],"managerial skills",1),
("manageable","adj",["可管理的"],"manageable workload",1),
("mandatorily","adv",["強制性地"],"mandatorily required",2),
("marginally","adv",["略微地"],"marginally profitable",2),
("markedly","adv",["顯著地"],"markedly improved",2),
("meaningfully","adv",["有意義地"],"meaningfully contribute",2),
("measurable","adj",["可衡量的"],"measurable results",1),
("memorandum","n",["備忘錄"],"issue a memorandum",2),
("methodical","adj",["有系統的"],"methodical approach",2),
("methodically","adv",["有系統地"],"methodically organized",2),
("modification","n",["修改","變更"],"contract modification",1),
("motivated","adj",["有動力的"],"highly motivated",1),
("narrowly","adv",["勉強地","狹義地"],"narrowly defined",1),
("negotiable","adj",["可談判的"],"negotiable terms",1),
("negotiator","n",["談判者"],"skilled negotiator",1),
("nomination","n",["提名"],"board nomination",2),
("notably","adv",["值得注意地"],"most notably",1),
("notification","n",["通知"],"receive notification",1),
("objectively","adv",["客觀地"],"objectively assessed",1),
("observance","n",["遵守","慶祝"],"policy observance",2),
("observer","n",["觀察者"],"industry observer",1),
("operational","adj",["營運的"],"operational efficiency",1),
("operationally","adv",["在營運上"],"operationally sound",2),
("optimistic","adj",["樂觀的"],"cautiously optimistic",1),
("optimistically","adv",["樂觀地"],"optimistically forecast",2),
("organizationally","adv",["在組織上"],"organizationally aligned",2),
("originally","adv",["原本地"],"originally planned",1),
("outperformance","n",["超越表現"],"market outperformance",2),
("overdue","adj",["過期的","遲到的"],"overdue payment",1),
("overwhelmingly","adv",["壓倒性地"],"overwhelmingly supported",2),
("participatory","adj",["參與式的"],"participatory approach",2),
("permanently","adv",["永久地"],"permanently assigned",1),
("permissible","adj",["允許的"],"permissible action",2),
("personally","adv",["親自地"],"personally oversee",1),
("persuasion","n",["說服","信念"],"strong persuasion",2),
("persuasive","adj",["有說服力的"],"persuasive argument",1),
("planner","n",["規劃者"],"strategic planner",1),
("positively","adv",["積極地"],"positively received",1),
("potentially","adv",["可能地"],"potentially profitable",1),
("practically","adv",["實際上"],"practically impossible",1),
("precisely","adv",["精確地"],"precisely defined",1),
("predominantly","adv",["主要地"],"predominantly used",2),
("predictable","adj",["可預測的"],"predictable outcome",1),
("predictably","adv",["可預測地"],"predictably stable",2),
("preferably","adv",["最好是"],"preferably before",1),
("presumably","adv",["大概地"],"presumably correct",1),
("previously","adv",["先前地"],"previously mentioned",1),
("primarily","adv",["主要地"],"primarily responsible",1),
("proactively","adv",["積極主動地"],"proactively manage",2),
("professionalism","n",["專業精神"],"show professionalism",1),
("professionally","adv",["專業地"],"professionally handled",1),
("profitably","adv",["有利可圖地"],"profitably operated",2),
("progressively","adv",["逐步地"],"progressively improve",2),
("prominently","adv",["顯著地"],"prominently featured",2),
("proportionally","adv",["按比例地"],"proportionally distributed",2),
("prospectively","adv",["預期地"],"prospectively analyzed",2),
("provisionally","adv",["暫時地"],"provisionally approved",2),
("punctually","adv",["準時地"],"punctually arrive",1),
("purposefully","adv",["有目的地"],"purposefully designed",2),
("qualification","n",["資格","資歷"],"professional qualification",1),
("qualifier","n",["限定詞","有資格的人"],"meet qualifiers",2),
("realistically","adv",["現實地"],"realistically assess",1),
("reasonably","adv",["合理地"],"reasonably priced",1),
("recognition","n",["認可","表彰"],"employee recognition",1),
("recommendation","n",["推薦"],"strong recommendation",1),
("redevelopment","n",["再開發"],"urban redevelopment",2),
("referral","n",["推薦","轉介"],"employee referral",1),
("reinforcement","n",["強化","增援"],"positive reinforcement",2),
("reliably","adv",["可靠地"],"reliably deliver",1),
("reluctantly","adv",["勉強地"],"reluctantly agreed",2),
("remarkably","adv",["顯著地"],"remarkably successful",1),
("reportedly","adv",["據報導"],"reportedly improved",1),
("representational","adj",["代表的"],"representational role",2),
("residential","adj",["住宅的"],"residential area",1),
("respectful","adj",["尊重的"],"respectful manner",1),
("respectively","adv",["分別地"],"respectively assigned",1),
("responsibly","adv",["負責地"],"responsibly managed",1),
("responsiveness","n",["回應能力"],"customer responsiveness",2),
("restoration","n",["恢復","修復"],"service restoration",2),
("reviewer","n",["審查者"],"performance reviewer",1),
("rigorously","adv",["嚴格地"],"rigorously tested",2),
("robustly","adv",["強健地"],"robustly designed",2),
("satisfactorily","adv",["令人滿意地"],"satisfactorily completed",1),
("selector","n",["選擇器","選拔者"],"candidate selector",2),
("significantly","adv",["顯著地"],"significantly improved",1),
("simplification","n",["簡化"],"process simplification",1),
("skillfully","adv",["熟練地"],"skillfully managed",1),
("specialization","n",["專業化"],"area of specialization",2),
("specifically","adv",["具體地"],"specifically designed",1),
("stabilization","n",["穩定化"],"market stabilization",2),
("strategically","adv",["策略性地"],"strategically planned",2),
("structurally","adv",["結構上"],"structurally sound",2),
("subsequently","adv",["隨後地"],"subsequently revised",1),
("substantially","adv",["大量地"],"substantially increase",1),
("successfully","adv",["成功地"],"successfully implemented",1),
("sufficiently","adv",["足夠地"],"sufficiently prepared",1),
("supervisory","adj",["監督的"],"supervisory role",2),
("supplementary","adj",["補充的"],"supplementary material",1),
("systematically","adv",["系統性地"],"systematically organized",2),
("thoughtfully","adv",["深思熟慮地"],"thoughtfully designed",1),
("traditionally","adv",["傳統地"],"traditionally managed",1),
("transformation","n",["轉型"],"digital transformation",1),
("transitional","adj",["過渡的"],"transitional period",2),
("transparently","adv",["透明地"],"transparently managed",2),
("tremendously","adv",["極大地"],"tremendously helpful",1),
("ultimately","adv",["最終地"],"ultimately responsible",1),
("unanimity","n",["一致同意"],"reach unanimity",2),
("unconditionally","adv",["無條件地"],"unconditionally support",2),
("undeniably","adv",["不可否認地"],"undeniably effective",2),
("understandably","adv",["可以理解地"],"understandably concerned",1),
("unequivocally","adv",["毫不含糊地"],"unequivocally stated",2),
("unfortunately","adv",["不幸地"],"unfortunately delayed",1),
("universally","adv",["普遍地"],"universally accepted",1),
("unmistakably","adv",["明確地"],"unmistakably clear",2),
("unprecedentedly","adv",["史無前例地"],"unprecedentedly high",2),
("urgently","adv",["緊急地"],"urgently required",1),
("valuably","adv",["有價值地"],"valuably contribute",2),
("variably","adv",["可變地"],"variably applied",2),
("verification","n",["驗證"],"identity verification",1),
("vigorously","adv",["大力地"],"vigorously pursue",2),
("virtuously","adv",["正直地"],"virtuously led",2),
("voluntarily","adv",["自願地"],"voluntarily resign",1),
("vulnerability","n",["脆弱性"],"market vulnerability",2),
("willfully","adv",["故意地"],"willfully ignored",2),
],
}
