"""Programmatic word derivation engine - generates word forms systematically"""

# Common suffixes and their transformations
# (input_suffix, output_suffix, from_pos, to_pos)
SUFFIX_RULES = [
    # Verb -> Noun (action/result)
    ("ate", "ation", "v", "n"),
    ("ize", "ization", "v", "n"),
    ("ify", "ification", "v", "n"),
    ("e", "ation", "v", "n"),
    ("", "ment", "v", "n"),
    ("", "ance", "v", "n"),
    ("", "ence", "v", "n"),
    ("e", "ing", "v", "n"),
    ("", "ing", "v", "n"),
    # Verb -> Agent noun
    ("e", "or", "v", "n"),
    ("e", "er", "v", "n"),
    ("", "er", "v", "n"),
    # Verb -> Adjective
    ("e", "able", "v", "adj"),
    ("", "able", "v", "adj"),
    ("e", "ive", "v", "adj"),
    ("", "ive", "v", "adj"),
    ("", "ed", "v", "adj"),
    # Noun -> Adjective
    ("", "al", "n", "adj"),
    ("y", "ical", "n", "adj"),
    ("", "ous", "n", "adj"),
    ("", "ful", "n", "adj"),
    ("", "less", "n", "adj"),
    ("", "ive", "n", "adj"),
    # Adjective -> Adverb
    ("", "ly", "adj", "adv"),
    ("le", "ly", "adj", "adv"),
    ("ic", "ically", "adj", "adv"),
    # Adjective -> Noun
    ("", "ness", "adj", "n"),
    ("t", "ce", "adj", "n"),
    ("", "ity", "adj", "n"),
]

# Known valid English derived forms organized by category
# These are manually curated to ensure quality
DERIVED_WORDS = {
"cat02": [
("accountable","adj",["負責的"],"held accountable",1),
("accumulation","n",["累積"],"wealth accumulation",2),
("adjustable","adj",["可調整的"],"adjustable rate",1),
("affordable","adj",["負擔得起的"],"affordable rates",1),
("affordably","adv",["可負擔地"],"affordably priced",1),
("allocation","n",["分配"],"resource allocation",2),
("analyst","n",["分析師"],"market analyst",1),
("annually","adv",["每年地"],"reported annually",1),
("appreciably","adv",["可觀地"],"appreciably different",2),
("assessable","adj",["可評估的"],"assessable income",2),
("auditable","adj",["可審計的"],"auditable records",2),
("bearish","adj",["看跌的"],"bearish outlook",2),
("beneficial","adj",["有益的"],"beneficial interest",1),
("beneficially","adv",["有利地"],"beneficially owned",2),
("billable","adj",["可計費的"],"billable hours",1),
("calculable","adj",["可計算的"],"calculable risk",2),
("cautionary","adj",["警告的"],"cautionary tale",2),
("centralized","adj",["集中的"],"centralized management",2),
("commercially","adv",["商業地"],"commercially viable",2),
("compensatory","adj",["補償的"],"compensatory payment",2),
("compliant","adj",["合規的"],"tax compliant",2),
("computable","adj",["可計算的"],"computable value",2),
("consecutive","adj",["連續的"],"consecutive years",2),
("conservatively","adv",["保守地"],"conservatively estimated",2),
("controllable","adj",["可控制的"],"controllable costs",1),
("cumulatively","adv",["累積地"],"cumulatively growing",2),
("defensible","adj",["可辯護的"],"defensible position",2),
("demonstrable","adj",["可證明的"],"demonstrable results",2),
("deductible","adj",["可扣除的"],"tax deductible",1),
("depreciable","adj",["可折舊的"],"depreciable asset",2),
("diligently","adv",["勤勉地"],"diligently managed",1),
("discountable","adj",["可折扣的"],"discountable offer",2),
("diversified","adj",["多元化的"],"diversified portfolio",2),
("earnestly","adv",["認真地"],"earnestly invest",2),
("economically","adv",["經濟地"],"economically sound",1),
("enforceability","n",["可執行性"],"contract enforceability",2),
("equitably","adv",["公平地"],"equitably distributed",2),
("estimable","adj",["可估計的"],"estimable value",2),
("exhaustible","adj",["可耗盡的"],"exhaustible resources",2),
("expendable","adj",["可消耗的"],"expendable budget",2),
("exponentially","adv",["指數地"],"exponentially growing",2),
("favorably","adv",["有利地"],"favorably positioned",1),
("financially","adv",["財務上"],"financially stable",1),
("foreseeably","adv",["可預見地"],"foreseeably profitable",2),
("frugally","adv",["節儉地"],"frugally managed",2),
("gainfully","adv",["有收益地"],"gainfully employed",2),
("generously","adv",["慷慨地"],"generously funded",1),
("gradually","adv",["逐漸地"],"gradually increasing",1),
("identifiable","adj",["可辨認的"],"identifiable asset",2),
("illicitly","adv",["非法地"],"illicitly obtained",2),
("immaterially","adv",["無關緊要地"],"immaterially different",3),
("incrementally","adv",["逐步地"],"incrementally improved",2),
("indispensable","adj",["不可或缺的"],"indispensable resource",2),
("inexcusable","adj",["不可原諒的"],"inexcusable loss",2),
("inevitably","adv",["不可避免地"],"inevitably increase",1),
("inflationary","adj",["通膨的"],"inflationary trend",2),
("insurable","adj",["可保險的"],"insurable risk",2),
("intangibly","adv",["無形地"],"intangibly valued",2),
("invariably","adv",["總是"],"invariably rising",2),
("justifiably","adv",["正當地"],"justifiably claimed",2),
("knowledgeably","adv",["博學地"],"knowledgeably invest",2),
("legitimately","adv",["合法地"],"legitimately earned",2),
("leveraged","adj",["槓桿化的"],"leveraged fund",2),
("liquidated","adj",["清算的"],"liquidated damages",2),
("managerially","adv",["管理上"],"managerially sound",2),
("marginally","adv",["略微地"],"marginally profitable",2),
("materially","adv",["物質上"],"materially different",2),
("maximally","adv",["最大限度地"],"maximally efficient",2),
("meaningfully","adv",["有意義地"],"meaningfully contribute",2),
("measurably","adv",["可測量地"],"measurably better",2),
("minimally","adv",["最低限度地"],"minimally required",1),
("monetarily","adv",["金錢上"],"monetarily compensated",2),
("negligibly","adv",["微不足道地"],"negligibly affected",2),
("nominally","adv",["名義上"],"nominally valued",2),
("noticeably","adv",["明顯地"],"noticeably improved",1),
("objectionable","adj",["令人反感的"],"objectionable practice",2),
("obligatorily","adv",["強制地"],"obligatorily required",2),
("observably","adv",["可觀察地"],"observably better",2),
("operationally","adv",["營運上"],"operationally efficient",2),
("optimistically","adv",["樂觀地"],"optimistically projected",2),
("ordinarily","adv",["通常"],"ordinarily expected",1),
("outstandingly","adv",["傑出地"],"outstandingly performed",2),
("painlessly","adv",["無痛地"],"painlessly processed",2),
("periodically","adv",["定期地"],"periodically reviewed",1),
("permanently","adv",["永久地"],"permanently invested",1),
("permissibly","adv",["允許地"],"permissibly allocated",2),
("plausibly","adv",["合理地"],"plausibly estimated",2),
("positively","adv",["積極地"],"positively impacted",1),
("practically","adv",["實際上"],"practically worthless",1),
("predictably","adv",["可預見地"],"predictably stable",2),
("predominantly","adv",["主要地"],"predominantly invested",2),
("presumably","adv",["大概"],"presumably profitable",1),
("previously","adv",["先前地"],"previously reported",1),
("primarily","adv",["主要地"],"primarily financed",1),
("profitably","adv",["有利可圖地"],"profitably managed",2),
("progressively","adv",["逐步地"],"progressively increasing",2),
("proportionally","adv",["按比例地"],"proportionally allocated",2),
("prudently","adv",["審慎地"],"prudently invested",2),
("quarterly","adv",["每季地"],"reported quarterly",1),
("questionably","adv",["可疑地"],"questionably valued",2),
("ratably","adv",["按比例地"],"ratably distributed",2),
("readily","adv",["輕易地"],"readily available",1),
("realistically","adv",["現實地"],"realistically valued",1),
("reasonably","adv",["合理地"],"reasonably priced",1),
("recoverability","n",["可收回性"],"asset recoverability",2),
("remarkably","adv",["顯著地"],"remarkably profitable",1),
("reportedly","adv",["據報導"],"reportedly profitable",1),
("reproducibly","adv",["可重複地"],"reproducibly generated",2),
("respectively","adv",["分別地"],"respectively valued",1),
("responsibly","adv",["負責地"],"responsibly managed",1),
("retroactively","adv",["追溯地"],"retroactively applied",2),
("revenue-generating","adj",["產生收入的"],"revenue-generating asset",2),
("satisfactorily","adv",["令人滿意地"],"satisfactorily performed",1),
("selectively","adv",["選擇性地"],"selectively invested",2),
("significantly","adv",["顯著地"],"significantly increased",1),
("simultaneously","adv",["同時地"],"simultaneously reported",1),
("solemnly","adv",["莊嚴地"],"solemnly pledged",2),
("specifically","adv",["具體地"],"specifically allocated",1),
("steadily","adv",["穩定地"],"steadily growing",1),
("strategically","adv",["策略性地"],"strategically invested",2),
("strongly","adv",["強烈地"],"strongly recommended",1),
("structurally","adv",["結構上"],"structurally sound",2),
("subsequently","adv",["隨後地"],"subsequently reported",1),
("substantially","adv",["大幅地"],"substantially increased",1),
("sufficiently","adv",["足夠地"],"sufficiently funded",1),
("sustainably","adv",["可持續地"],"sustainably managed",2),
("systematically","adv",["系統地"],"systematically reviewed",2),
("tangibly","adv",["有形地"],"tangibly valued",2),
("tentatively","adv",["暫時地"],"tentatively projected",2),
("transparently","adv",["透明地"],"transparently reported",2),
("tremendously","adv",["極大地"],"tremendously profitable",1),
("ultimately","adv",["最終地"],"ultimately profitable",1),
("unanimously","adv",["一致地"],"unanimously approved",2),
("unconditionally","adv",["無條件地"],"unconditionally guaranteed",2),
("undeniably","adv",["不可否認地"],"undeniably profitable",2),
("unexpectedly","adv",["出乎意料地"],"unexpectedly declined",1),
("unfortunately","adv",["不幸地"],"unfortunately lost",1),
("uniformly","adv",["統一地"],"uniformly applied",2),
("universally","adv",["普遍地"],"universally accepted",1),
("unreasonably","adv",["不合理地"],"unreasonably high",2),
("valuably","adv",["有價值地"],"valuably contributing",2),
("variably","adv",["可變地"],"variably priced",2),
("vigorously","adv",["大力地"],"vigorously pursued",2),
("virtually","adv",["幾乎"],"virtually eliminated",1),
("voluntarily","adv",["自願地"],"voluntarily disclosed",1),
("wholesale","adv",["批發地"],"wholesale priced",2),
],
"cat03": [
("accessible","adj",["可接近的"],"accessible market",1),
("accountably","adv",["負責地"],"accountably managed",2),
("advertiser","n",["廣告商"],"major advertiser",1),
("affordability","n",["可負擔性"],"product affordability",1),
("aggressiveness","n",["積極性"],"market aggressiveness",2),
("appealingly","adv",["吸引地"],"appealingly designed",2),
("assessable","adj",["可評估的"],"assessable market",2),
("attractively","adv",["有吸引力地"],"attractively priced",1),
("awareness","n",["認知"],"brand awareness",1),
("buyable","adj",["可購買的"],"buyable product",1),
("calculable","adj",["可計算的"],"calculable ROI",2),
("categorically","adv",["明確地"],"categorically denied",2),
("centrally","adv",["集中地"],"centrally managed",2),
("characteristically","adv",["特色地"],"characteristically bold",2),
("commercially","adv",["商業地"],"commercially successful",2),
("communicative","adj",["善於溝通的"],"communicative strategy",1),
("comparatively","adv",["相較地"],"comparatively better",1),
("compellingly","adv",["引人注目地"],"compellingly presented",2),
("competitively","adv",["競爭性地"],"competitively priced",1),
("comprehensively","adv",["全面地"],"comprehensively covered",2),
("conceivably","adv",["可想像地"],"conceivably successful",2),
("conclusively","adv",["決定性地"],"conclusively proven",2),
("conditionally","adv",["有條件地"],"conditionally offered",2),
("confidently","adv",["自信地"],"confidently marketed",1),
("consecutively","adv",["連續地"],"consecutively growing",2),
("considerably","adv",["相當大地"],"considerably improved",1),
("consistently","adv",["一貫地"],"consistently delivered",1),
("constructively","adv",["建設性地"],"constructively designed",2),
("conspicuously","adv",["顯著地"],"conspicuously promoted",2),
("conveniently","adv",["方便地"],"conveniently available",1),
("conventionally","adv",["傳統地"],"conventionally marketed",2),
("convincingly","adv",["有說服力地"],"convincingly promoted",2),
("creatively","adv",["有創意地"],"creatively designed",1),
("critically","adv",["關鍵地"],"critically acclaimed",1),
("decisively","adv",["果斷地"],"decisively marketed",2),
("deliberately","adv",["蓄意地"],"deliberately targeted",2),
("demonstrably","adv",["可證明地"],"demonstrably effective",2),
("dependably","adv",["可靠地"],"dependably delivered",2),
("descriptively","adv",["描述性地"],"descriptively labeled",2),
("differently","adv",["不同地"],"differently positioned",1),
("dramatically","adv",["戲劇性地"],"dramatically improved",1),
("durably","adv",["持久地"],"durably constructed",2),
("dynamically","adv",["動態地"],"dynamically priced",2),
("effectively","adv",["有效地"],"effectively marketed",1),
("efficiently","adv",["高效地"],"efficiently distributed",1),
("enthusiastically","adv",["熱情地"],"enthusiastically received",1),
("especially","adv",["特別地"],"especially popular",1),
("essentially","adv",["本質上"],"essentially different",1),
("exclusively","adv",["獨家地"],"exclusively offered",1),
("expansively","adv",["大範圍地"],"expansively marketed",2),
("experimentally","adv",["實驗性地"],"experimentally launched",2),
("explicitly","adv",["明確地"],"explicitly stated",1),
("exponentially","adv",["指數地"],"exponentially growing",2),
("extensively","adv",["廣泛地"],"extensively promoted",2),
("favorably","adv",["有利地"],"favorably reviewed",1),
("feasibly","adv",["可行地"],"feasibly implemented",2),
("globally","adv",["全球地"],"globally marketed",1),
("impressively","adv",["令人印象深刻地"],"impressively performed",1),
("independently","adv",["獨立地"],"independently operated",1),
("indisputably","adv",["無可爭議地"],"indisputably leading",2),
("ineffectively","adv",["無效地"],"ineffectively marketed",2),
("initially","adv",["最初地"],"initially launched",1),
("innovatively","adv",["創新地"],"innovatively designed",2),
("intentionally","adv",["有意地"],"intentionally branded",2),
("internationally","adv",["國際性地"],"internationally marketed",1),
("measurably","adv",["可衡量地"],"measurably improved",2),
("memorably","adv",["令人難忘地"],"memorably branded",2),
("methodically","adv",["有方法地"],"methodically planned",2),
("noticeably","adv",["明顯地"],"noticeably different",1),
("objectively","adv",["客觀地"],"objectively evaluated",1),
("originally","adv",["原本地"],"originally conceived",1),
("outstandingly","adv",["傑出地"],"outstandingly performed",2),
("overwhelmingly","adv",["壓倒性地"],"overwhelmingly positive",2),
("perceptibly","adv",["明顯地"],"perceptibly different",2),
("persuasively","adv",["有說服力地"],"persuasively presented",2),
("predominantly","adv",["主要地"],"predominantly targeting",2),
("preferably","adv",["最好是"],"preferably organic",1),
("previously","adv",["先前地"],"previously unknown",1),
("proactively","adv",["主動地"],"proactively marketed",2),
("profitably","adv",["有利可圖地"],"profitably sold",2),
("progressively","adv",["逐步地"],"progressively expanding",2),
("prominently","adv",["顯著地"],"prominently displayed",2),
("proportionally","adv",["按比例地"],"proportionally allocated",2),
("prospectively","adv",["預期地"],"prospectively planned",2),
("reliably","adv",["可靠地"],"reliably delivered",1),
("remarkably","adv",["顯著地"],"remarkably successful",1),
("selectively","adv",["選擇性地"],"selectively targeted",2),
("significantly","adv",["顯著地"],"significantly boosted",1),
("simultaneously","adv",["同時地"],"simultaneously launched",1),
("specifically","adv",["具體地"],"specifically targeted",1),
("strategically","adv",["策略性地"],"strategically positioned",2),
("substantially","adv",["大幅地"],"substantially increased",1),
("successfully","adv",["成功地"],"successfully launched",1),
("sufficiently","adv",["足夠地"],"sufficiently promoted",1),
("sustainably","adv",["可持續地"],"sustainably sourced",2),
("systematically","adv",["系統地"],"systematically analyzed",2),
("transparently","adv",["透明地"],"transparently communicated",2),
("tremendously","adv",["極大地"],"tremendously popular",1),
("ultimately","adv",["最終"],"ultimately profitable",1),
("uniquely","adv",["獨特地"],"uniquely positioned",1),
("universally","adv",["普遍地"],"universally appealing",1),
("unmistakably","adv",["明確地"],"unmistakably branded",2),
("unprecedentedly","adv",["前所未有地"],"unprecedentedly popular",2),
("vigorously","adv",["大力地"],"vigorously promoted",2),
("virtually","adv",["幾乎"],"virtually every",1),
("visually","adv",["視覺上"],"visually appealing",1),
],
"cat04": [
("accountable","adj",["負責的"],"held accountable",1),
("accurately","adv",["準確地"],"accurately assessed",1),
("adaptable","adj",["適應力強的"],"adaptable worker",1),
("admirably","adv",["令人欽佩地"],"admirably handled",2),
("advantageous","adj",["有利的"],"advantageous position",2),
("amicably","adv",["友好地"],"amicably resolved",2),
("assertively","adv",["堅定地"],"assertively communicate",2),
("attentively","adv",["專注地"],"attentively listen",1),
("autonomously","adv",["自主地"],"autonomously work",2),
("beneficially","adv",["有益地"],"beneficially impact",2),
("capably","adv",["有能力地"],"capably managed",2),
("carefully","adv",["仔細地"],"carefully screened",1),
("collectively","adv",["集體地"],"collectively agree",1),
("commendably","adv",["值得讚許地"],"commendably performed",2),
("communicatively","adv",["有溝通地"],"communicatively skilled",2),
("compassionately","adv",["富有同情心地"],"compassionately lead",2),
("competently","adv",["稱職地"],"competently managed",1),
("comprehensively","adv",["全面地"],"comprehensively trained",2),
("confidently","adv",["自信地"],"confidently lead",1),
("conscientiously","adv",["認真地"],"conscientiously work",2),
("consistently","adv",["一貫地"],"consistently performed",1),
("constructively","adv",["建設性地"],"constructively feedback",2),
("cooperatively","adv",["合作地"],"cooperatively work",1),
("courageously","adv",["勇敢地"],"courageously lead",2),
("decisively","adv",["果斷地"],"decisively act",2),
("dedicated","adj",["敬業的"],"dedicated employee",1),
("deliberately","adv",["深思熟慮地"],"deliberately chose",2),
("dependably","adv",["可靠地"],"dependably perform",2),
("diligently","adv",["勤奮地"],"diligently work",1),
("diplomatically","adv",["圓滑地"],"diplomatically handle",2),
("discreetly","adv",["謹慎地"],"discreetly manage",2),
("effectively","adv",["有效地"],"effectively lead",1),
("efficiently","adv",["高效地"],"efficiently manage",1),
("empathetically","adv",["有同理心地"],"empathetically respond",2),
("enthusiastically","adv",["熱情地"],"enthusiastically participate",1),
("equitably","adv",["公平地"],"equitably treated",2),
("ethically","adv",["道德地"],"ethically managed",2),
("exceptionally","adv",["非常地"],"exceptionally talented",1),
("exhaustively","adv",["詳盡地"],"exhaustively reviewed",2),
("explicitly","adv",["明確地"],"explicitly stated",1),
("fairly","adv",["公平地"],"fairly compensated",1),
("flexibly","adv",["靈活地"],"flexibly scheduled",1),
("formally","adv",["正式地"],"formally trained",1),
("genuinely","adv",["真誠地"],"genuinely care",1),
("harmoniously","adv",["和諧地"],"harmoniously work",2),
("impartially","adv",["公正地"],"impartially evaluate",2),
("inclusively","adv",["包容地"],"inclusively managed",2),
("individually","adv",["個別地"],"individually assessed",1),
("intentionally","adv",["故意地"],"intentionally designed",2),
("judiciously","adv",["明智地"],"judiciously manage",2),
("knowledgeably","adv",["博學地"],"knowledgeably advise",2),
("loyally","adv",["忠實地"],"loyally serve",1),
("meaningfully","adv",["有意義地"],"meaningfully engage",2),
("methodically","adv",["有條理地"],"methodically organize",2),
("objectively","adv",["客觀地"],"objectively assess",1),
("patiently","adv",["耐心地"],"patiently mentor",1),
("perceptively","adv",["敏銳地"],"perceptively observe",2),
("persistently","adv",["堅持地"],"persistently pursue",2),
("persuasively","adv",["有說服力地"],"persuasively argue",2),
("proactively","adv",["主動地"],"proactively recruit",2),
("productively","adv",["有生產力地"],"productively work",1),
("professionally","adv",["專業地"],"professionally handled",1),
("proficiently","adv",["熟練地"],"proficiently perform",1),
("purposefully","adv",["有目的地"],"purposefully lead",2),
("reliably","adv",["可靠地"],"reliably perform",1),
("resourcefully","adv",["足智多謀地"],"resourcefully solve",2),
("respectfully","adv",["尊敬地"],"respectfully communicate",1),
("responsibly","adv",["負責地"],"responsibly manage",1),
("selectively","adv",["選擇性地"],"selectively recruit",2),
("sensitively","adv",["敏感地"],"sensitively handle",2),
("strategically","adv",["策略性地"],"strategically plan",2),
("successfully","adv",["成功地"],"successfully onboard",1),
("supportively","adv",["支持地"],"supportively manage",2),
("systematically","adv",["系統地"],"systematically train",2),
("tactfully","adv",["圓滑地"],"tactfully address",2),
("thoughtfully","adv",["深思熟慮地"],"thoughtfully design",1),
("transparently","adv",["透明地"],"transparently report",2),
("uniformly","adv",["統一地"],"uniformly applied",2),
("voluntarily","adv",["自願地"],"voluntarily participate",1),
],
"cat05": [
("accurately","adv",["準確地"],"accurately measure",1),
("adequately","adv",["充分地"],"adequately maintained",1),
("adjustable","adj",["可調整的"],"adjustable mechanism",1),
("advantageously","adv",["有利地"],"advantageously positioned",2),
("automatically","adv",["自動地"],"automatically controlled",1),
("carefully","adv",["仔細地"],"carefully inspected",1),
("comparably","adv",["可比較地"],"comparably produced",2),
("competently","adv",["稱職地"],"competently operated",1),
("comprehensively","adv",["全面地"],"comprehensively tested",2),
("consistently","adv",["一致地"],"consistently produced",1),
("continuously","adv",["持續地"],"continuously running",1),
("controllable","adj",["可控的"],"controllable variable",1),
("correctively","adv",["糾正地"],"correctively adjusted",2),
("durably","adv",["耐用地"],"durably constructed",2),
("effectively","adv",["有效地"],"effectively operated",1),
("efficiently","adv",["高效地"],"efficiently manufactured",1),
("environmentally","adv",["環境上"],"environmentally friendly",1),
("ergonomically","adv",["人體工學地"],"ergonomically designed",2),
("hazardously","adv",["危險地"],"hazardously stored",2),
("hydraulically","adv",["液壓地"],"hydraulically operated",2),
("industrially","adv",["工業地"],"industrially produced",2),
("innovatively","adv",["創新地"],"innovatively designed",2),
("measurably","adv",["可衡量地"],"measurably improved",2),
("mechanically","adv",["機械地"],"mechanically sound",2),
("meticulously","adv",["一絲不苟地"],"meticulously assembled",2),
("methodically","adv",["有條理地"],"methodically inspected",2),
("operationally","adv",["營運上"],"operationally efficient",2),
("optimally","adv",["最佳地"],"optimally configured",2),
("periodically","adv",["定期地"],"periodically maintained",1),
("precisely","adv",["精確地"],"precisely manufactured",2),
("preventively","adv",["預防性地"],"preventively maintained",2),
("productively","adv",["有生產力地"],"productively operated",1),
("proportionally","adv",["按比例地"],"proportionally scaled",2),
("reliably","adv",["可靠地"],"reliably operate",1),
("repeatedly","adv",["反覆地"],"repeatedly tested",1),
("reproducibly","adv",["可再現地"],"reproducibly manufactured",2),
("rigorously","adv",["嚴格地"],"rigorously inspected",2),
("robustly","adv",["強健地"],"robustly designed",2),
("safely","adv",["安全地"],"safely operated",1),
("sequentially","adv",["依序地"],"sequentially processed",2),
("significantly","adv",["顯著地"],"significantly reduced",1),
("simultaneously","adv",["同時地"],"simultaneously produced",1),
("skillfully","adv",["熟練地"],"skillfully operated",1),
("specifically","adv",["具體地"],"specifically designed",1),
("standardly","adv",["標準地"],"standardly produced",2),
("strategically","adv",["策略性地"],"strategically manufactured",2),
("substantially","adv",["大幅地"],"substantially improved",1),
("successfully","adv",["成功地"],"successfully tested",1),
("sustainably","adv",["可持續地"],"sustainably produced",2),
("systematically","adv",["系統地"],"systematically checked",2),
("technically","adv",["技術上"],"technically advanced",1),
("thoroughly","adv",["徹底地"],"thoroughly inspected",1),
("uniformly","adv",["均勻地"],"uniformly produced",2),
("verifiably","adv",["可驗證地"],"verifiably tested",2),
],
}
