"""Additional TOEIC vocabulary data - Categories 02-08"""
WORDS_EXTRA_1 = {
"cat02": [
("account","n",["帳戶","帳目"],"bank account",1),
("accountant","n",["會計師"],"certified accountant",1),
("accounting","n",["會計","會計學"],"accounting department",1),
("accumulate","v",["累積","積聚"],"accumulate wealth",2),
("accurate","adj",["準確的","精確的"],"accurate data",1),
("adjust","v",["調整","修正"],"adjust the budget",1),
("adjustment","n",["調整","修正"],"price adjustment",1),
("afford","v",["負擔得起"],"afford the cost",1),
("affordable","adj",["負擔得起的"],"affordable price",1),
("amount","n",["金額","數量"],"total amount",1),
("appreciate","v",["增值","感謝"],"appreciate in value",1),
("appreciation","n",["增值","感激"],"currency appreciation",2),
("appropriation","n",["撥款"],"budget appropriation",2),
("asset","n",["資產"],"company assets",1),
("audit","v",["審計","稽核"],"audit accounts",2),
("auditor","n",["審計師"],"external auditor",2),
("balance","n",["餘額","平衡"],"account balance",1),
("bankruptcy","n",["破產"],"file for bankruptcy",2),
("bill","n",["帳單","票據"],"utility bill",1),
("bond","n",["債券"],"government bond",2),
("bookkeeping","n",["簿記"],"accurate bookkeeping",2),
("borrow","v",["借入","借款"],"borrow money",1),
("broker","n",["經紀人"],"stock broker",2),
("calculate","v",["計算","核算"],"calculate costs",1),
("calculation","n",["計算","核算"],"cost calculation",1),
("capital","n",["資本","資金"],"working capital",2),
("cash","n",["現金"],"cash flow",1),
("charge","v",["收費","索價"],"charge a fee",1),
("check","n",["支票"],"write a check",1),
("claim","n",["索賠","要求"],"insurance claim",1),
("collateral","n",["擔保品","抵押品"],"provide collateral",2),
("commission","n",["佣金"],"earn commission",2),
("commodity","n",["商品","期貨"],"commodity market",2),
("compound","adj",["複合的"],"compound interest",2),
("consolidate","v",["合併","整合"],"consolidate accounts",2),
("consume","v",["消費","消耗"],"consume resources",1),
("consumer","n",["消費者"],"consumer spending",1),
("contribution","n",["捐獻","貢獻"],"pension contribution",1),
("cost","n",["成本","費用"],"operating cost",1),
("credit","n",["信用","貸方"],"credit rating",1),
("creditor","n",["債權人"],"major creditor",2),
("currency","n",["貨幣","通貨"],"foreign currency",1),
("debit","n",["借方","扣款"],"debit card",1),
("debt","n",["債務","負債"],"pay off debt",1),
("declare","v",["申報","宣告"],"declare income",1),
("deduct","v",["扣除","減去"],"deduct taxes",1),
("deduction","n",["扣除額","減除"],"tax deduction",1),
("default","v",["違約","不履行"],"default on a loan",2),
("deficit","n",["赤字","虧損"],"budget deficit",2),
("deposit","n",["存款","押金"],"make a deposit",1),
("depreciate","v",["折舊","貶值"],"depreciate over time",2),
("depreciation","n",["折舊","貶值"],"asset depreciation",2),
("derive","v",["獲得","衍生"],"derive income from",2),
("determine","v",["決定","確定"],"determine the value",1),
("diminish","v",["減少","減小"],"diminish in value",2),
("disbursement","n",["支出","支付"],"fund disbursement",3),
("discount","n",["折扣"],"offer a discount",1),
("disparity","n",["差距","不等"],"income disparity",2),
("dividend","n",["股利","股息"],"pay dividends",2),
("due","adj",["到期的","應付的"],"payment due",1),
("earn","v",["賺取","獲得"],"earn interest",1),
("earnings","n",["收益","所得"],"quarterly earnings",1),
("economical","adj",["經濟實惠的"],"economical solution",1),
("economy","n",["經濟","節約"],"global economy",1),
("endowment","n",["捐贈基金"],"university endowment",3),
("equitable","adj",["公平的","公正的"],"equitable distribution",2),
("equity","n",["股權","權益"],"shareholder equity",2),
("estimate","n",["估計","預算"],"cost estimate",1),
("exceed","v",["超過","超出"],"exceed the budget",1),
("exchange","n",["匯兌","交易所"],"stock exchange",1),
("exemption","n",["免稅","豁免"],"tax exemption",2),
("expenditure","n",["支出","開銷"],"capital expenditure",2),
("expense","n",["費用","開支"],"travel expense",1),
("export","v",["出口","輸出"],"export goods",1),
("fee","n",["費用","手續費"],"service fee",1),
("fiduciary","adj",["信託的","受託的"],"fiduciary duty",3),
("figure","n",["數字","金額"],"sales figure",1),
("finance","n",["金融","財務"],"corporate finance",1),
("financial","adj",["金融的","財務的"],"financial statement",1),
("fiscal","adj",["財政的","會計的"],"fiscal year",2),
("fluctuate","v",["波動","變動"],"prices fluctuate",2),
("forecast","v",["預測"],"forecast revenue",1),
("forfeit","v",["喪失","沒收"],"forfeit a deposit",2),
("fortune","n",["財富","運氣"],"make a fortune",1),
("fraud","n",["詐欺","欺騙"],"financial fraud",2),
("fund","n",["基金","資金"],"mutual fund",1),
("funding","n",["資金","撥款"],"secure funding",1),
("gain","n",["收益","利潤"],"capital gain",1),
("grant","n",["補助金","撥款"],"research grant",1),
("gross","adj",["總的","毛的"],"gross income",1),
("guarantee","n",["保證","擔保"],"money-back guarantee",1),
("import","v",["進口","輸入"],"import products",1),
("impose","v",["徵收","課徵"],"impose a tax",2),
("incentive","n",["激勵","獎勵"],"tax incentive",2),
("income","n",["收入","所得"],"annual income",1),
("incur","v",["招致","產生"],"incur costs",2),
("indemnity","n",["賠償","補償"],"indemnity payment",3),
("index","n",["指數","索引"],"stock index",1),
("inflation","n",["通膨"],"inflation rate",1),
("inherit","v",["繼承"],"inherit property",1),
("installment","n",["分期付款"],"monthly installment",1),
("insure","v",["投保","保險"],"insure property",1),
("interest","n",["利息","利率"],"interest rate",1),
("inventory","n",["存貨","盤點"],"inventory management",1),
("invest","v",["投資"],"invest wisely",1),
("investment","n",["投資"],"return on investment",1),
("investor","n",["投資者"],"institutional investor",1),
("invoice","n",["發票","帳單"],"issue an invoice",1),
("ledger","n",["帳簿","分類帳"],"general ledger",2),
("lend","v",["借出","貸款"],"lend money",1),
("leverage","n",["槓桿","影響力"],"financial leverage",2),
("liability","n",["負債","責任"],"current liabilities",2),
("liquidate","v",["清算","變現"],"liquidate assets",2),
("loan","n",["貸款","借款"],"bank loan",1),
("loss","n",["損失","虧損"],"net loss",1),
("margin","n",["利潤率","保證金"],"profit margin",1),
("maturity","n",["到期日"],"bond maturity",2),
("monetary","adj",["貨幣的","金融的"],"monetary policy",2),
("mortgage","n",["抵押貸款"],"home mortgage",1),
("negotiate","v",["談判","協商"],"negotiate terms",1),
("net","adj",["淨的"],"net income",1),
("offset","v",["抵消","補償"],"offset losses",2),
("outstanding","adj",["未結清的","傑出的"],"outstanding balance",1),
("overdraft","n",["透支"],"bank overdraft",2),
("overhead","n",["經常費用","管理費"],"overhead costs",2),
("owe","v",["欠","虧欠"],"owe money",1),
("payable","adj",["應付的"],"accounts payable",1),
("payment","n",["付款","支付"],"payment method",1),
("payroll","n",["薪資總額"],"manage payroll",1),
("pension","n",["退休金"],"pension fund",1),
("portfolio","n",["投資組合"],"investment portfolio",2),
("premium","n",["保費","溢價"],"insurance premium",2),
("principal","n",["本金","負責人"],"loan principal",2),
("proceeds","n",["收益","所得"],"sale proceeds",2),
("profit","n",["利潤"],"operating profit",1),
("profitable","adj",["有利潤的"],"profitable venture",1),
("projection","n",["預測"],"financial projection",2),
("property","n",["財產","不動產"],"property value",1),
("prospectus","n",["說明書","公開說明書"],"company prospectus",3),
("provision","n",["備抵","準備金"],"loan provision",2),
("purchase","v",["購買","採購"],"purchase equipment",1),
("quota","n",["配額"],"import quota",2),
("quote","n",["報價","引述"],"price quote",1),
("rate","n",["費率","比率"],"exchange rate",1),
("receipt","n",["收據","收入"],"sales receipt",1),
("receivable","adj",["應收的"],"accounts receivable",1),
("recoup","v",["收回","補償"],"recoup losses",2),
("redeem","v",["贖回","兌換"],"redeem a coupon",2),
("refund","n",["退款"],"full refund",1),
("reimburse","v",["報銷","償還"],"reimburse expenses",2),
("remit","v",["匯款","匯寄"],"remit payment",2),
("remittance","n",["匯款"],"overseas remittance",2),
("render","v",["提交","呈報"],"render an account",2),
("repay","v",["償還","歸還"],"repay a loan",1),
("reserve","n",["準備金","儲備"],"cash reserve",2),
("retail","n",["零售"],"retail price",1),
("return","n",["報酬","收益"],"return on investment",1),
("revenue","n",["收入","營收"],"total revenue",1),
("royalty","n",["版稅","權利金"],"pay royalties",2),
("salary","n",["薪資","薪水"],"annual salary",1),
("savings","n",["儲蓄"],"savings account",1),
("secure","v",["取得","擔保"],"secure a loan",1),
("share","n",["股份","股票"],"market share",1),
("shareholder","n",["股東"],"majority shareholder",1),
("solvent","adj",["有償付能力的"],"remain solvent",2),
("statement","n",["報表","對帳單"],"bank statement",1),
("stock","n",["股票","庫存"],"stock market",1),
("subsidy","n",["補助","補貼"],"government subsidy",2),
("surplus","n",["盈餘"],"trade surplus",2),
("tariff","n",["關稅"],"import tariff",2),
("tax","n",["稅","稅金"],"income tax",1),
("taxation","n",["稅收","課稅"],"corporate taxation",2),
("transaction","n",["交易"],"financial transaction",1),
("transfer","v",["轉帳","轉移"],"transfer funds",1),
("treasury","n",["國庫","財政部"],"treasury bond",2),
("turnover","n",["營業額"],"annual turnover",1),
("underwrite","v",["承保","承銷"],"underwrite a policy",3),
("valuation","n",["估價","估值"],"company valuation",2),
("value","n",["價值"],"market value",1),
("venture","n",["創業","風險投資"],"venture capital",2),
("voucher","n",["憑證","代金券"],"purchase voucher",1),
("wage","n",["工資","薪資"],"minimum wage",1),
("wealth","n",["財富"],"accumulate wealth",1),
("wholesale","n",["批發"],"wholesale market",2),
("withdraw","v",["提取","撤回"],"withdraw funds",1),
("withdrawal","n",["提款","撤回"],"cash withdrawal",1),
("withhold","v",["扣留","預扣"],"withhold taxes",2),
("write-off","n",["沖銷","注銷"],"bad debt write-off",2),
("yield","n",["收益率","產量"],"bond yield",2),
],
"cat03": [
("advertise","v",["廣告","宣傳"],"advertise a product",1),
("advertisement","n",["廣告"],"print advertisement",1),
("advertising","n",["廣告業"],"advertising campaign",1),
("appeal","v",["吸引","呼籲"],"appeal to customers",1),
("attract","v",["吸引"],"attract clients",1),
("audience","n",["受眾","觀眾"],"target audience",1),
("awareness","n",["意識","認知"],"brand awareness",1),
("billboard","n",["廣告看板"],"billboard advertising",1),
("boost","v",["提升","促進"],"boost sales",1),
("brand","n",["品牌"],"brand identity",1),
("brochure","n",["手冊","簡介"],"product brochure",1),
("browse","v",["瀏覽","閱覽"],"browse products",1),
("bulk","n",["大量","散裝"],"buy in bulk",1),
("buyer","n",["買家","採購者"],"potential buyer",1),
("campaign","n",["活動","宣傳"],"marketing campaign",1),
("catalog","n",["目錄","產品冊"],"product catalog",1),
("clientele","n",["客戶群"],"loyal clientele",2),
("commercial","adj",["商業的"],"commercial success",1),
("commission","n",["佣金"],"sales commission",2),
("commodity","n",["商品"],"consumer commodity",2),
("comparable","adj",["可比較的"],"comparable products",1),
("compete","v",["競爭"],"compete for market share",1),
("competitive","adj",["有競爭力的"],"competitive pricing",1),
("competitor","n",["競爭者"],"direct competitor",1),
("complimentary","adj",["免費的","讚美的"],"complimentary sample",1),
("consumer","n",["消費者"],"consumer behavior",1),
("consumption","n",["消費","消耗"],"energy consumption",1),
("contract","n",["合約","契約"],"sign a contract",1),
("conversion","n",["轉換","轉化"],"conversion rate",2),
("convince","v",["說服","使確信"],"convince a client",1),
("coupon","n",["優惠券"],"discount coupon",1),
("customize","v",["客製化"],"customize a product",1),
("deal","n",["交易","優惠"],"close a deal",1),
("deliver","v",["交付","送達"],"deliver on time",1),
("delivery","n",["交付","遞送"],"fast delivery",1),
("demand","n",["需求"],"consumer demand",1),
("demographic","n",["人口統計"],"target demographic",2),
("demonstrate","v",["展示","示範"],"demonstrate a product",1),
("discount","n",["折扣"],"volume discount",1),
("display","v",["展示","陳列"],"display products",1),
("distribute","v",["分銷","配送"],"distribute widely",1),
("distributor","n",["經銷商"],"authorized distributor",1),
("diversify","v",["多樣化"],"diversify product line",2),
("dominate","v",["主導","稱霸"],"dominate the market",2),
("e-commerce","n",["電子商務"],"e-commerce platform",1),
("endorse","v",["代言","背書"],"endorse a brand",2),
("engage","v",["吸引","參與"],"engage customers",1),
("enhance","v",["增強","提升"],"enhance brand image",1),
("entice","v",["誘導","吸引"],"entice buyers",2),
("exclusive","adj",["獨家的","專屬的"],"exclusive offer",1),
("expand","v",["擴展"],"expand the market",1),
("exposure","n",["曝光","接觸"],"media exposure",1),
("feature","n",["特色","功能"],"product feature",1),
("feedback","n",["回饋","意見"],"customer feedback",1),
("flyer","n",["傳單"],"distribute flyers",1),
("franchise","n",["加盟","特許經營"],"franchise agreement",2),
("fulfill","v",["履行","完成"],"fulfill orders",1),
("generate","v",["產生","創造"],"generate leads",1),
("guarantee","n",["保證","擔保"],"satisfaction guarantee",1),
("highlight","v",["強調","突顯"],"highlight benefits",1),
("impact","n",["影響","衝擊"],"market impact",1),
("incentive","n",["激勵","獎勵"],"purchase incentive",2),
("influence","v",["影響"],"influence buying decisions",1),
("inquire","v",["詢問","查詢"],"inquire about products",1),
("innovative","adj",["創新的"],"innovative marketing",1),
("introduce","v",["推出","介紹"],"introduce a product",1),
("launch","v",["推出","上市"],"launch a campaign",1),
("loyal","adj",["忠誠的"],"loyal customer",1),
("loyalty","n",["忠誠度"],"brand loyalty",1),
("manufacturer","n",["製造商"],"leading manufacturer",1),
("market","v",["銷售","行銷"],"market a product",1),
("merchandise","n",["商品","貨品"],"retail merchandise",1),
("negotiate","v",["談判","協商"],"negotiate a deal",1),
("niche","n",["利基","小眾市場"],"niche market",2),
("offer","n",["優惠","報價"],"special offer",1),
("outlet","n",["通路","門市"],"retail outlet",1),
("outsell","v",["銷售量超過"],"outsell competitors",2),
("penetrate","v",["滲透","打入"],"penetrate a market",2),
("pitch","n",["推銷","簡報"],"sales pitch",1),
("position","v",["定位"],"position a brand",1),
("potential","adj",["潛在的"],"potential customer",1),
("premium","adj",["高級的","優質的"],"premium product",1),
("price","v",["定價"],"price competitively",1),
("pricing","n",["定價","價格策略"],"pricing strategy",1),
("product","n",["產品"],"new product",1),
("profile","n",["輪廓","概況"],"customer profile",1),
("profit","n",["利潤"],"profit margin",1),
("promote","v",["促銷","推廣"],"promote a sale",1),
("promotion","n",["促銷","推廣"],"special promotion",1),
("prospect","n",["潛在客戶"],"qualified prospect",1),
("publicize","v",["宣傳","公開"],"publicize an event",1),
("purchase","v",["購買"],"purchase online",1),
("rebate","n",["回扣","退款"],"mail-in rebate",2),
("recommend","v",["推薦"],"recommend products",1),
("referral","n",["推薦","轉介"],"customer referral",1),
("refund","n",["退款"],"process a refund",1),
("retail","n",["零售"],"retail store",1),
("retailer","n",["零售商"],"online retailer",1),
("revenue","n",["營收"],"advertising revenue",1),
("rival","n",["競爭對手"],"market rival",1),
("sample","n",["樣品","試用品"],"free sample",1),
("segment","n",["區隔","市場區段"],"market segment",1),
("sell","v",["銷售","賣出"],"sell products",1),
("slogan","n",["標語","口號"],"catchy slogan",1),
("solicit","v",["招攬","徵求"],"solicit business",2),
("sponsor","v",["贊助"],"sponsor an event",1),
("strategy","n",["策略"],"marketing strategy",1),
("subscribe","v",["訂閱"],"subscribe to a service",1),
("subscription","n",["訂閱"],"monthly subscription",1),
("supply","v",["供應","提供"],"supply products",1),
("supplier","n",["供應商"],"major supplier",1),
("surplus","n",["剩餘","過剩"],"inventory surplus",2),
("survey","n",["調查"],"market survey",1),
("target","v",["瞄準","以...為目標"],"target young adults",1),
("testimonial","n",["推薦信","證言"],"customer testimonial",2),
("trademark","n",["商標"],"registered trademark",2),
("trend","n",["趨勢"],"market trend",1),
("unique","adj",["獨特的"],"unique selling point",1),
("vendor","n",["供應商","攤販"],"street vendor",1),
("venture","n",["事業","企業"],"business venture",2),
("warranty","n",["保固","保證"],"product warranty",1),
("wholesale","n",["批發"],"wholesale price",2),
],
"cat04": [
("absenteeism","n",["缺勤","曠職"],"reduce absenteeism",2),
("accommodate","v",["容納","配合"],"accommodate requests",1),
("allowance","n",["津貼","補助"],"travel allowance",1),
("applicant","n",["申請者","應徵者"],"job applicant",1),
("application","n",["申請","應用"],"job application",1),
("apply","v",["申請","應用"],"apply for a position",1),
("appraisal","n",["考核","評估"],"performance appraisal",2),
("apprentice","n",["學徒","實習生"],"hire an apprentice",2),
("aptitude","n",["資質","天賦"],"aptitude test",2),
("assign","v",["指派","分配"],"assign duties",1),
("attendance","n",["出勤","出席"],"attendance record",1),
("background","n",["背景","資歷"],"professional background",1),
("benefit","n",["福利","津貼"],"employee benefits",1),
("bonus","n",["獎金","紅利"],"annual bonus",1),
("candidate","n",["候選人","應徵者"],"ideal candidate",1),
("career","n",["職業","生涯"],"career development",1),
("casual","adj",["臨時的","休閒的"],"casual worker",1),
("certificate","n",["證書","執照"],"training certificate",1),
("certification","n",["認證","證明"],"professional certification",1),
("colleague","n",["同事"],"work colleague",1),
("compensate","v",["補償","給予報酬"],"compensate employees",2),
("compensation","n",["薪酬","補償"],"total compensation",2),
("competence","n",["能力","勝任"],"professional competence",1),
("complaint","n",["投訴","抱怨"],"file a complaint",1),
("conduct","n",["行為","操守"],"code of conduct",1),
("confidential","adj",["機密的"],"confidential records",2),
("contract","n",["合約","契約"],"employment contract",1),
("contractor","n",["承包商","約聘人員"],"independent contractor",1),
("contribute","v",["貢獻"],"contribute to the team",1),
("credential","n",["資格證明"],"professional credentials",2),
("curriculum","n",["課程"],"training curriculum",2),
("dedicate","v",["奉獻","致力"],"dedicated employee",1),
("demotion","n",["降職"],"face demotion",2),
("department","n",["部門"],"HR department",1),
("designate","v",["指定","任命"],"designate a role",2),
("develop","v",["發展","培養"],"develop skills",1),
("development","n",["發展","培訓"],"professional development",1),
("disability","n",["殘疾","障礙"],"disability insurance",2),
("discharge","v",["解僱","免職"],"discharge an employee",2),
("discipline","n",["紀律","懲處"],"workplace discipline",1),
("discrimination","n",["歧視"],"prevent discrimination",2),
("dismiss","v",["解僱","開除"],"dismiss an employee",2),
("diversity","n",["多元化"],"workplace diversity",1),
("eligible","adj",["有資格的","符合條件的"],"eligible for benefits",1),
("employ","v",["僱用"],"employ workers",1),
("employee","n",["員工"],"full-time employee",1),
("employer","n",["雇主"],"current employer",1),
("employment","n",["就業","僱用"],"employment rate",1),
("empower","v",["授權","賦能"],"empower staff",2),
("entitle","v",["使有權利"],"entitled to leave",1),
("evaluate","v",["評估"],"evaluate performance",1),
("evaluation","n",["評估","考核"],"annual evaluation",1),
("exempt","adj",["豁免的","免除的"],"exempt employee",2),
("experience","n",["經驗","經歷"],"work experience",1),
("expertise","n",["專業知識"],"technical expertise",1),
("facilitate","v",["促進","推動"],"facilitate training",2),
("flexible","adj",["彈性的","靈活的"],"flexible schedule",1),
("freelance","adj",["自由職業的"],"freelance worker",1),
("full-time","adj",["全職的"],"full-time position",1),
("grievance","n",["申訴","不滿"],"file a grievance",2),
("harassment","n",["騷擾"],"workplace harassment",2),
("hire","v",["僱用","聘請"],"hire new staff",1),
("hourly","adj",["按時計算的"],"hourly wage",1),
("human resources","n",["人力資源"],"HR department",1),
("incentive","n",["激勵","獎勵"],"performance incentive",2),
("induction","n",["就職培訓","引導"],"induction program",2),
("intern","n",["實習生"],"summer intern",1),
("internship","n",["實習"],"paid internship",1),
("interview","n",["面試","面談"],"job interview",1),
("labor","n",["勞工","勞動"],"labor market",1),
("layoff","n",["裁員"],"mass layoff",2),
("leave","n",["休假"],"maternity leave",1),
("mentor","n",["導師"],"assign a mentor",1),
("morale","n",["士氣","民心"],"boost morale",1),
("negotiate","v",["談判"],"negotiate salary",1),
("onboarding","n",["入職培訓"],"onboarding process",1),
("orientation","n",["新人培訓"],"employee orientation",1),
("outsource","v",["外包"],"outsource tasks",2),
("overtime","n",["加班"],"work overtime",1),
("part-time","adj",["兼職的"],"part-time job",1),
("paycheck","n",["薪資支票"],"monthly paycheck",1),
("payroll","n",["薪資"],"payroll system",1),
("pension","n",["退休金"],"pension plan",1),
("performance","n",["績效","表現"],"performance review",1),
("personnel","n",["人員","員工"],"personnel management",1),
("position","n",["職位","崗位"],"open position",1),
("probation","n",["試用期"],"probation period",2),
("productive","adj",["有生產力的"],"productive worker",1),
("proficient","adj",["精通的","熟練的"],"proficient in English",1),
("promote","v",["晉升","提拔"],"promote an employee",1),
("promotion","n",["晉升"],"earn a promotion",1),
("qualification","n",["資格","學歷"],"required qualifications",1),
("qualified","adj",["有資格的","合格的"],"qualified candidate",1),
("recruit","v",["招募"],"recruit new talent",1),
("recruitment","n",["招募"],"recruitment drive",1),
("redundancy","n",["裁員","冗餘"],"face redundancy",2),
("reference","n",["推薦信","參考"],"professional reference",1),
("relocate","v",["搬遷","調職"],"relocate for work",1),
("report","v",["報告","回報"],"report to a supervisor",1),
("resign","v",["辭職"],"resign voluntarily",1),
("resume","n",["履歷"],"submit a resume",1),
("retain","v",["留住","保留"],"retain talent",1),
("retire","v",["退休"],"retire from work",1),
("salary","n",["薪資"],"competitive salary",1),
("screen","v",["篩選","檢查"],"screen applicants",1),
("seniority","n",["年資","資深"],"based on seniority",2),
("shift","n",["班次","輪班"],"night shift",1),
("shortlist","v",["列入候選名單"],"shortlist candidates",2),
("skill","n",["技能","能力"],"technical skill",1),
("staff","n",["員工","職員"],"staff meeting",1),
("stipend","n",["津貼","補助"],"monthly stipend",2),
("subordinate","n",["下屬"],"manage subordinates",2),
("supervise","v",["監督","指導"],"supervise employees",1),
("supervisor","n",["主管"],"direct supervisor",1),
("talent","n",["人才"],"talent acquisition",1),
("tenure","n",["任期","在職期間"],"long tenure",2),
("terminate","v",["終止","解僱"],"terminate employment",2),
("termination","n",["終止","解僱"],"contract termination",2),
("trainee","n",["受訓者"],"management trainee",1),
("training","n",["訓練","培訓"],"training program",1),
("transfer","v",["調動","轉調"],"transfer to another office",1),
("turnover","n",["人員流動率"],"high turnover rate",1),
("vacancy","n",["空缺","職缺"],"fill a vacancy",1),
("volunteer","n",["志願者"],"office volunteer",1),
("wage","n",["工資"],"hourly wage",1),
("welfare","n",["福利"],"employee welfare",1),
("workforce","n",["勞動力"],"skilled workforce",1),
("workload","n",["工作量"],"heavy workload",1),
],
"cat05": [
("assemble","v",["組裝","裝配"],"assemble parts",1),
("assembly","n",["組裝","裝配"],"assembly line",1),
("automate","v",["自動化"],"automate production",2),
("automation","n",["自動化"],"factory automation",2),
("batch","n",["批次","一批"],"production batch",1),
("blueprint","n",["藍圖","設計圖"],"product blueprint",2),
("calibrate","v",["校準","調整"],"calibrate equipment",2),
("capacity","n",["產能","容量"],"production capacity",1),
("certify","v",["認證","證明"],"certify quality",2),
("component","n",["零件","組件"],"electronic component",1),
("conform","v",["符合","遵循"],"conform to standards",2),
("consistency","n",["一致性"],"product consistency",1),
("constraint","n",["限制","制約"],"production constraint",2),
("contaminate","v",["污染","汙染"],"contaminate products",2),
("control","n",["控制","管控"],"quality control",1),
("conveyor","n",["輸送帶"],"conveyor belt",2),
("craft","v",["製作","精製"],"craft by hand",1),
("customize","v",["客製化"],"customize products",1),
("defect","n",["缺陷","瑕疵"],"product defect",1),
("defective","adj",["有缺陷的"],"defective item",1),
("deliver","v",["交付"],"deliver on schedule",1),
("demand","n",["需求"],"meet demand",1),
("design","v",["設計"],"design a product",1),
("detect","v",["偵測","發現"],"detect defects",1),
("develop","v",["開發"],"develop products",1),
("device","n",["裝置","設備"],"electronic device",1),
("diagnose","v",["診斷","判斷"],"diagnose a problem",2),
("dimension","n",["尺寸","維度"],"product dimensions",2),
("discard","v",["丟棄","廢棄"],"discard waste",1),
("dispatch","v",["發送","派遣"],"dispatch goods",2),
("downtime","n",["停機時間"],"minimize downtime",1),
("durable","adj",["耐用的"],"durable material",1),
("efficiency","n",["效率"],"production efficiency",1),
("emission","n",["排放"],"carbon emission",2),
("engineer","n",["工程師"],"quality engineer",1),
("engineering","n",["工程","工程學"],"industrial engineering",1),
("enhance","v",["提升","增強"],"enhance quality",1),
("environment","n",["環境"],"work environment",1),
("equipment","n",["設備","裝備"],"production equipment",1),
("error","n",["錯誤","誤差"],"margin of error",1),
("evaluate","v",["評估"],"evaluate quality",1),
("examine","v",["檢查","考查"],"examine samples",1),
("exceed","v",["超過"],"exceed standards",1),
("fabricate","v",["製造","加工"],"fabricate parts",2),
("facility","n",["設施","廠房"],"manufacturing facility",1),
("fault","n",["故障","缺陷"],"product fault",1),
("feasibility","n",["可行性"],"feasibility study",2),
("flaw","n",["瑕疵","缺陷"],"design flaw",1),
("forklift","n",["堆高機"],"operate a forklift",1),
("gauge","n",["量規","計量器"],"pressure gauge",2),
("generate","v",["產生","發電"],"generate power",1),
("hazard","n",["危害","危險"],"safety hazard",1),
("implement","v",["實施"],"implement controls",1),
("improve","v",["改善","提升"],"improve quality",1),
("improvement","n",["改善","提升"],"continuous improvement",1),
("industrial","adj",["工業的"],"industrial output",1),
("innovate","v",["創新"],"innovate processes",2),
("inspect","v",["檢查","巡檢"],"inspect products",1),
("inspection","n",["檢查","巡檢"],"quality inspection",1),
("install","v",["安裝"],"install equipment",1),
("installation","n",["安裝","裝設"],"equipment installation",1),
("instrument","n",["儀器","工具"],"measuring instrument",1),
("inventory","n",["庫存"],"inventory control",1),
("labeling","n",["標籤","標示"],"product labeling",1),
("lean","adj",["精實的"],"lean manufacturing",2),
("line","n",["生產線"],"production line",1),
("machinery","n",["機器","機械"],"heavy machinery",1),
("maintain","v",["維護"],"maintain equipment",1),
("maintenance","n",["維護","保養"],"preventive maintenance",1),
("malfunction","n",["故障","失靈"],"equipment malfunction",1),
("manual","n",["手冊","說明書"],"operation manual",1),
("manufacture","v",["製造","生產"],"manufacture goods",1),
("material","n",["材料","原料"],"raw material",1),
("mechanism","n",["機制","機構"],"safety mechanism",2),
("modify","v",["修改","改良"],"modify a design",1),
("monitor","v",["監控"],"monitor quality",1),
("obsolete","adj",["過時的","淘汰的"],"obsolete equipment",2),
("operate","v",["操作","運轉"],"operate machinery",1),
("operator","n",["操作員"],"machine operator",1),
("optimize","v",["最佳化"],"optimize output",2),
("output","n",["產出","產量"],"daily output",1),
("overhaul","v",["大修","徹底改革"],"overhaul equipment",2),
("packaging","n",["包裝"],"product packaging",1),
("part","n",["零件","部件"],"spare part",1),
("patent","n",["專利"],"file a patent",2),
("perform","v",["執行","表現"],"perform tests",1),
("pilot","adj",["試驗的"],"pilot program",2),
("plant","n",["工廠"],"manufacturing plant",1),
("precision","n",["精確","精密"],"high precision",2),
("procedure","n",["程序","步驟"],"safety procedure",1),
("process","n",["製程","流程"],"production process",1),
("produce","v",["生產"],"produce goods",1),
("production","n",["生產","產量"],"mass production",1),
("productive","adj",["有生產力的"],"productive shift",1),
("productivity","n",["生產力"],"increase productivity",1),
("prototype","n",["原型","樣品"],"build a prototype",2),
("quality","n",["品質"],"quality assurance",1),
("recall","v",["召回"],"recall a product",1),
("recycle","v",["回收","再利用"],"recycle materials",1),
("refine","v",["精煉","改進"],"refine a process",2),
("regulate","v",["規範","管制"],"regulate production",2),
("reject","v",["拒絕","退回"],"reject defective items",1),
("reliability","n",["可靠性"],"product reliability",1),
("reliable","adj",["可靠的"],"reliable equipment",1),
("repair","v",["修理","維修"],"repair machinery",1),
("replace","v",["替換","更換"],"replace a part",1),
("replacement","n",["替換","更換"],"part replacement",1),
("require","v",["需要","要求"],"require inspection",1),
("requirement","n",["要求","規格"],"safety requirements",1),
("safety","n",["安全"],"safety standards",1),
("sample","n",["樣品","樣本"],"product sample",1),
("schedule","n",["排程","時程"],"production schedule",1),
("shift","n",["班次","輪班"],"day shift",1),
("shortage","n",["短缺","不足"],"material shortage",1),
("specification","n",["規格","規範"],"technical specifications",1),
("standard","n",["標準","規範"],"industry standard",1),
("standardize","v",["標準化"],"standardize processes",2),
("streamline","v",["精簡","簡化"],"streamline production",2),
("supervise","v",["監督"],"supervise workers",1),
("supply","n",["供應"],"supply chain",1),
("sustainable","adj",["可持續的"],"sustainable manufacturing",1),
("technique","n",["技術","方法"],"production technique",1),
("technology","n",["技術","科技"],"manufacturing technology",1),
("test","v",["測試","檢驗"],"test products",1),
("tolerance","n",["公差","容許值"],"manufacturing tolerance",2),
("tool","n",["工具"],"production tool",1),
("trace","v",["追溯","追蹤"],"trace a defect",2),
("upgrade","v",["升級"],"upgrade equipment",1),
("utilization","n",["利用率"],"capacity utilization",2),
("validate","v",["驗證"],"validate results",2),
("verification","n",["驗證","確認"],"quality verification",2),
("warehouse","n",["倉庫"],"storage warehouse",1),
("warranty","n",["保固"],"product warranty",1),
("waste","n",["廢物","浪費"],"reduce waste",1),
("workflow","n",["工作流程"],"efficient workflow",1),
("yield","n",["產量","良率"],"production yield",2),
],
}
