"""Cross-category TOEIC general vocabulary - everyday business English"""
WORDS_GENERAL = {
"cat01": [
# General high-frequency words useful in all TOEIC contexts
("abandon","v",["放棄","拋棄"],"abandon a plan",1),
("abbreviate","v",["縮寫","簡稱"],"abbreviate a term",2),
("ability","n",["能力"],"natural ability",1),
("abnormal","adj",["異常的"],"abnormal behavior",1),
("abolish","v",["廢除"],"abolish a rule",2),
("abruptly","adv",["突然地"],"abruptly ended",2),
("absence","n",["缺席","缺乏"],"leave of absence",1),
("absorb","v",["吸收","理解"],"absorb information",1),
("abstain","v",["棄權","戒除"],"abstain from voting",2),
("abuse","n",["濫用","虐待"],"abuse of power",2),
("accede","v",["同意","加入"],"accede to demands",3),
("accelerate","v",["加速"],"accelerate progress",2),
("accept","v",["接受"],"accept a proposal",1),
("acceptance","n",["接受","錄取"],"gain acceptance",1),
("accomplish","v",["完成"],"accomplish tasks",1),
("accordance","n",["依照","符合"],"in accordance with",1),
("according","adv",["根據"],"according to reports",1),
("account","n",["帳戶","說明"],"take into account",1),
("accurate","adj",["準確的"],"accurate data",1),
("accuse","v",["指控","控告"],"accuse of fraud",2),
("accustom","v",["使習慣"],"accustom to change",2),
("acquaintance","n",["熟人","認識"],"business acquaintance",1),
("acquire","v",["取得"],"acquire skills",2),
("actual","adj",["實際的"],"actual results",1),
("actually","adv",["實際上"],"actually happened",1),
("additionally","adv",["此外"],"additionally mentioned",1),
("address","v",["解決","處理"],"address concerns",1),
("adjacent","adj",["相鄰的"],"adjacent offices",1),
("admire","v",["欽佩","讚賞"],"admire leadership",1),
("admission","n",["入場","承認"],"free admission",1),
("admit","v",["承認","允許進入"],"admit mistakes",1),
("adverse","adj",["不利的"],"adverse impact",2),
("advertise","v",["廣告","宣傳"],"advertise a position",1),
("affordable","adj",["負擔得起的"],"affordable price",1),
("afterward","adv",["之後"],"discussed afterward",1),
("aggregate","adj",["總計的"],"aggregate amount",2),
("agree","v",["同意"],"agree on terms",1),
("ahead","adv",["在前方","提前"],"plan ahead",1),
("allocate","v",["分配"],"allocate budget",2),
("allow","v",["允許"],"allow access",1),
("alter","v",["改變","修改"],"alter plans",1),
("alteration","n",["改變","修改"],"make alterations",1),
("alternative","n",["替代方案"],"viable alternative",1),
("amount","n",["金額","數量"],"total amount",1),
("announcement","n",["公告"],"make an announcement",1),
("anonymous","adj",["匿名的"],"anonymous survey",1),
("anticipation","n",["預期","期待"],"in anticipation of",1),
("apologize","v",["道歉"],"apologize sincerely",1),
("apology","n",["道歉"],"formal apology",1),
("apparatus","n",["器具","機構"],"measuring apparatus",2),
("apparently","adv",["顯然地"],"apparently successful",1),
("appeal","v",["呼籲","上訴"],"appeal a decision",1),
("appear","v",["出現","似乎"],"appear qualified",1),
("appearance","n",["外觀","出席"],"professional appearance",1),
("apply","v",["申請","應用"],"apply for a position",1),
("appoint","v",["任命"],"appoint a manager",2),
("appreciate","v",["感激","理解"],"appreciate support",1),
("appreciation","n",["感謝","升值"],"show appreciation",1),
("apprentice","n",["學徒"],"train an apprentice",1),
("appropriate","adj",["適當的"],"appropriate action",1),
("appropriately","adv",["適當地"],"respond appropriately",1),
("approximately","adv",["大約"],"approximately ten",1),
("arise","v",["出現","發生"],"issues arise",1),
("arrangement","n",["安排"],"make arrangements",1),
("assemble","v",["組裝","集合"],"assemble a team",1),
("assertion","n",["斷言","主張"],"confident assertion",2),
("asset","n",["資產","優勢"],"valuable asset",1),
("association","n",["協會","聯繫"],"trade association",1),
("assortment","n",["各種各樣"],"wide assortment",1),
("assumption","n",["假設"],"basic assumption",1),
("at once","adv",["立即","同時"],"respond at once",1),
("atmosphere","n",["氣氛","環境"],"work atmosphere",1),
("attachment","n",["附件","依附"],"email attachment",1),
("attain","v",["達到"],"attain goals",2),
("attendance","n",["出席","出勤"],"perfect attendance",1),
("attention","n",["注意力"],"pay attention",1),
("attractive","adj",["有吸引力的"],"attractive offer",1),
("attribute","n",["特質","歸因"],"positive attribute",1),
("authentic","adj",["真實的","正宗的"],"authentic brand",1),
("authority","n",["權力","當局"],"local authority",1),
("automatic","adj",["自動的"],"automatic renewal",1),
("automatically","adv",["自動地"],"automatically processed",1),
("available","adj",["可用的"],"readily available",1),
("average","adj",["平均的"],"above average",1),
("avoid","v",["避免"],"avoid delays",1),
("aware","adj",["知道的","意識到的"],"fully aware",1),
("awareness","n",["意識","認知"],"raise awareness",1),
("awkward","adj",["尷尬的","笨拙的"],"awkward situation",1),
("background","n",["背景"],"professional background",1),
("balance","n",["平衡","餘額"],"maintain balance",1),
("barely","adv",["幾乎不"],"barely sufficient",1),
("bargain","n",["交易","特價"],"good bargain",1),
("barrier","n",["障礙","壁壘"],"trade barrier",1),
("basis","n",["基礎","根據"],"on a regular basis",1),
("bear","v",["承擔","忍受"],"bear responsibility",1),
("behalf","n",["代表"],"on behalf of",1),
("believe","v",["相信","認為"],"firmly believe",1),
("below","adv",["在...以下"],"listed below",1),
("besides","adv",["此外"],"besides that",1),
("bias","n",["偏見","偏差"],"reduce bias",2),
("bind","v",["約束","綁定"],"legally bound",2),
("bold","adj",["大膽的"],"bold decision",1),
("border","n",["邊界","界線"],"cross borders",1),
("bound","adj",["一定的","受約束的"],"legally bound",1),
("breakthrough","n",["突破"],"major breakthrough",1),
("briefly","adv",["簡短地"],"briefly explain",1),
("burden","n",["負擔"],"financial burden",1),
("capable","adj",["有能力的"],"highly capable",1),
("caution","n",["謹慎","警告"],"exercise caution",1),
("cease","v",["停止"],"cease production",2),
("certain","adj",["確定的","某些"],"certain conditions",1),
("certification","n",["認證"],"quality certification",1),
("circumstance","n",["情況","環境"],"under the circumstances",1),
("cite","v",["引用","引述"],"cite examples",1),
("civilian","n",["平民"],"civilian sector",2),
("claim","v",["聲稱","索賠"],"claim compensation",1),
("clutch","adj",["關鍵的"],"clutch performance",2),
("coherent","adj",["連貫的","一致的"],"coherent plan",2),
("coincide","v",["同時發生"],"coincide with",2),
("collapse","v",["崩潰","倒塌"],"market collapse",2),
("combat","v",["對抗","打擊"],"combat fraud",2),
("combine","v",["結合"],"combine efforts",1),
("commit","v",["承諾","犯下"],"commit resources",1),
("common","adj",["普遍的","常見的"],"common practice",1),
("communal","adj",["公共的","共有的"],"communal area",2),
("comparable","adj",["可比較的"],"comparable data",1),
("comparison","n",["比較"],"in comparison",1),
("compel","v",["迫使"],"compel action",2),
("compensate","v",["補償"],"compensate employees",2),
("complement","n",["補充"],"perfect complement",2),
("complete","v",["完成"],"complete a task",1),
("completion","n",["完成"],"upon completion",1),
("complicated","adj",["複雜的"],"complicated process",1),
("comply","v",["遵守"],"comply with rules",2),
("composition","n",["組成","構成"],"team composition",2),
("concept","n",["概念"],"key concept",1),
("concern","v",["關心","涉及"],"primarily concerned",1),
("concrete","adj",["具體的"],"concrete plan",1),
("condition","n",["條件","狀況"],"working conditions",1),
("confer","v",["商議","授予"],"confer with peers",2),
("confidence","n",["信心","信任"],"build confidence",1),
("confident","adj",["有信心的"],"remain confident",1),
("confine","v",["限制"],"confine to area",2),
("conflict","v",["衝突"],"conflict with schedule",1),
("conform","v",["遵從","符合"],"conform to standards",2),
("confront","v",["面對"],"confront issues",1),
("connect","v",["連結"],"connect with clients",1),
("connection","n",["連結","關係"],"business connection",1),
("consciously","adv",["有意識地"],"consciously decide",1),
("consensus","n",["共識"],"build consensus",2),
("consent","v",["同意"],"consent to terms",1),
("conserve","v",["節約","保護"],"conserve resources",2),
("considerable","adj",["相當大的"],"considerable growth",1),
("constitute","v",["構成"],"constitute a majority",2),
("constraint","n",["限制","約束"],"budget constraint",2),
("construct","v",["建造","構建"],"construct a plan",1),
("consume","v",["消費","消耗"],"consume resources",1),
("consumer","n",["消費者"],"target consumer",1),
("contain","v",["包含","容納"],"contain information",1),
("contaminate","v",["污染"],"contaminate products",2),
("contend","v",["競爭","主張"],"contend for position",2),
("contention","n",["爭論","觀點"],"point of contention",2),
("contest","v",["質疑","競爭"],"contest a decision",2),
("context","n",["背景","環境"],"business context",1),
("continually","adv",["不斷地"],"continually improving",1),
("continuous","adj",["持續的"],"continuous improvement",1),
("continuously","adv",["持續不斷地"],"continuously monitored",1),
("contradict","v",["矛盾","反駁"],"contradict evidence",2),
("contrary","adj",["相反的"],"contrary to expectations",1),
("contrast","n",["對比"],"stark contrast",1),
("controversy","n",["爭議"],"avoid controversy",2),
("convenient","adj",["方便的"],"convenient location",1),
("conveniently","adv",["方便地"],"conveniently located",1),
("conventional","adj",["傳統的"],"conventional method",1),
("core","n",["核心"],"core business",1),
("correct","v",["糾正"],"correct an error",1),
("costly","adj",["代價高的"],"costly mistake",1),
("counterpart","n",["對應者"],"foreign counterpart",2),
("countless","adj",["無數的"],"countless opportunities",1),
("couple","n",["幾個","一對"],"a couple of",1),
("coupled","adj",["結合的"],"coupled with",1),
("courteous","adj",["禮貌的"],"courteous manner",1),
("coverage","n",["覆蓋","報導"],"media coverage",1),
("creative","adj",["創意的"],"creative solution",1),
("creatively","adv",["有創意地"],"creatively designed",1),
("creativity","n",["創意"],"foster creativity",1),
("critical","adj",["關鍵的","批判的"],"critical factor",1),
("critically","adv",["關鍵地"],"critically important",1),
("criticism","n",["批評","指責"],"constructive criticism",1),
("criticize","v",["批評"],"unfairly criticized",1),
("current","adj",["目前的","現行的"],"current status",1),
("currently","adv",["目前"],"currently available",1),
("customary","adj",["慣例的"],"customary practice",2),
("deliberate","v",["深思熟慮"],"deliberate carefully",2),
("delicate","adj",["微妙的","精細的"],"delicate matter",1),
("demand","v",["要求"],"strongly demand",1),
("denial","n",["否認","拒絕"],"issue a denial",2),
("denote","v",["表示","指稱"],"denote importance",2),
("dense","adj",["密集的"],"dense population",1),
("depart","v",["離開"],"depart from policy",1),
("departure","n",["離開","偏離"],"a departure from",1),
("dependent","adj",["依賴的"],"dependent on funding",1),
("depict","v",["描繪","描述"],"depict a scenario",2),
("deposit","n",["存款","押金"],"security deposit",1),
("deserve","v",["值得"],"deserve recognition",1),
("designate","v",["指定"],"designate a successor",2),
("desire","n",["渴望"],"strong desire",1),
("desktop","n",["桌面","桌上型電腦"],"desktop computer",1),
("despite","prep",["儘管"],"despite challenges",1),
("destination","n",["目的地"],"final destination",1),
("detail","n",["細節"],"pay attention to detail",1),
("detect","v",["檢測","發現"],"detect problems",1),
("deteriorate","v",["惡化"],"conditions deteriorate",2),
("detriment","n",["損害","不利"],"to the detriment of",2),
("devise","v",["設計","想出"],"devise a plan",2),
("devote","v",["奉獻","致力"],"devote time to",1),
("differentiate","v",["區分"],"differentiate products",2),
("dilemma","n",["困境","兩難"],"face a dilemma",1),
("dimension","n",["層面","維度"],"new dimension",2),
("diminish","v",["減少"],"gradually diminish",2),
],
}
