"""Additional TOEIC vocabulary data - Categories 08-15"""
WORDS_EXTRA_3 = {
"cat08": [
("accommodate","v",["容納","配合"],"accommodate guests",1),
("acknowledge","v",["確認","承認"],"acknowledge receipt",1),
("adjacent","adj",["鄰近的"],"adjacent office",1),
("agenda","n",["議程"],"set an agenda",1),
("arrange","v",["安排","佈置"],"arrange a meeting",1),
("arrangement","n",["安排","佈置"],"make arrangements",1),
("attach","v",["附上","附加"],"attach a file",1),
("attachment","n",["附件"],"email attachment",1),
("attend","v",["參加","出席"],"attend a meeting",1),
("attendance","n",["出席","出勤"],"check attendance",1),
("authorize","v",["授權"],"authorize access",2),
("bin","n",["垃圾桶"],"recycling bin",1),
("binder","n",["活頁夾"],"document binder",1),
("boardroom","n",["會議室"],"boardroom meeting",1),
("booklet","n",["小冊子"],"information booklet",1),
("cabinet","n",["檔案櫃","櫥櫃"],"filing cabinet",1),
("calendar","n",["行事曆"],"office calendar",1),
("cancel","v",["取消"],"cancel a meeting",1),
("chair","n",["椅子","主席"],"office chair",1),
("clerk","n",["職員","辦事員"],"office clerk",1),
("clipboard","n",["剪貼簿","文件夾板"],"use a clipboard",1),
("collate","v",["整理","校對"],"collate documents",2),
("commute","v",["通勤"],"commute to work",1),
("compartment","n",["隔間","車廂"],"storage compartment",1),
("compile","v",["彙編","整理"],"compile reports",2),
("confirm","v",["確認"],"confirm attendance",1),
("coordinate","v",["協調"],"coordinate schedules",1),
("copier","n",["影印機"],"office copier",1),
("copy","v",["複印","複製"],"copy a document",1),
("correspond","v",["通信","對應"],"correspond via email",2),
("correspondence","n",["信件","通訊"],"official correspondence",2),
("cubicle","n",["隔間","小辦公室"],"office cubicle",1),
("deadline","n",["截止日期"],"meet a deadline",1),
("delegate","v",["委派"],"delegate work",2),
("deliver","v",["遞送","交付"],"deliver a package",1),
("deposit","v",["存放","寄存"],"deposit documents",1),
("desk","n",["辦公桌"],"reception desk",1),
("dispatch","v",["發送"],"dispatch a letter",2),
("distribute","v",["分發"],"distribute copies",1),
("document","n",["文件"],"official document",1),
("draft","n",["草稿"],"first draft",1),
("duplicate","v",["複製"],"duplicate a file",1),
("efficient","adj",["高效率的"],"efficient workflow",1),
("elevator","n",["電梯"],"take the elevator",1),
("envelope","n",["信封"],"mail an envelope",1),
("equipment","n",["設備"],"office equipment",1),
("errand","n",["差事","跑腿"],"run an errand",1),
("essential","adj",["必要的"],"essential supplies",1),
("estimate","n",["估計"],"cost estimate",1),
("extension","n",["分機號碼"],"phone extension",1),
("fax","n",["傳真"],"send a fax",1),
("file","v",["歸檔","建檔"],"file documents",1),
("folder","n",["資料夾"],"file folder",1),
("form","n",["表格"],"fill out a form",1),
("forward","v",["轉寄","轉交"],"forward an email",1),
("furnish","v",["佈置","提供"],"furnish an office",1),
("furniture","n",["傢具"],"office furniture",1),
("hallway","n",["走廊"],"office hallway",1),
("handbook","n",["手冊"],"employee handbook",1),
("headquarters","n",["總部"],"company headquarters",1),
("inbox","n",["收件匣"],"check inbox",1),
("index","n",["索引"],"file index",1),
("inform","v",["通知"],"inform the team",1),
("inquiry","n",["詢問"],"general inquiry",1),
("intercom","n",["對講機"],"office intercom",1),
("inventory","n",["清單","盤點"],"office inventory",1),
("itinerary","n",["行程表"],"travel itinerary",1),
("label","n",["標籤"],"address label",1),
("laminate","v",["護貝"],"laminate a card",1),
("lease","n",["租約"],"office lease",1),
("letterhead","n",["信頭","信箋"],"company letterhead",2),
("lobby","n",["大廳"],"building lobby",1),
("log","v",["記錄"],"log activities",1),
("mail","n",["郵件"],"incoming mail",1),
("mailbox","n",["信箱"],"office mailbox",1),
("maintenance","n",["維護"],"building maintenance",1),
("memo","n",["備忘錄"],"internal memo",1),
("memorandum","n",["備忘錄"],"official memorandum",2),
("minutes","n",["會議紀錄"],"meeting minutes",1),
("monitor","n",["螢幕"],"computer monitor",1),
("notify","v",["通知"],"notify employees",1),
("office","n",["辦公室"],"main office",1),
("organize","v",["整理","組織"],"organize files",1),
("outbox","n",["寄件匣"],"email outbox",1),
("overhead","n",["開支"],"overhead costs",2),
("paper","n",["紙張","文件"],"copy paper",1),
("paperwork","n",["文書工作"],"complete paperwork",1),
("partition","n",["隔板","隔間"],"office partition",1),
("pending","adj",["待處理的"],"pending tasks",2),
("photocopy","v",["影印"],"photocopy documents",1),
("postpone","v",["延期","推遲"],"postpone a meeting",1),
("premises","n",["場所","辦公場地"],"office premises",2),
("print","v",["列印"],"print a document",1),
("printer","n",["印表機"],"laser printer",1),
("priority","n",["優先事項"],"top priority",1),
("procedure","n",["程序"],"office procedure",1),
("proofread","v",["校對"],"proofread a letter",1),
("receptionist","n",["接待員"],"front desk receptionist",1),
("record","v",["記錄"],"record minutes",1),
("redirect","v",["轉寄","重新導向"],"redirect mail",1),
("reference","n",["參考"],"use as reference",1),
("register","v",["登記"],"register visitors",1),
("relocate","v",["搬遷"],"relocate the office",1),
("reminder","n",["提醒"],"send a reminder",1),
("renovate","v",["翻新","整修"],"renovate the office",1),
("repair","v",["修理"],"repair equipment",1),
("replace","v",["替換"],"replace supplies",1),
("reschedule","v",["重新安排"],"reschedule a meeting",1),
("reserve","v",["預約","預留"],"reserve a room",1),
("retrieve","v",["取回","找回"],"retrieve a file",2),
("scan","v",["掃描"],"scan a document",1),
("schedule","v",["安排","排程"],"schedule an appointment",1),
("shred","v",["碎紙","銷毀"],"shred documents",1),
("sign","v",["簽署","簽名"],"sign a document",1),
("signature","n",["簽名"],"digital signature",1),
("sort","v",["分類","整理"],"sort mail",1),
("stationery","n",["文具"],"office stationery",1),
("storage","n",["儲存","倉儲"],"file storage",1),
("submit","v",["提交"],"submit paperwork",1),
("subscribe","v",["訂閱"],"subscribe to a newsletter",1),
("suite","n",["套房","套間"],"office suite",1),
("supervisor","n",["主管"],"office supervisor",1),
("supply","n",["用品","供應"],"office supplies",1),
("switch","v",["切換","轉換"],"switch offices",1),
("telecommunicate","v",["遠距通訊"],"telecommunicate daily",2),
("tenant","n",["租戶"],"office tenant",1),
("tidy","v",["整理","打掃"],"tidy the workspace",1),
("toner","n",["碳粉"],"printer toner",1),
("transfer","v",["轉接","轉移"],"transfer a call",1),
("utility","n",["公用事業"],"utility bill",1),
("vacancy","n",["空位","職缺"],"office vacancy",1),
("ventilation","n",["通風"],"office ventilation",2),
("voicemail","n",["語音信箱"],"leave a voicemail",1),
("workspace","n",["工作空間"],"shared workspace",1),
],
"cat09": [
("aboard","adv",["在船上","在飛機上"],"go aboard",1),
("accommodation","n",["住宿"],"hotel accommodation",1),
("airline","n",["航空公司"],"major airline",1),
("airport","n",["機場"],"international airport",1),
("aisle","n",["走道"],"aisle seat",1),
("ambassador","n",["大使"],"trade ambassador",2),
("arrange","v",["安排"],"arrange travel",1),
("arrival","n",["到達"],"arrival time",1),
("baggage","n",["行李"],"baggage claim",1),
("board","v",["登機","登船"],"board a plane",1),
("boarding","n",["登機"],"boarding pass",1),
("book","v",["預訂"],"book a flight",1),
("booking","n",["預訂"],"hotel booking",1),
("border","n",["邊界","國境"],"cross the border",1),
("cabin","n",["機艙","客艙"],"first-class cabin",1),
("cancel","v",["取消"],"cancel a reservation",1),
("cancellation","n",["取消"],"flight cancellation",1),
("cargo","n",["貨物"],"air cargo",2),
("carrier","n",["運輸業者"],"freight carrier",2),
("charter","v",["包租","特許"],"charter a bus",2),
("check-in","n",["報到","辦理登機"],"check-in counter",1),
("checkout","n",["退房"],"checkout time",1),
("clearance","n",["清關","許可"],"customs clearance",2),
("commute","n",["通勤"],"daily commute",1),
("compartment","n",["車廂","隔間"],"luggage compartment",1),
("complimentary","adj",["免費的"],"complimentary breakfast",1),
("concierge","n",["禮賓","門房"],"hotel concierge",1),
("confirm","v",["確認"],"confirm reservation",1),
("congestion","n",["壅塞","擁擠"],"traffic congestion",1),
("connect","v",["轉接","連接"],"connecting flight",1),
("consignment","n",["託運","委託"],"consignment shipment",2),
("container","n",["貨櫃","容器"],"shipping container",1),
("cruise","n",["郵輪旅行"],"cruise ship",1),
("currency","n",["貨幣"],"foreign currency",1),
("customs","n",["海關"],"pass through customs",1),
("delay","n",["延誤"],"flight delay",1),
("depart","v",["出發","啟程"],"depart from",1),
("departure","n",["出發","啟程"],"departure gate",1),
("destination","n",["目的地"],"travel destination",1),
("detour","n",["繞路","迂迴"],"take a detour",1),
("dispatch","v",["發送","派遣"],"dispatch goods",2),
("dock","n",["碼頭"],"loading dock",1),
("domestic","adj",["國內的"],"domestic flight",1),
("driver","n",["司機","駕駛"],"taxi driver",1),
("duty-free","adj",["免稅的"],"duty-free shop",1),
("embark","v",["上船","登機"],"embark on a trip",2),
("embassy","n",["大使館"],"contact the embassy",1),
("excursion","n",["遠足","短途旅行"],"group excursion",2),
("expedition","n",["探險","遠征"],"business expedition",2),
("express","adj",["快速的","特快的"],"express delivery",1),
("fare","n",["票價","車資"],"bus fare",1),
("ferry","n",["渡輪"],"take a ferry",1),
("fleet","n",["車隊","船隊"],"delivery fleet",2),
("freight","n",["貨運","運費"],"freight charges",2),
("fuel","n",["燃料"],"fuel cost",1),
("gate","n",["登機門","大門"],"boarding gate",1),
("guide","n",["導遊","指南"],"tour guide",1),
("harbor","n",["港口"],"shipping harbor",1),
("hospitality","n",["款待","接待"],"hospitality industry",1),
("hotel","n",["旅館","飯店"],"hotel reservation",1),
("immigration","n",["移民","入境"],"immigration control",1),
("import","v",["進口"],"import goods",1),
("inn","n",["旅館","客棧"],"country inn",1),
("inspection","n",["檢查"],"customs inspection",1),
("insurance","n",["保險"],"travel insurance",1),
("international","adj",["國際的"],"international travel",1),
("itinerary","n",["行程"],"travel itinerary",1),
("jet","n",["噴射機"],"private jet",1),
("journey","n",["旅程"],"business journey",1),
("kilometer","n",["公里"],"distance in kilometers",1),
("landing","n",["降落","著陸"],"smooth landing",1),
("lane","n",["車道"],"fast lane",1),
("locomotive","n",["火車頭"],"diesel locomotive",2),
("lodging","n",["住宿"],"find lodging",1),
("luggage","n",["行李"],"carry-on luggage",1),
("manifest","n",["艙單","貨物清單"],"cargo manifest",2),
("mileage","n",["里程數"],"frequent flyer mileage",1),
("navigate","v",["導航"],"navigate the route",1),
("overbook","v",["超額預訂"],"overbook a flight",2),
("overseas","adj",["海外的"],"overseas trip",1),
("package","n",["包裹","套裝行程"],"vacation package",1),
("passenger","n",["乘客"],"airplane passenger",1),
("passport","n",["護照"],"valid passport",1),
("pier","n",["碼頭"],"cruise pier",1),
("port","n",["港口"],"major port",1),
("porter","n",["行李員"],"hotel porter",1),
("postpone","v",["延期"],"postpone a trip",1),
("railway","n",["鐵路"],"railway station",1),
("receipt","n",["收據"],"hotel receipt",1),
("reception","n",["接待","接待處"],"hotel reception",1),
("reroute","v",["改道","重新路線"],"reroute shipment",2),
("reservation","n",["預約","保留"],"dinner reservation",1),
("reserve","v",["預訂"],"reserve a table",1),
("resort","n",["度假村"],"beach resort",1),
("round-trip","adj",["來回的"],"round-trip ticket",1),
("route","n",["路線"],"delivery route",1),
("runway","n",["跑道"],"airport runway",1),
("schedule","n",["時刻表"],"train schedule",1),
("shipment","n",["出貨","運送"],"track a shipment",1),
("shuttle","n",["接駁車"],"airport shuttle",1),
("sightseeing","n",["觀光"],"go sightseeing",1),
("souvenir","n",["紀念品"],"buy souvenirs",1),
("suite","n",["套房"],"hotel suite",1),
("terminal","n",["航廈","終點站"],"airport terminal",1),
("ticket","n",["票","車票"],"one-way ticket",1),
("tourism","n",["觀光業"],"tourism industry",1),
("tourist","n",["觀光客"],"foreign tourist",1),
("trailer","n",["拖車"],"cargo trailer",2),
("transit","n",["運輸","過境"],"in transit",1),
("transport","v",["運輸","搬運"],"transport goods",1),
("transportation","n",["運輸","交通"],"public transportation",1),
("tray","n",["托盤"],"meal tray",1),
("trip","n",["旅行","出差"],"business trip",1),
("trunk","n",["後車廂","主幹線"],"car trunk",1),
("turbulence","n",["亂流"],"experience turbulence",1),
("upgrade","v",["升級"],"upgrade a seat",1),
("vacancy","n",["空房"],"room vacancy",1),
("valid","adj",["有效的"],"valid ticket",1),
("vehicle","n",["車輛"],"company vehicle",1),
("venue","n",["場地"],"event venue",1),
("visa","n",["簽證"],"apply for a visa",1),
("voyage","n",["航行","旅途"],"maiden voyage",2),
("warehouse","n",["倉庫"],"storage warehouse",1),
],
"cat10": [
("administer","v",["施用","管理"],"administer medicine",2),
("ailment","n",["疾病","小毛病"],"common ailment",2),
("allergic","adj",["過敏的"],"allergic reaction",1),
("allergy","n",["過敏"],"food allergy",1),
("ambulance","n",["救護車"],"call an ambulance",1),
("appointment","n",["掛號","預約"],"doctor's appointment",1),
("bandage","n",["繃帶"],"apply a bandage",1),
("benefit","n",["福利","利益"],"health benefit",1),
("blood","n",["血液"],"blood test",1),
("checkup","n",["健康檢查"],"annual checkup",1),
("chronic","adj",["慢性的"],"chronic disease",2),
("claim","n",["理賠"],"insurance claim",1),
("clinic","n",["診所"],"medical clinic",1),
("condition","n",["病況","狀況"],"medical condition",1),
("conscious","adj",["有意識的"],"remain conscious",1),
("consent","n",["同意","許可"],"patient consent",1),
("consultation","n",["諮詢","看診"],"medical consultation",2),
("contagious","adj",["傳染的"],"contagious disease",2),
("coverage","n",["保障範圍"],"insurance coverage",1),
("cure","n",["治療","療法"],"find a cure",1),
("deductible","n",["自付額"],"insurance deductible",2),
("dental","adj",["牙科的"],"dental care",1),
("dentist","n",["牙醫"],"visit the dentist",1),
("diagnose","v",["診斷"],"diagnose a condition",2),
("diagnosis","n",["診斷結果"],"medical diagnosis",2),
("diet","n",["飲食","節食"],"balanced diet",1),
("disability","n",["殘疾","失能"],"physical disability",2),
("discharge","v",["出院"],"discharge a patient",2),
("disease","n",["疾病"],"infectious disease",1),
("disorder","n",["失調","疾病"],"sleep disorder",2),
("dosage","n",["劑量"],"recommended dosage",2),
("dose","n",["劑量","一劑"],"daily dose",1),
("emergency","n",["緊急情況"],"medical emergency",1),
("enroll","v",["報名","加入"],"enroll in a plan",1),
("epidemic","n",["流行病"],"flu epidemic",2),
("examine","v",["檢查","診察"],"examine a patient",1),
("exercise","n",["運動"],"regular exercise",1),
("facility","n",["設施"],"medical facility",1),
("fatigue","n",["疲勞"],"chronic fatigue",2),
("fever","n",["發燒"],"high fever",1),
("fitness","n",["健身","體適能"],"fitness center",1),
("flu","n",["流感"],"seasonal flu",1),
("fracture","n",["骨折"],"bone fracture",1),
("hazard","n",["危害"],"health hazard",1),
("heal","v",["治癒","癒合"],"heal a wound",1),
("healthcare","n",["醫療保健"],"healthcare system",1),
("hygiene","n",["衛生"],"personal hygiene",1),
("immune","adj",["免疫的"],"immune system",2),
("immunize","v",["免疫接種"],"immunize children",2),
("impair","v",["損害","削弱"],"impair vision",2),
("infection","n",["感染"],"prevent infection",1),
("infirmary","n",["醫務室"],"school infirmary",2),
("injury","n",["傷害","受傷"],"workplace injury",1),
("inoculate","v",["接種"],"inoculate against flu",2),
("insure","v",["投保"],"insure employees",1),
("intake","n",["攝取量"],"calorie intake",1),
("intensive","adj",["加護的","密集的"],"intensive care",2),
("laboratory","n",["實驗室"],"medical laboratory",1),
("medical","adj",["醫療的"],"medical records",1),
("medication","n",["藥物"],"take medication",1),
("medicine","n",["醫學","藥物"],"practice medicine",1),
("mental","adj",["心理的","精神的"],"mental health",1),
("nurse","n",["護士"],"registered nurse",1),
("nutrition","n",["營養"],"proper nutrition",1),
("obesity","n",["肥胖"],"prevent obesity",2),
("operate","v",["動手術"],"operate on a patient",2),
("operation","n",["手術"],"surgical operation",1),
("optician","n",["驗光師","眼鏡師"],"visit an optician",1),
("organ","n",["器官"],"organ transplant",2),
("outpatient","n",["門診病人"],"outpatient care",2),
("pain","n",["疼痛"],"chest pain",1),
("paramedic","n",["急救人員"],"trained paramedic",2),
("patient","n",["病人","患者"],"hospital patient",1),
("pharmacy","n",["藥局"],"local pharmacy",1),
("physical","adj",["身體的"],"physical therapy",1),
("physician","n",["醫師"],"primary physician",1),
("policy","n",["保單","政策"],"health policy",1),
("practice","n",["診所","執業"],"medical practice",1),
("premium","n",["保費"],"monthly premium",2),
("prescribe","v",["開處方"],"prescribe medication",2),
("prescription","n",["處方"],"fill a prescription",1),
("prevention","n",["預防"],"disease prevention",1),
("procedure","n",["手術","程序"],"medical procedure",1),
("prognosis","n",["預後"],"positive prognosis",3),
("provider","n",["醫療提供者"],"healthcare provider",1),
("quarantine","n",["隔離"],"quarantine period",2),
("recover","v",["康復","恢復"],"recover from surgery",1),
("recovery","n",["康復","恢復"],"full recovery",1),
("referral","n",["轉介"],"specialist referral",1),
("rehabilitate","v",["復健","康復"],"rehabilitate a patient",2),
("remedy","n",["治療","藥方"],"home remedy",1),
("sanitary","adj",["衛生的"],"sanitary conditions",1),
("screening","n",["篩檢"],"cancer screening",1),
("specialist","n",["專科醫師"],"see a specialist",1),
("stress","n",["壓力"],"work-related stress",1),
("surgeon","n",["外科醫師"],"heart surgeon",1),
("surgery","n",["手術"],"undergo surgery",1),
("symptom","n",["症狀"],"common symptom",1),
("therapy","n",["治療","療法"],"physical therapy",1),
("treatment","n",["治療"],"medical treatment",1),
("vaccine","n",["疫苗"],"flu vaccine",1),
("vital","adj",["生命的","重要的"],"vital signs",1),
("ward","n",["病房"],"hospital ward",1),
("welfare","n",["福利","福祉"],"health welfare",1),
("wellness","n",["健康","養生"],"wellness program",1),
("wound","n",["傷口"],"treat a wound",1),
],
"cat11": [
("adjacent","adj",["鄰近的","毗鄰的"],"adjacent lot",1),
("appraisal","n",["估價"],"property appraisal",2),
("architect","n",["建築師"],"licensed architect",1),
("blueprint","n",["藍圖"],"construction blueprint",2),
("broker","n",["經紀人"],"real estate broker",1),
("building","n",["建築物"],"office building",1),
("cement","n",["水泥"],"pour cement",1),
("closing","n",["成交","過戶"],"closing date",2),
("commercial","adj",["商用的"],"commercial property",1),
("commission","n",["佣金"],"agent commission",2),
("comply","v",["遵守"],"comply with codes",2),
("concrete","n",["混凝土"],"reinforced concrete",1),
("condition","n",["狀況"],"property condition",1),
("construct","v",["建造","興建"],"construct a building",1),
("construction","n",["建設","施工"],"under construction",1),
("contractor","n",["承包商"],"general contractor",1),
("convert","v",["改建","轉換"],"convert a warehouse",2),
("crane","n",["起重機"],"construction crane",1),
("deadline","n",["截止日期"],"construction deadline",1),
("deed","n",["地契","產權證書"],"property deed",2),
("demolish","v",["拆除"],"demolish a building",2),
("demolition","n",["拆除"],"scheduled demolition",2),
("deposit","n",["訂金","押金"],"security deposit",1),
("depreciate","v",["折舊","貶值"],"property depreciates",2),
("design","v",["設計"],"design a building",1),
("develop","v",["開發"],"develop land",1),
("developer","n",["開發商"],"real estate developer",1),
("development","n",["開發案"],"residential development",1),
("dwelling","n",["住宅","住處"],"single-family dwelling",2),
("easement","n",["地役權"],"property easement",3),
("elevation","n",["立面圖","海拔"],"building elevation",2),
("equip","v",["配備"],"equip a building",1),
("erect","v",["建立","豎起"],"erect a structure",2),
("estate","n",["房產","不動產"],"real estate",1),
("estimate","n",["估價","估計"],"construction estimate",1),
("evacuate","v",["撤離","疏散"],"evacuate a building",1),
("evict","v",["驅逐"],"evict a tenant",2),
("excavate","v",["挖掘","開挖"],"excavate the site",2),
("expand","v",["擴展"],"expand a property",1),
("facility","n",["設施"],"recreational facility",1),
("fence","n",["圍欄"],"build a fence",1),
("floor","n",["樓層","地板"],"ground floor",1),
("foreclose","v",["查封","法拍"],"foreclose a mortgage",3),
("foundation","n",["地基","基礎"],"building foundation",1),
("furnish","v",["配備傢具"],"furnish an apartment",1),
("garage","n",["車庫"],"parking garage",1),
("hazard","n",["危害"],"fire hazard",1),
("house","v",["容納","安置"],"house equipment",1),
("housing","n",["住宅","住房"],"affordable housing",1),
("infrastructure","n",["基礎設施"],"city infrastructure",2),
("inspect","v",["檢查","巡視"],"inspect a property",1),
("inspection","n",["檢查"],"building inspection",1),
("install","v",["安裝"],"install plumbing",1),
("insulate","v",["隔熱","隔音"],"insulate walls",2),
("insulation","n",["隔熱","絕緣"],"wall insulation",2),
("interior","n",["室內"],"interior design",1),
("invest","v",["投資"],"invest in property",1),
("landlord","n",["房東"],"building landlord",1),
("landscape","v",["景觀美化"],"landscape the yard",1),
("lease","n",["租約"],"sign a lease",1),
("lien","n",["留置權"],"property lien",3),
("listing","n",["房源","上市"],"property listing",1),
("location","n",["地點","位置"],"prime location",1),
("loft","n",["閣樓"],"converted loft",1),
("lot","n",["地塊","地段"],"vacant lot",1),
("maintain","v",["維護"],"maintain property",1),
("maintenance","n",["維護","保養"],"building maintenance",1),
("mortgage","n",["房貸"],"apply for mortgage",1),
("negotiate","v",["議價","談判"],"negotiate rent",1),
("occupancy","n",["入住率","占用"],"full occupancy",2),
("occupy","v",["佔用","居住"],"occupy a unit",1),
("outskirts","n",["郊區"],"city outskirts",1),
("permit","n",["許可證"],"building permit",1),
("plan","n",["計畫","圖紙"],"floor plan",1),
("plumbing","n",["管線","水電"],"fix plumbing",1),
("premises","n",["場所","房產"],"business premises",2),
("property","n",["房產","物業"],"rental property",1),
("purchase","v",["購買"],"purchase a home",1),
("real estate","n",["不動產","房地產"],"real estate market",1),
("remodel","v",["改建","翻修"],"remodel a kitchen",1),
("renovate","v",["翻新","裝修"],"renovate a house",1),
("renovation","n",["翻新","裝修"],"home renovation",1),
("rent","v",["租賃"],"rent an apartment",1),
("rental","n",["租金","出租"],"rental agreement",1),
("reside","v",["居住"],"reside in a city",1),
("residence","n",["住所"],"private residence",1),
("residential","adj",["住宅的"],"residential area",1),
("scaffold","n",["鷹架"],"construction scaffold",2),
("site","n",["工地","場地"],"construction site",1),
("structure","n",["建築","結構"],"steel structure",1),
("subcontract","v",["分包","轉包"],"subcontract work",2),
("suburb","n",["郊區"],"quiet suburb",1),
("survey","n",["勘測","測量"],"land survey",1),
("tenant","n",["租戶","房客"],"commercial tenant",1),
("title","n",["產權","所有權"],"property title",2),
("township","n",["鄉鎮"],"local township",2),
("unit","n",["單位","房間"],"housing unit",1),
("upgrade","v",["升級","改良"],"upgrade facilities",1),
("utility","n",["水電費","公用事業"],"utility costs",1),
("vacant","adj",["空的","空置的"],"vacant property",1),
("value","n",["價值"],"property value",1),
("ventilation","n",["通風"],"proper ventilation",2),
("zone","n",["區域","地帶"],"residential zone",1),
("zoning","n",["分區","都市計劃"],"zoning regulation",2),
],
"cat12": [
("appetizer","n",["開胃菜"],"order an appetizer",1),
("aroma","n",["香氣","芳香"],"pleasant aroma",1),
("banquet","n",["宴會"],"company banquet",1),
("bartender","n",["調酒師"],"experienced bartender",1),
("beverage","n",["飲料"],"hot beverage",1),
("bistro","n",["小餐館"],"French bistro",1),
("booking","n",["預訂"],"table booking",1),
("brunch","n",["早午餐"],"Sunday brunch",1),
("buffet","n",["自助餐"],"breakfast buffet",1),
("busboy","n",["餐廳助手"],"hire a busboy",1),
("cafeteria","n",["自助餐廳"],"company cafeteria",1),
("capacity","n",["容量","座位數"],"seating capacity",1),
("catering","n",["外燴","餐飲服務"],"catering service",1),
("chef","n",["主廚"],"head chef",1),
("check","n",["帳單"],"pay the check",1),
("cocktail","n",["雞尾酒"],"cocktail party",1),
("complimentary","adj",["免費的"],"complimentary drink",1),
("condiment","n",["調味料"],"add condiments",1),
("consume","v",["食用","消費"],"consume food",1),
("course","n",["道菜"],"main course",1),
("cuisine","n",["料理","烹飪"],"local cuisine",1),
("deli","n",["熟食店"],"neighborhood deli",1),
("delicacy","n",["美味佳餚"],"local delicacy",2),
("deliver","v",["外送"],"deliver food",1),
("dessert","n",["甜點"],"order dessert",1),
("dine","v",["用餐"],"dine out",1),
("diner","n",["用餐者","小餐廳"],"regular diner",1),
("dining","n",["用餐","餐飲"],"fine dining",1),
("discount","n",["折扣"],"member discount",1),
("dish","n",["菜餚","餐盤"],"signature dish",1),
("entree","n",["主菜"],"choose an entree",1),
("establish","v",["設立"],"establish a restaurant",1),
("event","n",["活動"],"catering event",1),
("franchise","n",["加盟"],"franchise restaurant",2),
("garnish","v",["裝飾","點綴"],"garnish a dish",2),
("gourmet","adj",["美食的","精緻的"],"gourmet dining",1),
("gratuity","n",["小費"],"add gratuity",2),
("grill","v",["燒烤"],"grill steak",1),
("hospitality","n",["餐旅業","待客"],"hospitality management",1),
("host","n",["主持人","帶位者"],"restaurant host",1),
("ingredient","n",["食材","材料"],"fresh ingredients",1),
("inspect","v",["檢查"],"inspect a kitchen",1),
("kitchen","n",["廚房"],"commercial kitchen",1),
("manage","v",["管理","經營"],"manage a restaurant",1),
("manager","n",["經理"],"restaurant manager",1),
("meal","n",["餐","一餐"],"prepare a meal",1),
("menu","n",["菜單"],"dinner menu",1),
("organic","adj",["有機的"],"organic food",1),
("patron","n",["顧客","常客"],"regular patron",1),
("portion","n",["份量"],"generous portion",1),
("prepare","v",["準備","烹調"],"prepare food",1),
("preserve","v",["保存","醃漬"],"preserve food",1),
("provision","n",["供應","糧食"],"food provisions",2),
("recipe","n",["食譜"],"secret recipe",1),
("recommend","v",["推薦"],"recommend a dish",1),
("refreshment","n",["茶點","飲料"],"light refreshments",1),
("reservation","n",["預約"],"make a reservation",1),
("reserve","v",["預訂"],"reserve a table",1),
("restaurant","n",["餐廳"],"popular restaurant",1),
("review","n",["評論","評價"],"restaurant review",1),
("sanitation","n",["衛生"],"food sanitation",1),
("seasonal","adj",["季節性的"],"seasonal menu",1),
("serve","v",["供應","服務"],"serve customers",1),
("server","n",["服務生"],"experienced server",1),
("service","n",["服務"],"excellent service",1),
("specialize","v",["專攻","專精"],"specialize in seafood",1),
("specialty","n",["招牌菜","特色"],"house specialty",1),
("staff","n",["員工"],"kitchen staff",1),
("supply","v",["供應"],"supply ingredients",1),
("tip","n",["小費"],"leave a tip",1),
("utensil","n",["餐具","用具"],"cooking utensils",1),
("venue","n",["場地"],"event venue",1),
("waiter","n",["服務生"],"friendly waiter",1),
],
"cat13": [
("account","n",["帳戶"],"savings account",1),
("annual","adj",["年度的"],"annual rate",1),
("application","n",["申請"],"loan application",1),
("approve","v",["核准"],"approve a loan",1),
("asset","n",["資產"],"liquid asset",1),
("ATM","n",["自動提款機"],"nearby ATM",1),
("authorize","v",["授權"],"authorize a transaction",2),
("balance","n",["餘額"],"check balance",1),
("bank","n",["銀行"],"commercial bank",1),
("banking","n",["銀行業務"],"online banking",1),
("beneficiary","n",["受益人"],"name a beneficiary",2),
("bond","n",["債券"],"corporate bond",2),
("borrow","v",["借款"],"borrow from a bank",1),
("branch","n",["分行"],"local branch",1),
("capacity","n",["能力"],"lending capacity",2),
("capital","n",["資本"],"raise capital",2),
("certificate","n",["存單","證書"],"deposit certificate",1),
("check","n",["支票"],"cash a check",1),
("circulation","n",["流通"],"currency circulation",2),
("claim","n",["理賠"],"file a claim",1),
("collateral","n",["擔保品"],"loan collateral",2),
("commercial","adj",["商業的"],"commercial lending",1),
("compound","adj",["複利的"],"compound interest",2),
("consolidate","v",["整合"],"consolidate debts",2),
("consumer","n",["消費者"],"consumer banking",1),
("coverage","n",["承保範圍"],"full coverage",1),
("credit","n",["信用","貸方"],"credit score",1),
("currency","n",["貨幣"],"digital currency",1),
("debit","n",["借方"],"debit transaction",1),
("default","v",["違約"],"default on payment",2),
("deferment","n",["延期"],"loan deferment",2),
("deposit","v",["存款"],"deposit money",1),
("digital","adj",["數位的"],"digital banking",1),
("disburse","v",["支付","撥款"],"disburse funds",2),
("dividend","n",["股利"],"quarterly dividend",2),
("eligible","adj",["符合資格的"],"eligible for a loan",1),
("endorse","v",["背書"],"endorse a check",2),
("equity","n",["淨值","股權"],"home equity",2),
("escrow","n",["第三方保管"],"held in escrow",3),
("exchange","n",["匯兌"],"currency exchange",1),
("extend","v",["延長","提供"],"extend credit",1),
("fee","n",["手續費"],"transaction fee",1),
("fiduciary","adj",["信託的"],"fiduciary responsibility",3),
("finance","v",["融資"],"finance a purchase",1),
("fixed","adj",["固定的"],"fixed rate",1),
("foreclose","v",["法拍"],"foreclose on a home",3),
("fund","n",["基金"],"hedge fund",2),
("guarantee","n",["保證"],"loan guarantee",1),
("index","n",["指數"],"market index",1),
("inflation","n",["通膨"],"inflation hedge",2),
("installment","n",["分期"],"monthly installment",1),
("insure","v",["保險"],"insure deposits",1),
("interest","n",["利息"],"earn interest",1),
("invest","v",["投資"],"invest in stocks",1),
("lend","v",["借出","放款"],"lend to borrowers",1),
("liability","n",["負債"],"total liabilities",2),
("liquid","adj",["流動性的"],"liquid assets",2),
("loan","n",["貸款"],"personal loan",1),
("maturity","n",["到期"],"at maturity",2),
("merchant","n",["商家"],"merchant services",1),
("mobile","adj",["行動的"],"mobile banking",1),
("mortgage","n",["房貸"],"mortgage rate",1),
("mutual","adj",["共同的"],"mutual fund",2),
("negotiate","v",["協商"],"negotiate rates",1),
("online","adj",["線上的"],"online banking",1),
("outstanding","adj",["未償還的"],"outstanding loan",1),
("overdraft","n",["透支"],"overdraft protection",2),
("penalty","n",["罰款"],"late penalty",1),
("portfolio","n",["投資組合"],"manage portfolio",2),
("premium","n",["保費"],"insurance premium",2),
("principal","n",["本金"],"principal amount",2),
("process","v",["處理"],"process a transaction",1),
("profit","n",["利潤"],"bank profit",1),
("qualify","v",["有資格"],"qualify for financing",1),
("rate","n",["利率"],"interest rate",1),
("receipt","n",["收據"],"transaction receipt",1),
("refinance","v",["再融資"],"refinance a loan",2),
("regulate","v",["監管"],"regulate banks",2),
("remittance","n",["匯款"],"send remittance",2),
("repay","v",["償還"],"repay a loan",1),
("reserve","n",["準備金"],"bank reserve",2),
("return","n",["收益率"],"rate of return",1),
("risk","n",["風險"],"credit risk",1),
("secure","v",["擔保"],"secure a loan",1),
("security","n",["證券","擔保"],"collateral security",2),
("statement","n",["對帳單"],"monthly statement",1),
("teller","n",["銀行行員"],"bank teller",1),
("term","n",["期限"],"loan term",1),
("transaction","n",["交易"],"banking transaction",1),
("transfer","v",["轉帳"],"wire transfer",1),
("treasury","n",["國庫"],"treasury bill",2),
("trust","n",["信託"],"investment trust",2),
("underwrite","v",["承保"],"underwrite a loan",3),
("variable","adj",["浮動的"],"variable rate",2),
("vault","n",["金庫"],"bank vault",1),
("verify","v",["驗證"],"verify identity",1),
("withdraw","v",["提款"],"withdraw cash",1),
("yield","n",["收益率"],"annual yield",2),
],
"cat14": [
("advertise","v",["刊登廣告"],"advertise online",1),
("anchor","n",["主播"],"news anchor",1),
("announce","v",["宣佈"],"announce news",1),
("announcement","n",["公告"],"press announcement",1),
("article","n",["文章"],"news article",1),
("audience","n",["觀眾","受眾"],"large audience",1),
("blog","n",["部落格"],"company blog",1),
("broadcast","v",["播送","廣播"],"broadcast live",1),
("brochure","n",["手冊"],"marketing brochure",1),
("bulletin","n",["公報","快訊"],"news bulletin",1),
("campaign","n",["宣傳活動"],"media campaign",1),
("caption","n",["標題","圖說"],"photo caption",1),
("channel","n",["頻道","管道"],"media channel",1),
("circulate","v",["傳播","流通"],"circulate a story",2),
("column","n",["專欄"],"newspaper column",1),
("comment","n",["評論"],"reader comment",1),
("commentator","n",["評論員"],"sports commentator",1),
("communicate","v",["溝通"],"communicate clearly",1),
("conference","n",["記者會"],"press conference",1),
("content","n",["內容"],"digital content",1),
("contributor","n",["撰稿人"],"regular contributor",1),
("coverage","n",["報導"],"news coverage",1),
("critic","n",["評論家"],"film critic",1),
("deadline","n",["截稿期"],"publication deadline",1),
("digital","adj",["數位的"],"digital media",1),
("distribute","v",["發行"],"distribute a magazine",1),
("edit","v",["編輯"],"edit an article",1),
("edition","n",["版本"],"latest edition",1),
("editor","n",["編輯"],"chief editor",1),
("editorial","n",["社論"],"write an editorial",2),
("exclusive","adj",["獨家的"],"exclusive story",1),
("feature","n",["專題報導"],"feature article",1),
("headline","n",["頭條"],"front-page headline",1),
("illustrate","v",["插畫","說明"],"illustrate a point",1),
("influence","n",["影響力"],"media influence",1),
("inform","v",["報導","通知"],"inform the public",1),
("interview","v",["採訪"],"interview a CEO",1),
("journalist","n",["記者"],"investigative journalist",1),
("launch","v",["推出"],"launch a magazine",1),
("layout","n",["版面配置"],"page layout",1),
("magazine","n",["雜誌"],"business magazine",1),
("manuscript","n",["稿件","手稿"],"submit a manuscript",2),
("media","n",["媒體"],"social media",1),
("newsletter","n",["電子報"],"monthly newsletter",1),
("newsroom","n",["新聞室","編輯室"],"busy newsroom",1),
("online","adj",["線上的"],"online publication",1),
("opinion","n",["意見","評論"],"expert opinion",1),
("outlet","n",["媒體平台"],"news outlet",1),
("photographer","n",["攝影師"],"professional photographer",1),
("platform","n",["平台"],"media platform",1),
("podcast","n",["播客"],"business podcast",1),
("press","n",["新聞界","出版社"],"press release",1),
("print","v",["印刷","出版"],"print a newspaper",1),
("produce","v",["製作"],"produce content",1),
("producer","n",["製作人"],"TV producer",1),
("proofread","v",["校對"],"proofread an article",1),
("public","n",["公眾"],"inform the public",1),
("publication","n",["出版物","發表"],"monthly publication",1),
("publicize","v",["公開","宣傳"],"publicize findings",1),
("publish","v",["出版","發表"],"publish an article",1),
("publisher","n",["出版商"],"book publisher",1),
("quote","v",["引述"],"quote a source",1),
("readership","n",["讀者群"],"growing readership",2),
("release","n",["新聞稿","發布"],"press release",1),
("report","v",["報導"],"report the news",1),
("reporter","n",["記者"],"field reporter",1),
("review","n",["評論","評價"],"book review",1),
("revise","v",["修改"],"revise a draft",1),
("segment","n",["節目片段"],"news segment",1),
("source","n",["來源","消息來源"],"reliable source",1),
("sponsor","v",["贊助"],"sponsor a show",1),
("statement","n",["聲明"],"official statement",1),
("stream","v",["串流"],"live stream",1),
("subscribe","v",["訂閱"],"subscribe to a paper",1),
("subscriber","n",["訂閱者"],"paid subscriber",1),
("supplement","n",["副刊","增刊"],"Sunday supplement",2),
("syndicate","v",["聯合發行"],"syndicate a column",3),
("telecast","n",["電視轉播"],"live telecast",2),
("transcript","n",["文字記錄"],"interview transcript",2),
("trend","n",["趨勢"],"media trend",1),
("update","n",["更新","最新消息"],"news update",1),
("viral","adj",["爆紅的","病毒式的"],"viral content",1),
("wire","n",["通訊社"],"wire service",2),
],
"cat15": [
("academic","adj",["學術的"],"academic research",1),
("accredit","v",["認證","授權"],"accredited institution",2),
("achieve","v",["達成","取得"],"achieve a goal",1),
("achievement","n",["成就","成績"],"academic achievement",1),
("admission","n",["入學","錄取"],"college admission",1),
("advance","v",["進步"],"advance knowledge",1),
("alumni","n",["校友"],"alumni association",2),
("assess","v",["評估"],"assess students",2),
("assignment","n",["作業"],"homework assignment",1),
("attend","v",["就讀","出席"],"attend a class",1),
("award","n",["獎項"],"academic award",1),
("campus","n",["校園"],"college campus",1),
("candidate","n",["候選人"],"PhD candidate",1),
("certificate","n",["證書"],"completion certificate",1),
("certification","n",["認證"],"professional certification",1),
("class","n",["課程","班級"],"attend a class",1),
("coach","n",["教練"],"career coach",1),
("collaborate","v",["合作"],"collaborate on research",1),
("college","n",["大學","學院"],"community college",1),
("comprehension","n",["理解","理解力"],"reading comprehension",1),
("conference","n",["學術會議"],"academic conference",1),
("confer","v",["授予"],"confer a degree",2),
("continuing","adj",["持續的"],"continuing education",1),
("course","n",["課程"],"online course",1),
("credential","n",["資格證書"],"teaching credential",2),
("credit","n",["學分"],"earn credits",1),
("curriculum","n",["課程]"],"school curriculum",2),
("dean","n",["院長"],"college dean",2),
("degree","n",["學位"],"master's degree",1),
("demonstrate","v",["展示","證明"],"demonstrate mastery",1),
("diploma","n",["文憑"],"high school diploma",1),
("discipline","n",["學科"],"academic discipline",1),
("dissertation","n",["論文"],"doctoral dissertation",2),
("distance","adj",["遠距的"],"distance learning",1),
("educate","v",["教育"],"educate students",1),
("education","n",["教育"],"higher education",1),
("educator","n",["教育者"],"experienced educator",1),
("eligible","adj",["有資格的"],"eligible for admission",1),
("enroll","v",["註冊","報名"],"enroll in a program",1),
("enrollment","n",["註冊","招生"],"student enrollment",1),
("evaluate","v",["評量"],"evaluate students",1),
("exam","n",["考試"],"final exam",1),
("examine","v",["考查"],"examine knowledge",1),
("exercise","n",["練習"],"grammar exercise",1),
("faculty","n",["教職員"],"faculty meeting",1),
("fellowship","n",["獎學金","研究員"],"research fellowship",2),
("forum","n",["論壇"],"educational forum",1),
("foundation","n",["基金會","基礎"],"educational foundation",1),
("graduate","v",["畢業"],"graduate from college",1),
("grant","n",["補助金"],"research grant",1),
("guidance","n",["輔導","指導"],"career guidance",1),
("handbook","n",["手冊"],"student handbook",1),
("homework","n",["作業"],"complete homework",1),
("instruct","v",["教導"],"instruct students",1),
("instructor","n",["講師"],"course instructor",1),
("intern","n",["實習生"],"research intern",1),
("knowledge","n",["知識"],"practical knowledge",1),
("laboratory","n",["實驗室"],"science laboratory",1),
("learn","v",["學習"],"learn new skills",1),
("lecture","n",["講座","授課"],"attend a lecture",1),
("lecturer","n",["講師"],"university lecturer",1),
("lesson","n",["課程"],"private lesson",1),
("literary","adj",["文學的"],"literary analysis",2),
("major","n",["主修"],"college major",1),
("mentor","n",["導師"],"academic mentor",1),
("methodology","n",["方法論"],"teaching methodology",2),
("module","n",["模組","單元"],"course module",1),
("objective","n",["目標"],"learning objective",1),
("orientation","n",["新生說明會"],"freshman orientation",1),
("participant","n",["參與者"],"workshop participant",1),
("pedagogy","n",["教學法"],"modern pedagogy",3),
("peer","n",["同儕"],"peer review",1),
("prerequisite","n",["先修條件"],"course prerequisite",2),
("professor","n",["教授"],"university professor",1),
("proficiency","n",["精通","熟練度"],"language proficiency",1),
("program","n",["課程","計畫"],"training program",1),
("project","n",["專案","報告"],"research project",1),
("publication","n",["出版","發表"],"academic publication",1),
("qualification","n",["資格","學歷"],"teaching qualification",1),
("quiz","n",["測驗"],"pop quiz",1),
("recommend","v",["推薦"],"recommend a course",1),
("register","v",["註冊"],"register for classes",1),
("research","n",["研究"],"conduct research",1),
("resource","n",["資源"],"learning resource",1),
("review","v",["複習","審查"],"review material",1),
("scholar","n",["學者"],"visiting scholar",2),
("scholarship","n",["獎學金"],"earn a scholarship",1),
("semester","n",["學期"],"fall semester",1),
("seminar","n",["研討會"],"graduate seminar",1),
("skill","n",["技能"],"practical skill",1),
("student","n",["學生"],"international student",1),
("study","v",["學習","研究"],"study abroad",1),
("subject","n",["科目"],"school subject",1),
("submit","v",["繳交"],"submit an essay",1),
("syllabus","n",["課程大綱"],"course syllabus",2),
("teach","v",["教導","教學"],"teach a class",1),
("tenure","n",["終身教職"],"earn tenure",2),
("test","n",["測驗","考試"],"standardized test",1),
("thesis","n",["論文"],"master's thesis",2),
("training","n",["訓練"],"job training",1),
("tuition","n",["學費"],"tuition fee",1),
("tutor","n",["家教"],"private tutor",1),
("undergraduate","n",["大學生"],"undergraduate program",1),
("university","n",["大學"],"state university",1),
("workshop","n",["工作坊"],"writing workshop",1),
],
}
