"""Additional TOEIC vocabulary expansion - Categories 06-15"""
WORDS_EXPAND_3 = {
"cat06": [
("accessible","adj",["可存取的"],"accessible platform",1),
("adapter","n",["轉接器"],"USB adapter",1),
("affiliate","n",["附屬"],"affiliate program",2),
("aggregate","v",["整合"],"aggregate data",2),
("anonymize","v",["匿名化"],"anonymize data",2),
("appliance","n",["家電","裝置"],"smart appliance",1),
("authenticate","v",["驗證"],"authenticate login",2),
("autonomous","adj",["自主的"],"autonomous system",2),
("benchmark","n",["基準"],"performance benchmark",2),
("biometric","adj",["生物辨識的"],"biometric scan",2),
("captcha","n",["驗證碼"],"enter captcha",1),
("centralize","v",["集中化"],"centralize storage",2),
("chipset","n",["晶片組"],"advanced chipset",2),
("cluster","n",["叢集"],"server cluster",2),
("codec","n",["編解碼器"],"video codec",2),
("cognitive","adj",["認知的"],"cognitive computing",2),
("commence","v",["開始"],"commence setup",2),
("compartmentalize","v",["分隔化"],"compartmentalize data",2),
("compliant","adj",["合規的"],"compliant system",2),
("concurrent","adj",["同時的"],"concurrent users",2),
("contingency","n",["應急"],"contingency backup",2),
("converge","v",["融合"],"technology converges",2),
("credential","n",["憑證"],"login credential",2),
("crowdsource","v",["群眾外包"],"crowdsource ideas",2),
("cryptocurrency","n",["加密貨幣"],"cryptocurrency trading",2),
("customize","v",["客製化"],"customize software",1),
("decentralize","v",["去中心化"],"decentralize systems",2),
("decommission","v",["退役"],"decommission a server",2),
("degradation","n",["降級","退化"],"performance degradation",2),
("deprecate","v",["棄用"],"deprecate a feature",2),
("diagnostic","n",["診斷"],"run diagnostics",2),
("disruptive","adj",["顛覆性的"],"disruptive technology",2),
("downgrade","v",["降級"],"downgrade software",1),
("ecosystem","n",["生態系統"],"tech ecosystem",2),
("emulate","v",["模擬","效仿"],"emulate a system",2),
("endpoint","n",["端點"],"API endpoint",2),
("enterprise","adj",["企業級的"],"enterprise solution",1),
("ergonomic","adj",["人體工學的"],"ergonomic keyboard",2),
("escalation","n",["升級"],"issue escalation",2),
("expedite","v",["加速"],"expedite processing",2),
("framework","n",["框架"],"development framework",2),
("gateway","n",["閘道"],"network gateway",2),
("glitch","n",["故障"],"system glitch",1),
("granular","adj",["細粒度的"],"granular control",2),
("holistic","adj",["全面的"],"holistic approach",2),
("immersive","adj",["沉浸式的"],"immersive experience",2),
("increment","n",["增量"],"incremental update",2),
("infrastructure","n",["基礎設施"],"cloud infrastructure",2),
("insufficient","adj",["不足的"],"insufficient storage",1),
("interoperable","adj",["可互通的"],"interoperable systems",2),
("iterate","v",["迭代"],"iterate on code",2),
("latency","n",["延遲"],"low latency",2),
("legacy","adj",["舊有的"],"legacy system",2),
("middleware","n",["中介軟體"],"application middleware",2),
("milestone","n",["里程碑"],"development milestone",1),
("mitigation","n",["緩解"],"risk mitigation",2),
("modular","adj",["模組化的"],"modular design",2),
("neural","adj",["神經的"],"neural network",2),
("obsolete","adj",["過時的"],"obsolete technology",2),
("onboard","v",["導入"],"onboard users",1),
("orchestrate","v",["編排"],"orchestrate services",2),
("outage","n",["停機"],"system outage",1),
("overload","v",["過載"],"server overload",1),
("parameter","n",["參數"],"set parameters",2),
("parse","v",["解析"],"parse data",2),
("patch","v",["修補"],"patch software",2),
("penetrate","v",["滲透"],"penetrate security",2),
("pipeline","n",["管線","流程"],"data pipeline",2),
("pivotal","adj",["關鍵的"],"pivotal technology",2),
("portable","adj",["攜帶型的"],"portable device",1),
("pragmatic","adj",["務實的"],"pragmatic solution",2),
("predictive","adj",["預測的"],"predictive analytics",2),
("prerequisite","n",["先決條件"],"system prerequisite",2),
("proprietary","adj",["專有的"],"proprietary software",2),
("provisioning","n",["配置"],"server provisioning",2),
("resilient","adj",["有彈性的"],"resilient system",2),
("retrofit","v",["改裝"],"retrofit hardware",2),
("robust","adj",["強健的"],"robust architecture",2),
("sandbox","n",["沙盒"],"testing sandbox",2),
("seamless","adj",["無縫的"],"seamless integration",1),
("segment","v",["分段"],"segment data",2),
("semantic","adj",["語意的"],"semantic search",2),
("sequential","adj",["連續的"],"sequential processing",2),
("snippet","n",["片段"],"code snippet",2),
("stakeholder","n",["利害關係人"],"project stakeholder",1),
("standalone","adj",["獨立的"],"standalone application",1),
("streamline","v",["精簡"],"streamline development",2),
("sustainable","adj",["可持續的"],"sustainable tech",1),
("synchronize","v",["同步"],"synchronize devices",1),
("telemetry","n",["遙測"],"system telemetry",2),
("throughput","n",["吞吐量"],"network throughput",2),
("toggle","v",["切換"],"toggle a setting",1),
("tokenize","v",["代幣化"],"tokenize data",2),
("topology","n",["拓撲"],"network topology",2),
("vendor","n",["供應商"],"tech vendor",1),
("versatile","adj",["多功能的"],"versatile platform",1),
("vulnerability","n",["漏洞"],"security vulnerability",2),
("workflow","n",["工作流程"],"automated workflow",1),
],
"cat07": [
("acquiesce","v",["默許","順從"],"acquiesce to demands",3),
("adjournment","n",["休庭","延期"],"request adjournment",3),
("antagonist","n",["對手","敵手"],"legal antagonist",3),
("antitrust","adj",["反壟斷的"],"antitrust law",2),
("arraign","v",["提訊","傳訊"],"arraign the suspect",3),
("bail","n",["保釋金"],"post bail",2),
("bankrupt","adj",["破產的"],"declare bankrupt",2),
("bankruptcy","n",["破產"],"file for bankruptcy",2),
("barrister","n",["出庭律師"],"hire a barrister",2),
("benefactor","n",["捐助者"],"charitable benefactor",2),
("bequest","n",["遺贈"],"generous bequest",3),
("binding","adj",["有約束力的"],"legally binding",2),
("bona fide","adj",["真正的","善意的"],"bona fide offer",3),
("caveat","n",["警告","附帶條件"],"important caveat",2),
("certiorari","n",["調卷令"],"writ of certiorari",3),
("circumstantial","adj",["間接的"],"circumstantial evidence",3),
("clemency","n",["寬大處理"],"grant clemency",3),
("codicil","n",["遺囑附錄"],"add a codicil",3),
("collude","v",["勾結","串通"],"collude with competitors",3),
("contempt","n",["蔑視","藐視法庭"],"contempt of court",2),
("corroborate","v",["證實","確認"],"corroborate evidence",3),
("culpable","adj",["有過失的"],"culpable behavior",3),
("custody","n",["監護","拘留"],"in custody",2),
("defendant","n",["被告"],"named defendant",2),
("deposition","n",["證詞","錄取證詞"],"give a deposition",3),
("detain","v",["拘留"],"detain a suspect",2),
("deterrent","n",["威懾"],"legal deterrent",2),
("diligence","n",["盡職","勤勉"],"due diligence",2),
("dissent","n",["異議"],"formal dissent",2),
("doctrine","n",["學說","原則"],"legal doctrine",2),
("duress","n",["脅迫","強制"],"under duress",3),
("emancipate","v",["解放"],"emancipate from debt",3),
("embargo","n",["禁令"],"trade embargo",2),
("encroach","v",["侵犯","侵佔"],"encroach on rights",2),
("escheat","n",["充公"],"property escheat",3),
("estoppel","n",["禁止反言"],"promissory estoppel",3),
("exculpate","v",["開脫"],"exculpate the accused",3),
("executor","n",["執行人"],"estate executor",3),
("felony","n",["重罪"],"commit a felony",2),
("fiduciary","adj",["信託的"],"fiduciary duty",3),
("habeas corpus","n",["人身保護令"],"file habeas corpus",3),
("impunity","n",["免罰"],"act with impunity",3),
("incarcerate","v",["監禁"],"incarcerate an offender",3),
("indictment","n",["起訴書"],"grand jury indictment",3),
("injunct","v",["命令停止"],"injunct the defendant",3),
("jurisprudence","n",["法學"],"study jurisprudence",3),
("levy","v",["課徵"],"levy a fine",2),
("litigant","n",["訴訟當事人"],"active litigant",3),
("magistrate","n",["法官","裁判官"],"local magistrate",2),
("malfeasance","n",["瀆職"],"official malfeasance",3),
("manslaughter","n",["過失殺人"],"charged with manslaughter",3),
("moot","adj",["有爭議的"],"moot point",2),
("moratorium","n",["暫停令"],"impose moratorium",3),
("nullify","v",["使無效"],"nullify a contract",2),
("perjury","n",["做偽證"],"commit perjury",3),
("plaintiff","n",["原告"],"the plaintiff",2),
("plea","n",["抗辯"],"guilty plea",2),
("precedent","n",["判例"],"set a precedent",2),
("probate","n",["遺囑認證"],"probate court",3),
("pro bono","adj",["免費的"],"pro bono work",2),
("prosecute","v",["起訴"],"prosecute a case",2),
("quash","v",["撤銷","推翻"],"quash a verdict",3),
("restitution","n",["賠償"],"order restitution",3),
("retainer","n",["聘用費"],"pay a retainer",2),
("revoke","v",["撤銷"],"revoke a license",2),
("solicit","v",["徵求","請求"],"solicit clients",2),
("statute","n",["法規"],"within the statute",2),
("subpoena","n",["傳票"],"issue a subpoena",2),
("supercede","v",["取代"],"supercede a ruling",3),
("testimony","n",["證詞"],"give testimony",2),
("tort","n",["侵權行為"],"civil tort",3),
("waiver","n",["棄權書"],"sign a waiver",2),
],
"cat08": [
("archive","v",["歸檔"],"archive records",1),
("audit","n",["稽查"],"office audit",2),
("authorize","v",["授權"],"authorize purchase",2),
("backlog","n",["積壓"],"clear the backlog",2),
("batch","n",["批次"],"process in batches",1),
("blueprint","n",["藍圖"],"office blueprint",2),
("briefcase","n",["公事包"],"carry a briefcase",1),
("bulletin","n",["公告"],"post a bulletin",1),
("cartridge","n",["墨水匣"],"ink cartridge",1),
("centralize","v",["集中"],"centralize files",2),
("circulate","v",["流通"],"circulate a memo",2),
("clerk","n",["辦事員"],"file clerk",1),
("collaborate","v",["合作"],"collaborate remotely",1),
("commute","v",["通勤"],"commute daily",1),
("comply","v",["遵守"],"comply with policy",2),
("confidential","adj",["機密的"],"confidential file",2),
("consolidate","v",["合併"],"consolidate files",2),
("coordinate","v",["協調"],"coordinate tasks",1),
("courier","n",["快遞"],"send by courier",1),
("credential","n",["證件"],"office credential",2),
("cubicle","n",["隔間"],"work in a cubicle",1),
("delegate","v",["委派"],"delegate tasks",2),
("directory","n",["目錄"],"staff directory",1),
("dispatch","v",["派送"],"dispatch courier",2),
("duplicate","v",["複製"],"duplicate keys",1),
("escalate","v",["升級"],"escalate an issue",2),
("expedite","v",["加速"],"expedite delivery",2),
("facilitate","v",["促進"],"facilitate workflow",2),
("facsimile","n",["傳真"],"send a facsimile",2),
("implement","v",["實施"],"implement changes",1),
("inauguration","n",["就職","開幕"],"office inauguration",2),
("intranet","n",["內部網路"],"company intranet",2),
("ledger","n",["帳本"],"office ledger",2),
("liaison","n",["聯絡人"],"department liaison",2),
("logistics","n",["後勤"],"office logistics",2),
("mandate","v",["強制"],"mandate compliance",2),
("merge","v",["合併"],"merge departments",2),
("morale","n",["士氣"],"boost office morale",1),
("negotiate","v",["談判"],"negotiate lease",1),
("nominal","adj",["名義的"],"nominal fee",2),
("oversee","v",["監督"],"oversee operations",2),
("personnel","n",["人事"],"personnel file",1),
("petition","n",["請願"],"submit a petition",2),
("prerequisite","n",["先決條件"],"office prerequisite",2),
("procurement","n",["採購"],"office procurement",2),
("protocol","n",["協定","規範"],"office protocol",2),
("receptacle","n",["容器"],"recycling receptacle",2),
("roster","n",["輪值表"],"duty roster",2),
("scrutinize","v",["仔細審查"],"scrutinize records",2),
("streamline","v",["精簡"],"streamline procedures",2),
("subordinate","n",["下屬"],"office subordinate",2),
("surplus","n",["剩餘"],"office surplus",2),
("syndicate","v",["組成聯合體"],"syndicate efforts",3),
("teleconference","n",["電話會議"],"join a teleconference",1),
("vicinity","n",["附近"],"office vicinity",1),
],
"cat09": [
("accessible","adj",["可到達的"],"accessible route",1),
("adjacent","adj",["鄰近的"],"adjacent terminal",1),
("berth","n",["泊位","鋪位"],"ship berth",2),
("bilingual","adj",["雙語的"],"bilingual guide",1),
("brochure","n",["手冊"],"travel brochure",1),
("browse","v",["瀏覽"],"browse options",1),
("bumpy","adj",["顛簸的"],"bumpy ride",1),
("bypass","v",["繞過"],"bypass traffic",1),
("chauffeur","n",["專職司機"],"hire a chauffeur",2),
("circumnavigate","v",["環繞航行"],"circumnavigate the globe",3),
("clause","n",["條款"],"cancellation clause",2),
("complimentary","adj",["免費的"],"complimentary upgrade",1),
("confiscate","v",["沒收"],"confiscate items",2),
("consolidate","v",["合併"],"consolidate shipments",2),
("contraband","n",["走私品"],"contraband goods",2),
("corridor","n",["走廊"],"transit corridor",1),
("depart","v",["出發"],"depart on time",1),
("disembark","v",["下船","下飛機"],"disembark safely",2),
("divert","v",["改道"],"divert the flight",2),
("embargo","n",["禁運"],"trade embargo",2),
("embark","v",["登機"],"embark on journey",2),
("expedite","v",["加速"],"expedite clearance",2),
("facilitate","v",["促進"],"facilitate travel",2),
("fuselage","n",["機身"],"aircraft fuselage",2),
("intercontinental","adj",["洲際的"],"intercontinental flight",2),
("junction","n",["交叉口"],"highway junction",1),
("layover","n",["中途停留"],"long layover",1),
("maritime","adj",["海運的"],"maritime industry",2),
("meander","v",["蜿蜒"],"meander through",2),
("navigate","v",["導航"],"navigate traffic",1),
("nonstop","adj",["直達的"],"nonstop flight",1),
("obstruct","v",["阻礙"],"obstruct passage",2),
("peninsula","n",["半島"],"scenic peninsula",2),
("proximity","n",["鄰近"],"in proximity to",2),
("quarantine","n",["隔離"],"quarantine zone",2),
("ramp","n",["坡道","登機坡道"],"boarding ramp",1),
("scenic","adj",["風景優美的"],"scenic route",1),
("sojourn","n",["短暫停留"],"brief sojourn",3),
("stow","v",["收藏","存放"],"stow luggage",1),
("tariff","n",["費率","關稅"],"customs tariff",2),
("traverse","v",["穿越"],"traverse the country",2),
("turnaround","n",["轉運時間"],"quick turnaround",1),
("wayfinding","n",["尋路指引"],"airport wayfinding",2),
],
"cat10": [
("abstain","v",["戒除","棄權"],"abstain from alcohol",2),
("adhere","v",["遵守"],"adhere to treatment",2),
("adverse","adj",["不良的"],"adverse reaction",2),
("alleviate","v",["減輕"],"alleviate pain",2),
("anesthesia","n",["麻醉"],"general anesthesia",2),
("antibiotic","n",["抗生素"],"prescribe antibiotics",2),
("antiseptic","n",["消毒劑"],"apply antiseptic",2),
("benign","adj",["良性的"],"benign tumor",2),
("cardiovascular","adj",["心血管的"],"cardiovascular health",2),
("chronic","adj",["慢性的"],"chronic condition",2),
("cognitive","adj",["認知的"],"cognitive therapy",2),
("compassionate","adj",["有同情心的"],"compassionate care",2),
("comply","v",["遵守"],"comply with treatment",2),
("comprehensive","adj",["全面的"],"comprehensive exam",2),
("confidential","adj",["保密的"],"confidential records",2),
("congenital","adj",["先天的"],"congenital condition",3),
("consecutive","adj",["連續的"],"consecutive doses",2),
("contaminate","v",["污染"],"contaminate samples",2),
("debilitate","v",["使衰弱"],"debilitating illness",3),
("dermatologist","n",["皮膚科醫師"],"consult dermatologist",2),
("deteriorate","v",["惡化"],"condition deteriorates",2),
("diagnostic","adj",["診斷的"],"diagnostic test",2),
("dietitian","n",["營養師"],"consult a dietitian",2),
("dosage","n",["劑量"],"accurate dosage",2),
("efficacy","n",["功效"],"drug efficacy",2),
("epidemic","n",["流行病"],"flu epidemic",2),
("evaluate","v",["評估"],"evaluate symptoms",1),
("exacerbate","v",["加劇"],"exacerbate symptoms",3),
("gene","n",["基因"],"gene therapy",2),
("generic","adj",["通用的"],"generic medicine",1),
("holistic","adj",["全面的"],"holistic treatment",2),
("inpatient","n",["住院病人"],"inpatient care",2),
("malignant","adj",["惡性的"],"malignant tumor",3),
("mandatory","adj",["強制性的"],"mandatory vaccination",2),
("neurologist","n",["神經科醫師"],"consult neurologist",2),
("optimal","adj",["最佳的"],"optimal health",2),
("pathology","n",["病理學"],"study pathology",3),
("pediatric","adj",["兒科的"],"pediatric care",2),
("pharmaceutical","adj",["製藥的"],"pharmaceutical company",2),
("physiotherapy","n",["物理治療"],"undergo physiotherapy",2),
("placebo","n",["安慰劑"],"placebo effect",2),
("precaution","n",["預防措施"],"take precautions",1),
("prognosis","n",["預後"],"positive prognosis",3),
("prophylactic","adj",["預防性的"],"prophylactic treatment",3),
("prosthetic","adj",["義肢的"],"prosthetic limb",2),
("psychiatric","adj",["精神科的"],"psychiatric care",2),
("relapse","n",["復發"],"prevent relapse",2),
("remission","n",["緩解期"],"in remission",3),
("resuscitate","v",["使甦醒","急救"],"resuscitate patient",3),
("sterile","adj",["無菌的"],"sterile environment",2),
("supplement","n",["補充品"],"dietary supplement",1),
("symptom","n",["症狀"],"common symptoms",1),
("syndrome","n",["症候群"],"metabolic syndrome",2),
("therapeutic","adj",["治療的"],"therapeutic benefit",2),
("toxic","adj",["有毒的"],"toxic substance",2),
("transfusion","n",["輸血"],"blood transfusion",2),
("triage","n",["分診"],"emergency triage",2),
],
"cat11": [
("acre","n",["英畝"],"two-acre lot",1),
("amenity","n",["設施","便利設施"],"building amenities",1),
("annex","n",["附屬建築"],"office annex",2),
("attic","n",["閣樓"],"spacious attic",1),
("awning","n",["遮棚"],"install an awning",2),
("bungalow","n",["平房"],"beachfront bungalow",1),
("canopy","n",["雨棚","天蓬"],"entrance canopy",2),
("caulk","v",["填縫"],"caulk windows",2),
("condo","n",["公寓"],"luxury condo",1),
("corridor","n",["走廊"],"building corridor",1),
("dormitory","n",["宿舍"],"student dormitory",1),
("duplex","n",["雙拼屋"],"rent a duplex",1),
("drywall","n",["石膏板"],"install drywall",2),
("embellish","v",["裝飾"],"embellish interiors",2),
("facade","n",["建築正面"],"building facade",2),
("foyer","n",["大廳"],"entrance foyer",1),
("gazebo","n",["涼亭"],"garden gazebo",1),
("habitable","adj",["可居住的"],"habitable condition",2),
("inhabit","v",["居住"],"inhabit a building",2),
("intercom","n",["對講機"],"building intercom",1),
("joist","n",["托梁"],"floor joist",2),
("keystone","n",["拱頂石"],"architectural keystone",3),
("linoleum","n",["油毡"],"linoleum flooring",2),
("manmade","adj",["人造的"],"manmade materials",1),
("occupant","n",["居住者"],"building occupant",1),
("parcel","n",["地塊"],"land parcel",2),
("penthouse","n",["頂層公寓"],"luxury penthouse",1),
("prefabricate","v",["預製"],"prefabricated building",2),
("proprietor","n",["業主"],"property proprietor",2),
("realty","n",["不動產"],"realty market",1),
("refurbish","v",["翻新"],"refurbish a house",2),
("sublet","v",["轉租"],"sublet an apartment",2),
("terrace","n",["露台"],"rooftop terrace",1),
("townhouse","n",["透天厝"],"suburban townhouse",1),
("traverse","v",["穿越"],"traverse the property",2),
("upkeep","n",["維護費"],"property upkeep",1),
("viaduct","n",["高架橋"],"railway viaduct",2),
("waterproof","v",["防水處理"],"waterproof the basement",2),
],
"cat12": [
("adjourn","v",["暫停"],"adjourn for lunch",2),
("allergy","n",["過敏"],"food allergy",1),
("appetizing","adj",["開胃的"],"appetizing dish",1),
("aroma","n",["香氣"],"coffee aroma",1),
("baste","v",["塗抹肉汁"],"baste the turkey",2),
("blanch","v",["快速水煮"],"blanch vegetables",2),
("braise","v",["燉"],"braise meat",2),
("cater","v",["外燴"],"cater an event",1),
("cellar","n",["酒窖"],"wine cellar",1),
("confectionery","n",["糖果","甜點"],"confectionery shop",2),
("connoisseur","n",["鑒賞家"],"wine connoisseur",2),
("culinary","adj",["烹飪的"],"culinary art",2),
("debone","v",["去骨"],"debone a chicken",2),
("decant","v",["倒入醒酒器"],"decant wine",2),
("delicatessen","n",["精緻食品"],"local delicatessen",2),
("entrée","n",["主菜"],"order an entrée",1),
("flambé","v",["火焰料理"],"flambé dessert",3),
("gastronomy","n",["美食學"],"molecular gastronomy",3),
("gluten","n",["麩質"],"gluten-free",1),
("hors d'oeuvre","n",["開胃小菜"],"serve hors d'oeuvres",2),
("infuse","v",["浸泡","注入"],"infuse herbs",2),
("julienne","v",["切絲"],"julienne vegetables",2),
("kosher","adj",["合乎猶太教規的"],"kosher food",2),
("lard","n",["豬油"],"cook with lard",2),
("macerate","v",["浸漬"],"macerate fruit",3),
("maitre d","n",["領班"],"speak to the maitre d",2),
("marinate","v",["醃漬"],"marinate chicken",1),
("nutrition","n",["營養"],"proper nutrition",1),
("palette","n",["味覺"],"refined palette",2),
("pasteurize","v",["巴氏消毒"],"pasteurize milk",2),
("poach","v",["水波煮"],"poach eggs",2),
("purée","v",["打成泥"],"purée soup",2),
("rancid","adj",["腐臭的"],"rancid butter",2),
("sauté","v",["快炒"],"sauté vegetables",1),
("simmer","v",["小火燉"],"simmer the sauce",1),
("sommelier","n",["侍酒師"],"hotel sommelier",2),
("sous chef","n",["副廚"],"experienced sous chef",2),
("steep","v",["浸泡"],"steep tea",1),
("vegan","adj",["純素的"],"vegan menu",1),
("ventilate","v",["通風"],"ventilate kitchen",2),
("vintage","n",["年份酒"],"fine vintage",2),
("zest","n",["果皮屑"],"lemon zest",2),
],
"cat13": [
("accrue","v",["累積"],"accrue savings",2),
("annuity","n",["年金"],"purchase an annuity",3),
("arbitrage","n",["套利"],"currency arbitrage",3),
("assessment","n",["評估"],"risk assessment",2),
("blockchain","n",["區塊鏈"],"blockchain finance",2),
("clearinghouse","n",["清算所"],"financial clearinghouse",3),
("collateral","n",["擔保品"],"provide collateral",2),
("consolidation","n",["合併"],"debt consolidation",2),
("correspondent","n",["代理行"],"correspondent bank",3),
("custodian","n",["託管人"],"fund custodian",3),
("delinquency","n",["拖欠"],"loan delinquency",2),
("denomination","n",["面額"],"bill denomination",2),
("derivative","n",["衍生工具"],"financial derivative",3),
("embargo","n",["禁令"],"financial embargo",2),
("endowment","n",["捐贈基金"],"endowment fund",2),
("fiduciary","n",["受託人"],"act as fiduciary",3),
("float","v",["浮動"],"float interest rates",2),
("fluctuate","v",["波動"],"rates fluctuate",2),
("hedge","v",["避險"],"hedge investments",2),
("insolvent","adj",["無力償債的"],"declared insolvent",3),
("interchange","n",["交換費"],"interchange fee",2),
("ledger","n",["帳本"],"general ledger",2),
("liquidity","n",["流動性"],"market liquidity",2),
("mandate","n",["委託"],"investment mandate",2),
("microloan","n",["微型貸款"],"issue microloans",2),
("notary","n",["公證人"],"visit a notary",2),
("promissory","adj",["承諾的"],"promissory note",3),
("receivership","n",["破產管理"],"placed in receivership",3),
("reconcile","v",["對帳"],"reconcile statements",2),
("remit","v",["匯款"],"remit payment",2),
("scrutinize","v",["審核"],"scrutinize transactions",2),
("solvency","n",["償付能力"],"maintain solvency",3),
("subsidiary","n",["子公司"],"banking subsidiary",2),
("surcharge","n",["附加費"],"service surcharge",1),
("syndicate","n",["銀行團"],"loan syndicate",3),
("tenor","n",["期限"],"loan tenor",3),
("volatility","n",["波動性"],"market volatility",2),
],
"cat14": [
("affiliate","n",["附屬機構"],"media affiliate",2),
("bias","n",["偏見"],"media bias",2),
("byline","n",["署名"],"article byline",2),
("censorship","n",["審查"],"media censorship",2),
("columnist","n",["專欄作家"],"newspaper columnist",2),
("corroborate","v",["證實"],"corroborate a story",2),
("credible","adj",["可信的"],"credible source",1),
("dateline","n",["發稿地"],"news dateline",2),
("defamation","n",["誹謗"],"avoid defamation",3),
("disseminate","v",["傳播"],"disseminate information",2),
("embed","v",["嵌入"],"embed a reporter",2),
("excerpt","n",["摘錄"],"book excerpt",2),
("expose","n",["揭發"],"investigative exposé",2),
("freelance","adj",["自由職業的"],"freelance writer",1),
("gazette","n",["公報"],"government gazette",2),
("infomercial","n",["資訊廣告"],"late-night infomercial",2),
("libel","n",["文字誹謗"],"sue for libel",3),
("masthead","n",["報頭"],"newspaper masthead",2),
("obsolete","adj",["過時的"],"obsolete media",2),
("op-ed","n",["社評對頁"],"write an op-ed",2),
("paparazzi","n",["狗仔隊"],"avoid paparazzi",1),
("periodical","n",["期刊"],"trade periodical",2),
("plagiarize","v",["抄襲"],"plagiarize content",2),
("podcast","n",["播客"],"news podcast",1),
("propaganda","n",["宣傳"],"political propaganda",2),
("pundit","n",["評論家"],"political pundit",2),
("redact","v",["編輯刪減"],"redact sensitive info",2),
("retract","v",["撤回"],"retract a statement",2),
("scoop","n",["獨家新聞"],"news scoop",2),
("slander","n",["口頭誹謗"],"sue for slander",3),
("tabloid","n",["小報"],"tabloid newspaper",1),
("verbatim","adv",["逐字地"],"quote verbatim",2),
],
"cat15": [
("accreditation","n",["認證","認可"],"program accreditation",2),
("alumnus","n",["校友"],"notable alumnus",2),
("apprentice","n",["學徒"],"become an apprentice",1),
("audit","v",["旁聽"],"audit a course",1),
("bursary","n",["獎學金"],"receive a bursary",2),
("chancellor","n",["校長"],"university chancellor",2),
("collegiate","adj",["大學的"],"collegiate level",2),
("commencement","n",["畢業典禮"],"commencement ceremony",2),
("compulsory","adj",["必修的"],"compulsory course",2),
("convocation","n",["畢業典禮"],"attend convocation",2),
("cum laude","adv",["以優等"],"graduate cum laude",2),
("dean","n",["院長"],"college dean",2),
("dissertation","n",["學位論文"],"doctoral dissertation",2),
("elective","n",["選修課"],"take an elective",1),
("emeritus","adj",["榮譽退休的"],"professor emeritus",3),
("etymology","n",["詞源學"],"study etymology",3),
("extracurricular","adj",["課外的"],"extracurricular activities",1),
("formative","adj",["形成的"],"formative assessment",2),
("graduating","adj",["畢業的"],"graduating class",1),
("immersion","n",["沉浸"],"language immersion",2),
("interdisciplinary","adj",["跨學科的"],"interdisciplinary study",2),
("matriculate","v",["入學"],"matriculate at college",3),
("pedagogue","n",["教育家"],"respected pedagogue",3),
("postdoctoral","adj",["博士後的"],"postdoctoral research",2),
("postgraduate","n",["研究生"],"postgraduate studies",1),
("practicum","n",["實習"],"teaching practicum",2),
("proctor","n",["監考人"],"exam proctor",2),
("provost","n",["教務長"],"university provost",2),
("remedial","adj",["補救的"],"remedial course",2),
("sabbatical","n",["學術休假"],"take a sabbatical",2),
("scholastic","adj",["學術的"],"scholastic achievement",2),
("summative","adj",["總結的"],"summative assessment",2),
("symposium","n",["研討會"],"academic symposium",2),
("tenure","n",["終身教職"],"earn tenure",2),
("transcript","n",["成績單"],"academic transcript",1),
("truancy","n",["逃學"],"address truancy",2),
("tutelage","n",["指導"],"under the tutelage of",3),
("valedictorian","n",["畢業生代表"],"class valedictorian",2),
],
}
