"""Additional TOEIC vocabulary - Categories 02-05 expansion"""
WORDS_EXPAND_2 = {
"cat02": [
("accelerate","v",["加速"],"accelerate payments",2),
("accrue","v",["累積","應計"],"accrue interest",2),
("accumulate","v",["累積"],"accumulate wealth",2),
("acquaint","v",["使了解"],"acquaint with terms",2),
("actuarial","adj",["精算的"],"actuarial analysis",3),
("adjuster","n",["理賠員"],"insurance adjuster",2),
("adjust","v",["調整"],"adjust figures",1),
("advance","n",["預付款"],"cash advance",1),
("adverse","adj",["不利的"],"adverse conditions",2),
("aggregate","n",["總計"],"in aggregate",2),
("allocate","v",["分配"],"allocate funds",2),
("allowance","n",["津貼"],"travel allowance",1),
("amass","v",["積累"],"amass capital",2),
("amortization","n",["分期攤還"],"loan amortization",3),
("amortize","v",["攤銷"],"amortize a loan",3),
("annuity","n",["年金"],"fixed annuity",3),
("appreciate","v",["增值","感謝"],"appreciate in value",1),
("appreciation","n",["升值","感謝"],"capital appreciation",2),
("arbitrage","n",["套利"],"arbitrage opportunity",3),
("arrears","n",["欠款","拖欠"],"in arrears",2),
("attest","v",["證實"],"attest to accuracy",2),
("augment","v",["增加"],"augment revenue",2),
("austerity","n",["緊縮"],"austerity measures",2),
("bail","n",["保釋金"],"post bail",2),
("bailout","n",["紓困"],"government bailout",2),
("benchmark","n",["基準"],"performance benchmark",2),
("bookkeeping","n",["簿記"],"double-entry bookkeeping",2),
("boom","n",["繁榮"],"economic boom",1),
("bounty","n",["獎金","賞金"],"cash bounty",2),
("broker","n",["經紀人"],"stock broker",1),
("brokerage","n",["經紀業務"],"brokerage fee",2),
("bust","n",["蕭條"],"economic bust",2),
("buyout","n",["收購"],"leveraged buyout",2),
("capitalize","v",["資本化"],"capitalize expenses",2),
("cartel","n",["卡特爾","壟斷"],"oil cartel",3),
("ceiling","n",["上限"],"debt ceiling",2),
("certify","v",["認證"],"certify accounts",2),
("charter","n",["章程","許可"],"bank charter",2),
("claimant","n",["索賠人"],"insurance claimant",2),
("coefficient","n",["係數"],"cost coefficient",3),
("coffers","n",["金庫","國庫"],"government coffers",2),
("commodity","n",["商品","大宗商品"],"commodity prices",2),
("compensate","v",["補償"],"compensate losses",2),
("compound","v",["複合"],"compound interest",2),
("confiscate","v",["沒收"],"confiscate assets",2),
("conglomerate","n",["企業集團"],"media conglomerate",2),
("conservative","adj",["保守的"],"conservative estimate",1),
("consortium","n",["財團"],"banking consortium",2),
("constrain","v",["限制"],"constrain spending",2),
("contingency","n",["應急金"],"contingency fund",2),
("converge","v",["匯聚"],"prices converge",2),
("convertible","adj",["可轉換的"],"convertible bond",3),
("corpus","n",["本金","主體"],"investment corpus",3),
("correlate","v",["相關"],"correlate with GDP",2),
("cushion","n",["緩衝"],"financial cushion",2),
("cutback","n",["削減"],"budget cutback",1),
("cyclical","adj",["週期性的"],"cyclical trend",2),
("debenture","n",["公司債"],"issue debentures",3),
("debit","v",["借記"],"debit an account",2),
("decrement","n",["減少"],"salary decrement",2),
("deduction","n",["扣除","扣減"],"tax deduction",1),
("defer","v",["遞延"],"defer payment",2),
("deficit","n",["赤字","虧損"],"trade deficit",2),
("deflation","n",["通貨緊縮"],"price deflation",2),
("delinquent","adj",["拖欠的"],"delinquent account",2),
("denominate","v",["標價"],"denominate in dollars",3),
("deplete","v",["耗盡"],"deplete reserves",2),
("depreciation","n",["折舊"],"asset depreciation",2),
("depress","v",["壓低"],"depress prices",2),
("deregulate","v",["解除管制"],"deregulate markets",2),
("derivative","n",["衍生工具"],"financial derivative",3),
("deteriorate","v",["惡化"],"finances deteriorate",2),
("devalue","v",["貶值"],"devalue currency",2),
("diminish","v",["減少"],"diminish returns",2),
("disallow","v",["不允許"],"disallow a deduction",2),
("disburse","v",["支出"],"disburse funds",2),
("disbursement","n",["支付","支出"],"loan disbursement",2),
("disclosure","n",["揭露"],"financial disclosure",2),
("discount","v",["折扣","貼現"],"discount a bill",1),
("discretionary","adj",["可自由支配的"],"discretionary income",2),
("disparity","n",["差距"],"income disparity",2),
("dispense","v",["分發"],"dispense cash",2),
("divest","v",["撤資","出售"],"divest assets",2),
("divestiture","n",["資產剝離"],"forced divestiture",3),
("downturn","n",["低迷"],"economic downturn",2),
("durable","adj",["耐用的"],"durable goods",1),
("earmark","v",["指定用途"],"earmark funds",2),
("embargo","n",["禁運"],"trade embargo",2),
("embezzle","v",["挪用","侵占"],"embezzle funds",3),
("encumber","v",["設定負擔"],"encumber property",3),
("endow","v",["捐贈"],"endow a fund",2),
("endowment","n",["捐贈基金"],"university endowment",2),
("enumerate","v",["列舉"],"enumerate expenses",2),
("equitable","adj",["公平的"],"equitable distribution",2),
("erode","v",["侵蝕"],"erode profits",2),
("estimation","n",["估算"],"cost estimation",1),
("excise","n",["消費稅"],"excise duty",2),
("exonerate","v",["免除"],"exonerate from debt",3),
("expedient","adj",["權宜的"],"financially expedient",3),
("expendable","adj",["可消耗的"],"expendable supplies",2),
("expenditure","n",["支出","開銷"],"capital expenditure",2),
("fiscal","adj",["財政的"],"fiscal policy",2),
("fluctuation","n",["波動"],"market fluctuation",2),
("foreclose","v",["取消贖回權"],"foreclose a mortgage",3),
("forge","v",["偽造"],"forge a signature",2),
("fortify","v",["加強"],"fortify finances",2),
("franchise","n",["特許經營"],"franchise agreement",2),
("frugal","adj",["節儉的"],"frugal spending",2),
("garnish","v",["扣押工資"],"garnish wages",3),
("glut","n",["供過於求"],"market glut",2),
("goodwill","n",["商譽"],"intangible goodwill",2),
("grant","n",["補助金"],"government grant",1),
("gross","adj",["總額的"],"gross income",1),
("guarantee","n",["擔保"],"loan guarantee",1),
("hedge","v",["對沖","避險"],"hedge risk",2),
("hoard","v",["囤積"],"hoard cash",2),
("hypothetical","adj",["假設的"],"hypothetical scenario",2),
("illiquid","adj",["缺乏流動性的"],"illiquid assets",3),
("impound","v",["扣押"],"impound assets",3),
("incentivize","v",["激勵"],"incentivize savings",2),
("increment","n",["增量"],"pay increment",2),
("indebtedness","n",["負債"],"level of indebtedness",2),
("indemnify","v",["賠償","補償"],"indemnify losses",3),
("indemnity","n",["賠償","保障"],"indemnity insurance",3),
("inflate","v",["膨脹","使通膨"],"inflate prices",2),
("inflationary","adj",["通膨的"],"inflationary pressure",2),
("inflow","n",["流入"],"capital inflow",2),
("inheritance","n",["遺產"],"inheritance tax",1),
("insolvency","n",["無力償債"],"declare insolvency",3),
("insolvent","adj",["無力償債的"],"declared insolvent",3),
("intangible","adj",["無形的"],"intangible assets",2),
("inventorize","v",["盤存"],"inventorize assets",3),
("invoice","v",["開發票"],"invoice clients",1),
("irrecoverable","adj",["無法收回的"],"irrecoverable debt",3),
("itemize","v",["逐條列出"],"itemize expenses",2),
("kickback","n",["回扣"],"illegal kickback",2),
("lease","v",["租賃"],"lease equipment",1),
("ledger","n",["帳簿","分類帳"],"general ledger",2),
("lending","n",["貸款","放款"],"lending rate",1),
("leverage","n",["槓桿"],"financial leverage",2),
("levy","n",["徵稅"],"tax levy",2),
("liabilities","n",["負債"],"current liabilities",2),
("liquidate","v",["清算"],"liquidate assets",2),
("liquidity","n",["流動性"],"ensure liquidity",2),
("lucrative","adj",["有利可圖的"],"lucrative investment",2),
("lump","n",["一次性"],"lump sum",1),
("macroeconomics","n",["總體經濟學"],"macroeconomics course",3),
("margin","n",["利潤率"],"profit margin",1),
("markup","n",["加價"],"product markup",1),
("maturation","n",["到期"],"bond maturation",3),
("mercantile","adj",["商業的"],"mercantile exchange",3),
("merge","v",["合併"],"merge accounts",2),
("microfinance","n",["微型貸款"],"microfinance institution",2),
("miscalculate","v",["誤算"],"miscalculate costs",2),
("monetize","v",["貨幣化"],"monetize assets",2),
("monitory","adj",["勸告的"],"monitory letter",3),
("moratorium","n",["暫停"],"debt moratorium",3),
("municipal","adj",["市政的"],"municipal bonds",2),
("nationalize","v",["國有化"],"nationalize banks",3),
("negotiate","v",["談判"],"negotiate rates",1),
("net","adj",["淨的"],"net income",1),
("nominal","adj",["名義上的"],"nominal interest",2),
("offset","v",["抵消"],"offset losses",2),
("outflow","n",["流出"],"capital outflow",2),
("outlay","n",["支出"],"capital outlay",2),
("outstanding","adj",["未償還的"],"outstanding debt",1),
("overcapitalize","v",["過度資本化"],"overcapitalize a firm",3),
("overdraft","n",["透支"],"bank overdraft",2),
("overhead","n",["間接費用"],"overhead costs",2),
("parity","n",["平價"],"purchasing parity",2),
("payable","adj",["應付的"],"accounts payable",1),
("payroll","n",["薪資單","工資總額"],"process payroll",1),
("pecuniary","adj",["金錢的"],"pecuniary gain",3),
("per annum","adv",["每年"],"five percent per annum",2),
("per capita","adv",["每人"],"income per capita",2),
("petty","adj",["少量的","瑣碎的"],"petty cash",1),
("pledge","n",["質押"],"asset pledge",2),
("plummet","v",["暴跌"],"stock prices plummet",2),
("portfolio","n",["投資組合"],"diversified portfolio",2),
("precipitous","adj",["急劇的"],"precipitous decline",2),
("premium","n",["溢價","保費"],"insurance premium",2),
("proceeds","n",["收益","所得"],"sale proceeds",2),
("procure","v",["取得"],"procure funds",2),
("prodigious","adj",["巨大的"],"prodigious sum",3),
("profit","v",["獲利"],"profit from trade",1),
("profitability","n",["盈利能力"],"improve profitability",2),
("prorate","v",["按比例分配"],"prorate expenses",2),
("provision","n",["準備金"],"bad debt provision",2),
("prudent","adj",["審慎的"],"prudent investment",2),
("quarterly","adj",["季度的"],"quarterly report",1),
("quota","n",["配額"],"sales quota",2),
("rebound","v",["反彈"],"prices rebound",2),
("receivable","adj",["應收的"],"accounts receivable",1),
("recession","n",["經濟衰退"],"deep recession",1),
("recoup","v",["收回","補回"],"recoup losses",2),
("recuperate","v",["恢復"],"recuperate losses",2),
("redeem","v",["贖回","兌換"],"redeem a bond",2),
("reimburse","v",["報銷"],"reimburse travel",2),
("reimbursement","n",["報銷","償還"],"expense reimbursement",2),
("remit","v",["匯款"],"remit payment",2),
("remunerate","v",["報酬"],"remunerate employees",2),
("remuneration","n",["報酬","薪酬"],"total remuneration",2),
("repayment","n",["償還"],"loan repayment",1),
("replenish","v",["補充"],"replenish reserves",2),
("reserve","n",["儲備金"],"cash reserve",2),
("residual","adj",["剩餘的"],"residual value",2),
("restitution","n",["賠償","歸還"],"make restitution",3),
("restructure","v",["重組"],"restructure debt",2),
("retainer","n",["預付費","聘用費"],"annual retainer",2),
("retroactive","adj",["追溯的"],"retroactive payment",2),
("returns","n",["回報"],"diminishing returns",2),
("revenue","n",["營收"],"annual revenue",1),
("rollover","n",["續期"],"loan rollover",2),
("salvage","v",["挽救"],"salvage value",2),
("scrutinize","v",["審查"],"scrutinize accounts",2),
("securities","n",["證券"],"government securities",2),
("shrinkage","n",["縮水","損耗"],"inventory shrinkage",2),
("slash","v",["大幅削減"],"slash costs",1),
("solvent","adj",["有償付能力的"],"remain solvent",2),
("speculator","n",["投機者"],"market speculator",2),
("stagnation","n",["停滯"],"economic stagnation",2),
("stipend","n",["津貼","薪俸"],"monthly stipend",2),
("subprime","adj",["次級的"],"subprime lending",2),
("subsidy","n",["補貼","津貼"],"government subsidy",2),
("subsidize","v",["補貼"],"subsidize housing",2),
("surplus","n",["盈餘"],"budget surplus",2),
("surtax","n",["附加稅"],"income surtax",3),
("tabulate","v",["列表"],"tabulate results",2),
("tally","v",["計算","合計"],"tally receipts",2),
("tangible","adj",["有形的"],"tangible assets",1),
("tariff","n",["關稅"],"import tariff",2),
("tenet","n",["原則"],"accounting tenet",3),
("tenure","n",["任期"],"investment tenure",2),
("thrift","n",["節儉"],"practice thrift",2),
("transact","v",["交易"],"transact business",2),
("transparency","n",["透明度"],"financial transparency",2),
("treasury","n",["國庫","財務部"],"corporate treasury",2),
("turmoil","n",["動盪"],"market turmoil",2),
("underwrite","v",["承銷"],"underwrite securities",3),
("unearned","adj",["未賺得的"],"unearned revenue",2),
("unrealized","adj",["未實現的"],"unrealized gains",2),
("valuation","n",["估值"],"company valuation",2),
("variance","n",["差異","偏差"],"budget variance",2),
("verify","v",["核實"],"verify accounts",1),
("volatile","adj",["波動的"],"volatile market",2),
("voucher","n",["憑單","代金券"],"payment voucher",1),
("windfall","n",["意外之財"],"windfall profit",2),
("withhold","v",["扣留"],"withhold taxes",2),
("write-off","n",["沖銷"],"bad debt write-off",2),
("yield","n",["收益率"],"bond yield",2),
],
"cat03": [
("affiliate","n",["聯盟夥伴"],"affiliate marketing",2),
("aggressive","adj",["積極的"],"aggressive campaign",2),
("algorithm","n",["演算法"],"search algorithm",2),
("analytics","n",["分析學"],"web analytics",2),
("appeal","n",["吸引力"],"broad appeal",1),
("aspiring","adj",["有抱負的"],"aspiring brand",2),
("billboard","n",["看板","廣告牌"],"billboard advertising",1),
("boost","v",["提升"],"boost sales",1),
("brainstorm","v",["腦力激盪"],"brainstorm ideas",1),
("brand","n",["品牌"],"brand loyalty",1),
("branding","n",["品牌塑造"],"corporate branding",1),
("broadcast","v",["廣播"],"broadcast a commercial",1),
("brochure","n",["手冊"],"product brochure",1),
("browser","n",["瀏覽器"],"web browser",1),
("bundle","v",["捆綁"],"bundle products",1),
("catalogue","n",["目錄"],"product catalogue",1),
("circulation","n",["發行量"],"newspaper circulation",2),
("clientele","n",["客戶群"],"loyal clientele",2),
("collaborate","v",["合作"],"collaborate on campaigns",1),
("collateral","n",["宣傳品"],"marketing collateral",2),
("commercial","n",["廣告"],"TV commercial",1),
("commission","n",["佣金"],"sales commission",2),
("commodity","n",["商品"],"commodity market",2),
("compatible","adj",["相容的"],"compatible products",1),
("compelling","adj",["引人注目的"],"compelling offer",2),
("competitive","adj",["有競爭力的"],"competitive pricing",1),
("complement","v",["補充"],"complement a range",2),
("concept","n",["概念"],"marketing concept",1),
("concession","n",["讓步","優惠"],"price concession",2),
("consolidate","v",["整合"],"consolidate market share",2),
("consumer","n",["消費者"],"consumer demand",1),
("consumption","n",["消費"],"domestic consumption",2),
("content","n",["內容"],"digital content",1),
("conversion","n",["轉換"],"conversion rate",2),
("coupon","n",["優惠券"],"discount coupon",1),
("craft","v",["精心製作"],"craft a message",1),
("credibility","n",["信譽"],"brand credibility",2),
("customize","v",["客製化"],"customize products",1),
("dashboard","n",["儀表板"],"analytics dashboard",1),
("debut","n",["首次亮相"],"product debut",1),
("demographic","n",["人口統計"],"target demographic",2),
("deploy","v",["部署"],"deploy a campaign",2),
("differentiate","v",["差異化"],"differentiate products",2),
("diminish","v",["減少"],"diminish in value",2),
("discount","n",["折扣"],"volume discount",1),
("dispatch","v",["發送"],"dispatch orders",2),
("display","v",["展示"],"display products",1),
("distribute","v",["分銷"],"distribute goods",1),
("diversify","v",["多元化"],"diversify product line",2),
("dynamic","adj",["動態的"],"dynamic pricing",1),
("e-commerce","n",["電子商務"],"e-commerce platform",1),
("edge","n",["優勢"],"competitive edge",1),
("elevate","v",["提升"],"elevate brand image",2),
("embed","v",["嵌入"],"embed ads",2),
("emerging","adj",["新興的"],"emerging market",1),
("endorse","v",["代言","背書"],"endorse a product",2),
("endorsement","n",["代言","認可"],"celebrity endorsement",2),
("engage","v",["吸引","互動"],"engage customers",1),
("engagement","n",["互動","參與"],"customer engagement",1),
("enhance","v",["增強"],"enhance visibility",1),
("enthusiasm","n",["熱情"],"consumer enthusiasm",1),
("escalate","v",["升級"],"escalate promotions",2),
("evaluate","v",["評估"],"evaluate effectiveness",1),
("evolve","v",["發展"],"evolve strategies",2),
("exclusive","adj",["獨家的"],"exclusive deal",1),
("exemplify","v",["體現"],"exemplify quality",2),
("exhibit","v",["展出"],"exhibit at a show",1),
("expand","v",["擴展"],"expand reach",1),
("exploit","v",["利用","開發"],"exploit a niche",2),
("exposure","n",["曝光","暴露"],"brand exposure",1),
("feasibility","n",["可行性"],"market feasibility",2),
("fervent","adj",["熱情的"],"fervent supporter",2),
("fidelity","n",["忠誠度"],"brand fidelity",2),
("flagship","n",["旗艦"],"flagship product",1),
("flair","n",["天賦","才華"],"marketing flair",2),
("flyer","n",["傳單"],"promotional flyer",1),
("forecast","v",["預測"],"forecast demand",1),
("formulate","v",["制定"],"formulate a plan",2),
("foster","v",["培養"],"foster relationships",2),
("funnel","n",["銷售漏斗"],"marketing funnel",2),
("gauge","v",["衡量"],"gauge demand",2),
("generate","v",["產生"],"generate leads",1),
("goodwill","n",["商譽"],"brand goodwill",2),
("harness","v",["利用"],"harness social media",2),
("highlight","v",["突出"],"highlight features",1),
("holistic","adj",["整體的"],"holistic approach",2),
("hype","n",["炒作"],"media hype",1),
("iconic","adj",["標誌性的"],"iconic brand",1),
("impactful","adj",["有影響力的"],"impactful campaign",2),
("implement","v",["執行"],"implement a strategy",1),
("incentive","n",["獎勵"],"purchase incentive",2),
("inflate","v",["膨脹"],"inflate expectations",2),
("influencer","n",["網紅","意見領袖"],"social media influencer",1),
("infographic","n",["資訊圖表"],"create infographics",1),
("innovative","adj",["創新的"],"innovative product",1),
("insight","n",["洞察"],"consumer insight",1),
("integrate","v",["整合"],"integrate channels",2),
("interact","v",["互動"],"interact with customers",1),
("inventory","n",["庫存"],"manage inventory",1),
("iterate","v",["迭代"],"iterate on design",2),
("jingle","n",["廣告歌曲"],"catchy jingle",1),
("kickstart","v",["啟動"],"kickstart a campaign",1),
("landscape","n",["格局"],"competitive landscape",2),
("launch","v",["推出"],"launch a product",1),
("leverage","v",["利用"],"leverage data",2),
("loyalty","n",["忠誠度"],"customer loyalty",1),
("lucrative","adj",["有利可圖的"],"lucrative deal",2),
("mainstream","adj",["主流的"],"mainstream market",1),
("mandate","n",["授權"],"marketing mandate",2),
("maximize","v",["最大化"],"maximize ROI",1),
("milestone","n",["里程碑"],"marketing milestone",1),
("monetize","v",["變現"],"monetize content",2),
("monopoly","n",["壟斷"],"market monopoly",2),
("niche","n",["利基","利基市場"],"niche market",1),
("optimize","v",["最佳化"],"optimize content",2),
("outpace","v",["超過"],"outpace competitors",2),
("outreach","n",["推廣"],"customer outreach",2),
("patron","n",["贊助者","常客"],"loyal patron",1),
("penetrate","v",["滲透"],"penetrate new markets",2),
("perception","n",["認知"],"brand perception",2),
("personalize","v",["個人化"],"personalize offers",1),
("persuade","v",["說服"],"persuade customers",1),
("pitch","n",["提案","推銷"],"sales pitch",1),
("placement","n",["放置","置入"],"product placement",1),
("platform","n",["平台"],"digital platform",1),
("pledge","v",["承諾"],"pledge quality",2),
("plunge","v",["暴跌"],"sales plunge",2),
("podcast","n",["播客"],"brand podcast",1),
("positioning","n",["定位"],"brand positioning",2),
("premier","adj",["首要的"],"premier brand",1),
("premium","adj",["高級的"],"premium product",1),
("prevail","v",["盛行"],"trends prevail",2),
("profile","n",["形象","概況"],"customer profile",1),
("prominence","n",["突出","顯著"],"market prominence",2),
("prospect","n",["潛在客戶"],"sales prospect",1),
("prospective","adj",["潛在的"],"prospective buyer",2),
("prototype","n",["原型"],"product prototype",2),
("publicist","n",["公關人員"],"brand publicist",2),
("rapport","n",["融洽關係"],"build rapport",2),
("rebrand","v",["重新塑造品牌"],"rebrand the company",2),
("rebate","n",["折扣","回扣"],"mail-in rebate",1),
("receptive","adj",["善於接受的"],"receptive audience",2),
("referral","n",["推薦"],"customer referral",1),
("reshape","v",["重塑"],"reshape strategy",2),
("resonate","v",["引起共鳴"],"resonate with users",2),
("retail","n",["零售"],"retail market",1),
("retain","v",["留住"],"retain customers",1),
("revenue","n",["營收"],"ad revenue",1),
("revamp","v",["翻新"],"revamp the brand",2),
("rival","n",["競爭對手"],"market rival",1),
("rollout","n",["推出"],"product rollout",1),
("saturate","v",["飽和"],"saturated market",2),
("segment","v",["細分"],"segment the market",2),
("showcase","v",["展示"],"showcase features",1),
("slogan","n",["口號","標語"],"brand slogan",1),
("solicit","v",["徵求"],"solicit feedback",2),
("sponsor","v",["贊助"],"sponsor an event",1),
("stagnate","v",["停滯"],"sales stagnate",2),
("stimulate","v",["刺激"],"stimulate demand",2),
("strategize","v",["制定策略"],"strategize growth",2),
("subscriber","n",["訂戶"],"email subscriber",1),
("surge","n",["激增"],"sales surge",1),
("survey","n",["調查"],"customer survey",1),
("sustain","v",["維持"],"sustain growth",1),
("tailor","v",["量身訂做"],"tailor campaigns",2),
("testimonial","n",["推薦書"],"customer testimonial",1),
("thrive","v",["繁榮"],"brand thrives",2),
("trademark","n",["商標"],"registered trademark",2),
("trend","n",["趨勢"],"market trend",1),
("undercut","v",["削價"],"undercut competitors",2),
("unprecedented","adj",["前所未有的"],"unprecedented growth",1),
("unveil","v",["揭幕"],"unveil a product",2),
("upscale","adj",["高檔的"],"upscale market",1),
("upsell","v",["追加銷售"],"upsell services",2),
("venture","n",["冒險"],"business venture",2),
("versatile","adj",["多用途的"],"versatile product",1),
("viral","adj",["病毒式的"],"viral marketing",1),
("visibility","n",["能見度","知名度"],"brand visibility",1),
("wholesale","n",["批發"],"wholesale market",2),
],
"cat04": [
("absenteeism","n",["曠工","缺勤"],"reduce absenteeism",2),
("accommodate","v",["適應"],"accommodate requests",1),
("acclimate","v",["適應"],"acclimate to culture",2),
("acknowledge","v",["承認"],"acknowledge contributions",1),
("adeptly","adv",["熟練地"],"adeptly manage",2),
("adjourn","v",["休會"],"adjourn the meeting",2),
("administer","v",["管理"],"administer benefits",2),
("advocate","n",["提倡者"],"employee advocate",2),
("affirmative","adj",["肯定的"],"affirmative action",2),
("aggregate","v",["匯總"],"aggregate data",2),
("alleviate","v",["減輕"],"alleviate stress",2),
("allowance","n",["津貼"],"housing allowance",1),
("amicable","adj",["友好的"],"amicable resolution",2),
("anonymous","adj",["匿名的"],"anonymous feedback",1),
("appoint","v",["任命"],"appoint a successor",2),
("appraise","v",["評價"],"appraise performance",2),
("aptitude","n",["資質","才能"],"aptitude test",2),
("arbitrate","v",["仲裁"],"arbitrate a dispute",3),
("aspiration","n",["抱負"],"career aspiration",2),
("assimilate","v",["融入"],"assimilate new hires",2),
("attrition","n",["自然減員"],"staff attrition",2),
("benchmarking","n",["標竿學習"],"salary benchmarking",2),
("bias","n",["偏見"],"unconscious bias",2),
("burnout","n",["倦怠"],"employee burnout",2),
("calibrate","v",["校準"],"calibrate reviews",2),
("cohesion","n",["凝聚力"],"team cohesion",2),
("collaborate","v",["合作"],"collaborate across teams",1),
("commend","v",["表揚"],"commend performance",2),
("compensate","v",["補償"],"compensate fairly",2),
("competency","n",["能力"],"core competency",2),
("compliance","n",["合規"],"HR compliance",2),
("conciliate","v",["調解"],"conciliate parties",3),
("confidentiality","n",["保密","機密性"],"maintain confidentiality",2),
("counsel","v",["輔導"],"counsel employees",2),
("credential","n",["資格"],"professional credential",2),
("culminate","v",["達到高潮"],"culminate in promotion",2),
("delegate","v",["委派"],"delegate authority",2),
("demote","v",["降職"],"demote an employee",2),
("deploy","v",["部署"],"deploy talent",2),
("designate","v",["指派"],"designate a role",2),
("deter","v",["阻止","震懾"],"deter misconduct",2),
("diligent","adj",["勤奮的"],"diligent worker",1),
("discipline","v",["懲戒"],"discipline staff",2),
("discreet","adj",["謹慎的"],"discreet handling",2),
("discriminate","v",["歧視"],"discriminate against",2),
("discrimination","n",["歧視"],"workplace discrimination",2),
("dismiss","v",["解僱"],"dismiss an employee",2),
("diverse","adj",["多元的"],"diverse workforce",1),
("diversity","n",["多樣性"],"promote diversity",1),
("downsizing","n",["裁員","縮編"],"corporate downsizing",2),
("eligible","adj",["合格的"],"eligible for promotion",1),
("empower","v",["賦權"],"empower employees",2),
("endorse","v",["認可"],"endorse a candidate",2),
("enact","v",["制定"],"enact policies",2),
("engage","v",["投入"],"engage the team",1),
("entitle","v",["賦予權利"],"entitled to leave",1),
("evaluate","v",["評估"],"evaluate candidates",1),
("expatriate","n",["外派人員"],"manage expatriates",2),
("facilitate","v",["促進"],"facilitate training",2),
("furlough","n",["無薪假"],"temporary furlough",2),
("grievance","n",["申訴"],"file a grievance",2),
("harassment","n",["騷擾"],"workplace harassment",2),
("hardship","n",["困難"],"financial hardship",2),
("headcount","n",["人數"],"reduce headcount",1),
("hierarchy","n",["層級"],"organizational hierarchy",2),
("incentivize","v",["激勵"],"incentivize employees",2),
("inclusive","adj",["包容的"],"inclusive workplace",1),
("induct","v",["就職","使入門"],"induct new hires",2),
("insubordination","n",["不服從"],"acts of insubordination",3),
("lateral","adj",["橫向的"],"lateral move",2),
("layoff","n",["裁員"],"massive layoff",1),
("mandate","v",["強制要求"],"mandate training",2),
("mediate","v",["調解"],"mediate conflict",2),
("mentor","v",["指導"],"mentor junior staff",1),
("misconduct","n",["瀆職","行為不當"],"employee misconduct",2),
("morale","n",["士氣"],"boost morale",1),
("negotiate","v",["談判"],"negotiate salary",1),
("nepotism","n",["裙帶關係"],"avoid nepotism",3),
("non-disclosure","n",["保密"],"non-disclosure agreement",2),
("nurture","v",["培養"],"nurture talent",2),
("objective","n",["目標"],"performance objective",1),
("onboarding","n",["入職引導"],"employee onboarding",1),
("orient","v",["培訓"],"orient new hires",1),
("outplacement","n",["再就業服務"],"outplacement assistance",2),
("outsource","v",["外包"],"outsource HR",2),
("overtime","n",["加班"],"work overtime",1),
("peer","n",["同儕"],"peer review",1),
("pension","n",["退休金"],"pension plan",1),
("performance","n",["績效"],"performance review",1),
("personnel","n",["人事","人員"],"personnel department",1),
("placement","n",["安排","安置"],"job placement",1),
("probation","n",["試用期"],"probation period",2),
("proficient","adj",["精通的"],"proficient in skills",1),
("prohibition","n",["禁止"],"workplace prohibition",2),
("promotion","n",["晉升"],"earn promotion",1),
("qualification","n",["資格"],"job qualification",1),
("reassign","v",["重新分配"],"reassign duties",2),
("reconcile","v",["調和"],"reconcile differences",2),
("redeployment","n",["重新調配"],"staff redeployment",2),
("redundancy","n",["裁員","冗餘"],"make redundancies",2),
("reimburse","v",["報銷"],"reimburse relocations",2),
("relocate","v",["調遷"],"relocate employees",1),
("remunerate","v",["給報酬"],"remunerate fairly",2),
("reprimand","v",["訓斥"],"formal reprimand",2),
("resign","v",["辭職"],"resign voluntarily",1),
("restructure","v",["重組"],"restructure team",2),
("retain","v",["留住"],"retain talent",1),
("retire","v",["退休"],"retire early",1),
("retrench","v",["縮減","裁員"],"retrench staff",2),
("sabbatical","n",["安息休假"],"take a sabbatical",2),
("sanction","v",["制裁"],"sanction misconduct",2),
("seniority","n",["資歷"],"based on seniority",2),
("severance","n",["遣散費"],"severance package",2),
("shortlist","v",["列入候選名單"],"shortlist candidates",2),
("stipulate","v",["規定"],"stipulate conditions",2),
("subordinate","n",["下屬"],"manage subordinates",2),
("succession","n",["繼任"],"succession plan",2),
("terminate","v",["終止"],"terminate employment",2),
("tenure","n",["任期"],"long tenure",2),
("transition","n",["過渡"],"career transition",1),
("turnover","n",["離職率"],"reduce turnover",1),
("underperform","v",["表現不佳"],"underperform expectations",2),
("vacancy","n",["空缺"],"fill a vacancy",1),
("vet","v",["審查"],"vet candidates",2),
("whistleblower","n",["舉報人"],"whistleblower protection",2),
("workforce","n",["勞動力"],"skilled workforce",1),
("workload","n",["工作量"],"manage workload",1),
],
"cat05": [
("abrasion","n",["磨損"],"surface abrasion",2),
("assemble","v",["組裝"],"assemble components",1),
("automate","v",["自動化"],"automate production",2),
("benchmark","n",["基準"],"quality benchmark",2),
("bottleneck","n",["瓶頸"],"production bottleneck",2),
("calibrate","v",["校準"],"calibrate instruments",2),
("capacity","n",["產能"],"production capacity",1),
("comply","v",["遵守"],"comply with standards",2),
("component","n",["零件"],"key component",1),
("configure","v",["配置"],"configure machinery",2),
("contaminate","v",["污染"],"contaminate products",2),
("convey","v",["輸送"],"convey materials",1),
("corrective","adj",["糾正的"],"corrective action",2),
("criterion","n",["標準"],"quality criterion",2),
("curtail","v",["縮減"],"curtail waste",2),
("customize","v",["客製化"],"customize orders",1),
("deficiency","n",["缺陷"],"quality deficiency",2),
("deploy","v",["部署"],"deploy resources",2),
("deviation","n",["偏差"],"quality deviation",2),
("diagnose","v",["診斷"],"diagnose problems",2),
("disassemble","v",["拆解"],"disassemble a unit",2),
("discontinue","v",["停產"],"discontinue a model",2),
("dispatch","v",["派送"],"dispatch goods",2),
("downtime","n",["停機時間"],"minimize downtime",1),
("durable","adj",["耐用的"],"durable material",1),
("efficiency","n",["效率"],"production efficiency",1),
("emission","n",["排放"],"carbon emission",2),
("ergonomic","adj",["人體工學的"],"ergonomic design",2),
("expedite","v",["加速"],"expedite delivery",2),
("fabricate","v",["製造"],"fabricate parts",2),
("facility","n",["設施"],"manufacturing facility",1),
("faulty","adj",["有故障的"],"faulty equipment",1),
("feasibility","n",["可行性"],"feasibility study",2),
("fluctuate","v",["波動"],"output fluctuates",2),
("forklift","n",["堆高機"],"operate a forklift",1),
("gauge","n",["量規"],"pressure gauge",2),
("hazardous","adj",["危險的"],"hazardous material",2),
("implement","v",["實施"],"implement improvements",1),
("incorporate","v",["納入"],"incorporate feedback",2),
("infrastructure","n",["基礎設施"],"manufacturing infrastructure",2),
("innovate","v",["創新"],"innovate processes",2),
("inspect","v",["檢驗"],"inspect products",1),
("integrate","v",["整合"],"integrate systems",2),
("inventory","n",["庫存"],"manage inventory",1),
("lean","adj",["精實的"],"lean manufacturing",2),
("logistics","n",["物流"],"supply logistics",2),
("maintain","v",["維護"],"maintain equipment",1),
("malfunction","n",["故障"],"equipment malfunction",1),
("manufacture","v",["製造"],"manufacture goods",1),
("mechanism","n",["機制"],"safety mechanism",2),
("mitigate","v",["減輕"],"mitigate risk",2),
("modify","v",["修改"],"modify a design",1),
("monitor","v",["監控"],"monitor production",1),
("obsolete","adj",["過時的"],"obsolete equipment",2),
("operate","v",["操作"],"operate machinery",1),
("optimal","adj",["最佳的"],"optimal output",2),
("optimize","v",["最佳化"],"optimize processes",2),
("output","n",["產出"],"daily output",1),
("overhaul","v",["大修"],"overhaul equipment",2),
("patent","n",["專利"],"file a patent",2),
("precision","n",["精密度"],"high precision",2),
("preventive","adj",["預防的"],"preventive maintenance",2),
("procurement","n",["採購"],"procurement process",2),
("productivity","n",["生產力"],"increase productivity",1),
("prototype","n",["原型"],"build a prototype",2),
("quality","n",["品質"],"quality control",1),
("quarantine","v",["隔離"],"quarantine defects",2),
("raw","adj",["原始的","生的"],"raw materials",1),
("recalibrate","v",["重新校準"],"recalibrate instruments",2),
("rectify","v",["糾正"],"rectify defects",2),
("redundancy","n",["備援"],"system redundancy",2),
("refine","v",["精煉","改進"],"refine processes",2),
("refurbish","v",["翻新"],"refurbish equipment",2),
("regulate","v",["調節"],"regulate temperature",2),
("reliability","n",["可靠性"],"product reliability",2),
("remanufacture","v",["再製造"],"remanufacture parts",2),
("replicate","v",["複製"],"replicate results",2),
("repurpose","v",["重新利用"],"repurpose materials",2),
("retrofit","v",["改裝"],"retrofit equipment",2),
("robust","adj",["堅固的"],"robust design",2),
("safeguard","n",["安全措施"],"safety safeguard",2),
("salvage","v",["搶救"],"salvage materials",2),
("scalable","adj",["可擴展的"],"scalable production",2),
("schematic","n",["示意圖"],"electrical schematic",2),
("shipment","n",["出貨"],"track shipment",1),
("simulate","v",["模擬"],"simulate conditions",2),
("specification","n",["規格"],"product specification",1),
("standardize","v",["標準化"],"standardize processes",2),
("streamline","v",["精簡"],"streamline production",2),
("subcontract","v",["分包"],"subcontract work",2),
("sustainability","n",["永續性"],"environmental sustainability",2),
("throughput","n",["產出量"],"increase throughput",2),
("tolerance","n",["公差"],"manufacturing tolerance",2),
("traceability","n",["可追溯性"],"product traceability",2),
("troubleshoot","v",["故障排除"],"troubleshoot issues",1),
("turnaround","n",["周轉時間"],"fast turnaround",1),
("upgrade","v",["升級"],"upgrade equipment",1),
("validate","v",["驗證"],"validate results",2),
("variance","n",["偏差"],"quality variance",2),
("vendor","n",["供應商"],"approved vendor",1),
("verify","v",["核實"],"verify quality",1),
("volatile","adj",["不穩定的"],"volatile demand",2),
("warehouse","n",["倉庫"],"storage warehouse",1),
("warranty","n",["保固"],"product warranty",1),
("waste","n",["浪費"],"minimize waste",1),
("yield","n",["良率","產量"],"production yield",2),
],
}
